import Foundation
import Testing
@testable import WingFoilKit

/// Cross-implementation golden tests (docs/testing.md): for every
/// `fixtures/goldens/<stem>.expected.json` written by the lab, run the full Swift
/// pipeline on the matching FIT and assert within tolerances — counts exact,
/// speeds ± 0.05 kn (alpha ± 0.1), timestamps ± 1 s, foil time ± 2 %.
/// Goldens are read leniently (JSONSerialization), so extra/experimental keys from
/// the lab never break decoding; only contracted quantities are asserted.
@Suite struct GoldenTests {

    @Test func goldensMatchWhenPresent() throws {
        let dir = testFixturesDir.appendingPathComponent("goldens")
        let goldens = ((try? FileManager.default.contentsOfDirectory(
            at: dir, includingPropertiesForKeys: nil)) ?? [])
            .filter { $0.lastPathComponent.hasSuffix(".expected.json") }
            .sorted { $0.lastPathComponent < $1.lastPathComponent }
        guard !goldens.isEmpty else {
            print("GoldenTests: fixtures/goldens contains no *.expected.json yet "
                  + "(generated by the lab workstream) — zero assertions, passing.")
            return
        }
        for golden in goldens {
            try check(golden: golden)
        }
    }

    private func check(golden url: URL) throws {
        let stem = String(url.lastPathComponent.dropLast(".expected.json".count))
        guard let fitURL = findFixtureFIT(stem: stem) else {
            Issue.record("golden \(stem): no \(stem).fit under fixtures/sessions or fixtures/synthetic")
            return
        }
        guard let json = try JSONSerialization.jsonObject(with: Data(contentsOf: url))
                as? [String: Any] else {
            Issue.record("golden \(stem): top level is not a JSON object")
            return
        }

        // Run with the parameters the golden was generated with (config echo).
        var filter = FilterConfig()
        var flight = FlightConfig()
        var recCfg = RecordsConfig()
        if let cfg = json["config"] as? [String: Any] {
            if let v = num(cfg["foilEntrySpeed"]) { flight.foilEntrySpeedKmh = v }
            if let v = num(cfg["foilExitSpeed"]) { flight.foilExitSpeedKmh = v }
            if let v = num(cfg["entryHold"]) { flight.entryHoldS = v }
            if let v = num(cfg["exitHold"]) { flight.exitHoldS = v }
            if let v = num(cfg["minFlightDuration"]) { flight.minFlightDurationS = v }
            if let v = num(cfg["maxAccel1Hz"]) { filter.maxAccelMps2 = v }
            if let v = num(cfg["gapMinS"]) { filter.gapMinS = v }
            if let v = num(cfg["gapFactor"]) { filter.gapFactor = v }
            if let v = num(cfg["alphaProximity"]) { recCfg.alphaProximityM = v }
            if let v = num(cfg["alphaMaxDistance"]) { recCfg.alphaMaxDistanceM = v }
        }
        let raw = try FitSessionParser.parse(url: fitURL)
        let analysis = SessionSummarizer.analyze(raw, filterConfig: filter,
                                                 flightConfig: flight, recordsConfig: recCfg)

        if let expCaps = json["capabilities"] as? [String: Any] {
            let caps = AnalysisCapabilities(raw.capabilities)
            let flags: [(String, Bool)] = [
                ("hasDoppler", caps.hasDoppler), ("hasDevFields", caps.hasDevFields),
                ("hasWatchLaps", caps.hasWatchLaps), ("hasAccel", caps.hasAccel),
                ("hasHR", caps.hasHR),
            ]
            for (key, actual) in flags {
                guard let expected = expCaps[key] as? Bool else { continue }
                #expect(actual == expected,
                        "\(stem) capabilities.\(key): \(actual) vs \(expected)")
            }
            if let v = num(expCaps["sampleRateHz"]) {
                #expect(abs(caps.sampleRateHz - v) <= 0.01,
                        "\(stem) capabilities.sampleRateHz: \(caps.sampleRateHz) vs \(v)")
            }
        }

        if let expFlights = json["flights"] as? [[String: Any]] {
            #expect(analysis.flights.count == expFlights.count,
                    "\(stem): flight count \(analysis.flights.count) != \(expFlights.count)")
            for (i, pair) in zip(expFlights, analysis.flights).enumerated() {
                let (exp, act) = pair
                if let v = num(exp["startTs"]) {
                    #expect(abs(act.startTs - v) <= 1.0, "\(stem) flights[\(i)].startTs")
                }
                if let v = num(exp["endTs"]) {
                    #expect(abs(act.endTs - v) <= 1.0, "\(stem) flights[\(i)].endTs")
                }
                if let v = num(exp["maxKn"]) {
                    #expect(abs(act.maxKn - v) <= 0.05, "\(stem) flights[\(i)].maxKn")
                }
                if let v = num(exp["distM"]) {
                    #expect(abs(act.distM - v) <= max(0.02 * abs(v), 5),
                            "\(stem) flights[\(i)].distM")
                }
            }
        }

        if let expRecords = json["records"] as? [String: Any] {
            let keys: [(String, Double, KeyPath<GP3SRecords, Double?>)] = [
                ("best2sKn", 0.05, \.best2sKn), ("best10sKn", 0.05, \.best10sKn),
                ("best5x10sKn", 0.05, \.best5x10sKn), ("best100mKn", 0.05, \.best100mKn),
                ("best250mKn", 0.05, \.best250mKn), ("best500mKn", 0.05, \.best500mKn),
                ("bestNmKn", 0.05, \.bestNmKn), ("bestHourKn", 0.05, \.bestHourKn),
                ("alpha500Kn", 0.10, \.alpha500Kn),
            ]
            for (key, tol, kp) in keys where expRecords.keys.contains(key) {
                // Contract (docs/testing.md): a non-qualifying record serializes as 0.0
                // in goldens and as nil in the Swift model — the two are equivalent.
                let exp = num(expRecords[key])
                let act = analysis.records[keyPath: kp]
                let e = (exp ?? 0) < 0.05 ? nil : exp
                let a = (act ?? 0) < 0.05 ? nil : act
                switch (e, a) {
                case (nil, nil):
                    break
                case let (e?, a?):
                    #expect(abs(a - e) <= tol, "\(stem) records.\(key): \(a) vs \(e)")
                default:
                    let es = e.map { "\($0)" } ?? "none"
                    let as_ = a.map { "\($0)" } ?? "none"
                    Issue.record("\(stem) records.\(key): expected \(es), got \(as_)")
                }
            }
        }

        if let expTurns = json["turns"] as? [[String: Any]], !expTurns.isEmpty {
            // P1 engine produces no turns; goldens with turns belong to phase 2.
            print("GoldenTests: \(stem) has \(expTurns.count) golden turns — "
                  + "not asserted until the phase-2 turn engine lands.")
        }

        if let expSummary = json["summary"] as? [String: Any] {
            if let v = num(expSummary["foilTimeS"]) {
                #expect(abs(analysis.summary.foilTimeS - v) <= max(0.02 * abs(v), 2),
                        "\(stem) summary.foilTimeS: \(analysis.summary.foilTimeS) vs \(v)")
            }
            if let v = num(expSummary["foilPct"]) {
                #expect(abs(analysis.summary.foilPct - v) <= 2.0,
                        "\(stem) summary.foilPct: \(analysis.summary.foilPct) vs \(v)")
            }
            if let v = num(expSummary["flightCount"]) {
                #expect(analysis.summary.flightCount == Int(v),
                        "\(stem) summary.flightCount: \(analysis.summary.flightCount) vs \(Int(v))")
            }
            if let v = num(expSummary["longestFlightS"]) {
                #expect(abs(analysis.summary.longestFlightS - v) <= 2.0,
                        "\(stem) summary.longestFlightS")
            }
            if let v = num(expSummary["longestFlightM"]) {
                #expect(abs(analysis.summary.longestFlightM - v) <= max(0.02 * abs(v), 5),
                        "\(stem) summary.longestFlightM")
            }
            if let v = num(expSummary["distanceKm"]) {
                #expect(abs(analysis.summary.distanceKm - v) <= max(0.02 * abs(v), 0.05),
                        "\(stem) summary.distanceKm")
            }
        }
    }

    /// Numeric JSON value (NSNull / non-numbers → nil).
    private func num(_ any: Any?) -> Double? {
        guard let n = any as? NSNumber, !(any is NSNull) else { return nil }
        return n.doubleValue
    }

    // MARK: - Schema shape

    /// The encoded SessionAnalysis must match the golden schema of docs/testing.md
    /// verbatim: exact top-level keys, `wind` explicit null, `takeoffPumps` explicit
    /// null per flight, `startTs`/`endTs` spelling, windows provenance shape.
    @Test func encodedAnalysisMatchesGoldenSchema() throws {
        var raw = RawTrack()
        let epoch = Date(timeIntervalSince1970: 1_700_000_000)
        for t in stride(from: 0.0, through: 120, by: 1) {
            var s = RecordSample(t: t, timestamp: epoch.addingTimeInterval(t))
            s.speedMps = (20 <= t && t <= 60) ? 6.0 : 1.0
            raw.samples.append(s)
        }
        raw.capabilities.hasSpeed = true
        raw.capabilities.sampleRateHz = 1
        let analysis = SessionSummarizer.analyze(raw)
        #expect(analysis.engineVersion == "0.1.0")
        #expect(analysis.flights.count == 1)

        let data = try JSONEncoder().encode(analysis)
        let obj = try #require(try JSONSerialization.jsonObject(with: data) as? [String: Any])
        #expect(Set(obj.keys) == ["engineVersion", "config", "capabilities", "flights",
                                  "turns", "records", "wind", "takeoffs", "summary"])
        #expect(obj["wind"] is NSNull)                       // explicit null, not omitted
        #expect((obj["turns"] as? [Any])?.isEmpty == true)
        #expect((obj["takeoffs"] as? [Any])?.isEmpty == true)

        let flights = try #require(obj["flights"] as? [[String: Any]])
        #expect(Set(flights[0].keys) == ["startTs", "endTs", "distM", "maxKn", "takeoffPumps"])
        #expect(flights[0]["takeoffPumps"] is NSNull)

        let caps = try #require(obj["capabilities"] as? [String: Any])
        #expect(Set(caps.keys) == ["hasDoppler", "hasDevFields", "hasWatchLaps",
                                   "hasAccel", "hasHR", "sampleRateHz"])

        let records = try #require(obj["records"] as? [String: Any])
        #expect(records.keys.contains("best2sKn"))
        let windows = try #require(records["windows"] as? [String: Any])
        let w2 = try #require(windows["best2s"] as? [String: Any])
        #expect(Set(w2.keys) == ["startTs", "durS"])

        let summary = try #require(obj["summary"] as? [String: Any])
        #expect(Set(summary.keys) == ["foilTimeS", "foilPct", "flightCount",
                                      "longestFlightS", "longestFlightM", "distanceKm"])

        // Round-trip: the model decodes its own encoding losslessly — except
        // `records.totalDistanceM`, which is deliberately not part of the golden
        // records object (the golden carries km in `summary`).
        let decoded = try JSONDecoder().decode(SessionAnalysis.self, from: data)
        var expected = analysis
        expected.records.totalDistanceM = 0
        #expect(decoded == expected)
    }
}
