import Foundation
import Testing
@testable import WingFoilKit

/// Cross-implementation golden tests (docs/testing.md): for every
/// `fixtures/goldens/<stem>.expected.json` written by the lab, run the full Swift
/// pipeline on the matching recording — FIT, or since engine 0.9.0 GPX — and assert
/// within tolerances — counts exact,
/// speeds ± 0.05 kn (alpha ± 0.1), timestamps ± 1 s, angles ± 1°, percentages ± 0.5,
/// foil time ± 2 %.
///
/// The lab (`lab/src/wingfoil_lab/*`) is the authoritative reference; Swift re-derives
/// everything from the same original FIT and must land on the same verdicts — not just
/// the same totals, but the same *per-turn* type and outcome, the same flight-end
/// ownership, and the same takeoff stroke counts.
///
/// Goldens are read leniently (JSONSerialization), so extra/experimental keys from the
/// lab never break decoding; only contracted quantities are asserted.
@Suite struct GoldenTests {

    @Test func goldensMatchWhenPresent() throws {
        let dir = testFixturesDir.appendingPathComponent("goldens")
        let goldens = ((try? FileManager.default.contentsOfDirectory(
            at: dir, includingPropertiesForKeys: nil)) ?? [])
            .filter { $0.lastPathComponent.hasSuffix(".expected.json") }
            .sorted { $0.lastPathComponent < $1.lastPathComponent }
        guard !goldens.isEmpty else {
            print("GoldenTests: fixtures/goldens contains no *.expected.json yet "
                  + "(generated by the lab workstream) — zero assertions, passing.")
            return
        }
        for golden in goldens {
            try check(golden: golden)
        }
    }

    private func check(golden url: URL) throws {
        let stem = String(url.lastPathComponent.dropLast(".expected.json".count))
        guard let fitURL = findFixtureTrack(stem: stem) else {
            let where_ = "fixtures/sessions or fixtures/synthetic"
            Issue.record("golden \(stem): no \(stem).fit or \(stem).gpx under \(where_)")
            return
        }
        guard let json = try JSONSerialization.jsonObject(with: Data(contentsOf: url))
                as? [String: Any] else {
            Issue.record("golden \(stem): top level is not a JSON object")
            return
        }

        // Run with the parameters the golden was generated with (config echo).
        var filter = FilterConfig()
        var flight = FlightConfig()
        var recCfg = RecordsConfig()
        var turnCfg = TurnConfig()
        var windCfg = WindConfig()
        var pumpCfg = PumpConfig()
        var takeoffCfg = TakeoffConfig()
        var hrCfg = HrConfig()
        var ratesCfg = RatesConfig()
        if let cfg = json["config"] as? [String: Any] {
            if let v = num(cfg["foilEntrySpeed"]) { flight.foilEntrySpeedKmh = v }
            if let v = num(cfg["foilExitSpeed"]) { flight.foilExitSpeedKmh = v }
            if let v = num(cfg["entryHold"]) { flight.entryHoldS = v }
            if let v = num(cfg["exitHold"]) { flight.exitHoldS = v }
            if let v = num(cfg["minFlightDuration"]) { flight.minFlightDurationS = v }
            if let v = num(cfg["maxAccel1Hz"]) { filter.maxAccelMps2 = v }
            if let v = num(cfg["gapMinS"]) { filter.gapMinS = v }
            if let v = num(cfg["gapFactor"]) { filter.gapFactor = v }
            if let v = num(cfg["alphaProximity"]) { recCfg.alphaProximityM = v }
            if let v = num(cfg["alphaMaxDistance"]) { recCfg.alphaMaxDistanceM = v }
            if let v = num(cfg["turnMinAngle"]) { turnCfg.minAngleDeg = v }
            if let v = num(cfg["turnMaxDuration"]) { turnCfg.maxDurationS = v }
            if let v = num(cfg["turnPeakRate"]) { turnCfg.peakRateDegS = v }
            if let v = num(cfg["turnMinArc"]) { turnCfg.minArcM = v }
            if let v = num(cfg["turnMinRadius"]) { turnCfg.minRadiusM = v }
            if let v = num(cfg["turnBaroDrop"]) { turnCfg.baroDropM = v }
            if let v = num(cfg["windMinConfidence"]) { windCfg.minConfidence = v }
            if let v = num(cfg["windFullMargin"]) { windCfg.fullMargin = v }
            if let v = num(cfg["windTurnPriorWeight"]) { windCfg.turnPriorWeight = v }
            // The rider's declared habit is a parameter like any other: run the golden with
            // the one it was written under, or the 180° prior would be asked a different
            // question than the lab asked (docs/algorithms.md "Default turn type").
            if let v = cfg["windDefaultTurnType"] as? String,
               let type = DefaultTurnType(rawValue: v) { windCfg.defaultTurnType = type }
            if let v = num(cfg["pumpStrokeAmp"]) { pumpCfg.strokeAmpG = v }
            if let v = num(cfg["pumpMinStrokes"]) { pumpCfg.minStrokes = Int(v) }
            if let v = num(cfg["pumpBurstPeakG"]) { pumpCfg.burstPeakG = v }
            if let v = num(cfg["pumpMinSpeedKmh"]) { pumpCfg.minSpeedKmh = v }
            if let v = num(cfg["takeoffAttemptWindow"]) { takeoffCfg.attemptWindowS = v }
            if let v = num(cfg["takeoffMinPreWindow"]) { takeoffCfg.minPreWindowS = v }
            if let v = num(cfg["hrCostPeakWindow"]) { hrCfg.peakWindowS = v }
            if let v = num(cfg["hrBaselineWindow"]) { hrCfg.baselineWindowS = v }
            if let v = num(cfg["hrMinCoverage"]) { hrCfg.minCoverageShare = v }
            if let v = num(cfg["hrFlatlineMax"]) { hrCfg.flatlineMaxS = v }
            if let v = num(cfg["hrMinBpm"]) { hrCfg.minBpm = v }
            if let v = num(cfg["hrMaxBpm"]) { hrCfg.maxBpm = v }
            if let v = num(cfg["hrLag"]) { hrCfg.lagS = v }
            if let v = num(cfg["hrRecoveryWindow"]) { hrCfg.recoveryWindowS = v }
            if let v = num(cfg["hrMinRise"]) { hrCfg.minRiseBpm = v }
            if let v = num(cfg["hrBinMinutes"]) { hrCfg.binMinutes = v }
            if let v = num(cfg["hrMaxSampleGap"]) { hrCfg.maxSampleGapS = v }
            if let v = num(cfg["windowRateMin"]) { ratesCfg.windowRateMin = v }
        }
        // The same door `make_goldens.py` uses: FIT or GPX, decided by the file itself.
        let raw = try TrackParser.parse(url: fitURL)
        let analysis = SessionSummarizer.analyze(raw, filterConfig: filter,
                                                 flightConfig: flight, recordsConfig: recCfg,
                                                 turnConfig: turnCfg, windConfig: windCfg,
                                                 pumpConfig: pumpCfg, takeoffConfig: takeoffCfg,
                                                 hrConfig: hrCfg, ratesConfig: ratesCfg)

        checkCapabilities(stem, json, analysis, raw)
        checkFlights(stem, json, analysis)
        checkRecords(stem, json, analysis)
        checkWind(stem, json, analysis)
        checkTurns(stem, json, analysis)
        checkFlightEnds(stem, json, analysis)
        checkTakeoffs(stem, json, analysis)
        checkPumpEpisodes(stem, json, analysis)
        checkHr(stem, json, analysis)
        checkSummary(stem, json, analysis)
    }

    // MARK: - Phase 1 (capabilities, flights, records)

    private func checkCapabilities(_ stem: String, _ json: [String: Any],
                                   _ analysis: SessionAnalysis, _ raw: RawTrack) {
        guard let expCaps = json["capabilities"] as? [String: Any] else { return }
        let caps = AnalysisCapabilities(raw.capabilities)
        let flags: [(String, Bool)] = [
            ("hasDoppler", caps.hasDoppler), ("hasDevFields", caps.hasDevFields),
            ("hasWatchLaps", caps.hasWatchLaps), ("hasAccel", caps.hasAccel),
            ("hasHR", caps.hasHR),
        ]
        for (key, actual) in flags {
            guard let expected = expCaps[key] as? Bool else { continue }
            #expect(actual == expected, "\(stem) capabilities.\(key): \(actual) vs \(expected)")
        }
        if let v = num(expCaps["sampleRateHz"]) {
            #expect(abs(caps.sampleRateHz - v) <= 0.01,
                    "\(stem) capabilities.sampleRateHz: \(caps.sampleRateHz) vs \(v)")
        }
    }

    private func checkFlights(_ stem: String, _ json: [String: Any],
                              _ analysis: SessionAnalysis) {
        guard let expFlights = json["flights"] as? [[String: Any]] else { return }
        #expect(analysis.flights.count == expFlights.count,
                "\(stem): flight count \(analysis.flights.count) != \(expFlights.count)")
        for (i, pair) in zip(expFlights, analysis.flights).enumerated() {
            let (exp, act) = pair
            if let v = num(exp["startTs"]) {
                #expect(abs(act.startTs - v) <= 1.0, "\(stem) flights[\(i)].startTs")
            }
            if let v = num(exp["endTs"]) {
                #expect(abs(act.endTs - v) <= 1.0, "\(stem) flights[\(i)].endTs")
            }
            if let v = num(exp["maxKn"]) {
                #expect(abs(act.maxKn - v) <= 0.05, "\(stem) flights[\(i)].maxKn")
            }
            if let v = num(exp["distM"]) {
                #expect(abs(act.distM - v) <= max(0.02 * abs(v), 5), "\(stem) flights[\(i)].distM")
            }
            // Stroke counts are exact or both absent — a source without accel reports nil.
            #expect(int(exp["takeoffPumps"]) == act.takeoffPumps,
                    "\(stem) flights[\(i)].takeoffPumps: \(describe(act.takeoffPumps)) vs \(describe(int(exp["takeoffPumps"])))")
        }
    }

    private func checkRecords(_ stem: String, _ json: [String: Any],
                              _ analysis: SessionAnalysis) {
        guard let expRecords = json["records"] as? [String: Any] else { return }
        let keys: [(String, Double, KeyPath<GP3SRecords, Double?>)] = [
            ("best2sKn", 0.05, \.best2sKn), ("best10sKn", 0.05, \.best10sKn),
            ("best5x10sKn", 0.05, \.best5x10sKn), ("best100mKn", 0.05, \.best100mKn),
            ("best250mKn", 0.05, \.best250mKn), ("best500mKn", 0.05, \.best500mKn),
            ("bestNmKn", 0.05, \.bestNmKn), ("bestHourKn", 0.05, \.bestHourKn),
            ("alpha500Kn", 0.10, \.alpha500Kn),
        ]
        for (key, tol, kp) in keys where expRecords.keys.contains(key) {
            // Contract (docs/testing.md): a non-qualifying record serializes as 0.0
            // in goldens and as nil in the Swift model — the two are equivalent.
            let exp = num(expRecords[key])
            let act = analysis.records[keyPath: kp]
            let e = (exp ?? 0) < 0.05 ? nil : exp
            let a = (act ?? 0) < 0.05 ? nil : act
            switch (e, a) {
            case (nil, nil):
                break
            case let (e?, a?):
                #expect(abs(a - e) <= tol, "\(stem) records.\(key): \(a) vs \(e)")
            default:
                let es = e.map { "\($0)" } ?? "none"
                let as_ = a.map { "\($0)" } ?? "none"
                Issue.record("\(stem) records.\(key): expected \(es), got \(as_)")
            }
        }
    }

    // MARK: - Phase 2 (wind, turns, flight ends)

    private func checkWind(_ stem: String, _ json: [String: Any], _ analysis: SessionAnalysis) {
        guard json.keys.contains("wind") else { return }
        guard let expWind = json["wind"] as? [String: Any] else {
            #expect(analysis.wind == nil,
                    "\(stem) wind: golden has no axis, Swift estimated \(describe(analysis.wind?.dirDeg))")
            return
        }
        guard let wind = analysis.wind else {
            Issue.record("\(stem) wind: golden has an axis, Swift produced none")
            return
        }
        if let v = num(expWind["dirDeg"]) {
            #expect(abs(angleDelta(wind.dirDeg, v)) <= 1.0,
                    "\(stem) wind.dirDeg: \(wind.dirDeg) vs \(v)")
        }
        if let v = num(expWind["axisDeg"]) {
            let d = abs(angleDelta(wind.axisDeg * 2, v * 2)) / 2   // the axis is mod 180
            #expect(d <= 1.0, "\(stem) wind.axisDeg: \(wind.axisDeg) vs \(v)")
        }
        if let v = num(expWind["confidence"]) {
            #expect(abs(wind.confidence - v) <= 0.01,
                    "\(stem) wind.confidence: \(wind.confidence) vs \(v)")
        }
        if let v = num(expWind["axisConfidence"]) {
            #expect(abs(wind.axisConfidence - v) <= 0.01, "\(stem) wind.axisConfidence")
        }
        if let v = num(expWind["ambiguityMargin"]) {
            #expect(abs(wind.ambiguityMargin - v) <= 0.01, "\(stem) wind.ambiguityMargin")
        }
        if let v = num(expWind["separationDeg"]), let actual = wind.separationDeg {
            #expect(abs(actual - v) <= 1.0, "\(stem) wind.separationDeg: \(actual) vs \(v)")
        }
        if let v = expWind["usable"] as? Bool {
            #expect(wind.usable == v, "\(stem) wind.usable: \(wind.usable) vs \(v)")
        }
        // The default-turn-type prior's evidence trail. `turnTypeDirDeg` is checked through
        // its presence too: "the prior did not run" and "it ran and tied" are different
        // facts, and only the null tells them apart.
        if let v = num(expWind["turnTypeMargin"]) {
            #expect(abs(wind.turnTypeMargin - v) <= 0.01, "\(stem) wind.turnTypeMargin")
        }
        if let v = num(expWind["turnTypeVotes"]) {
            #expect(wind.turnTypeVotes == Int(v), "\(stem) wind.turnTypeVotes")
        }
        if let v = expWind["priorFlipped"] as? Bool {
            #expect(wind.priorFlipped == v, "\(stem) wind.priorFlipped")
        }
        if expWind.keys.contains("turnTypeDirDeg") {
            if let v = num(expWind["turnTypeDirDeg"]), let actual = wind.turnTypeDirDeg {
                #expect(abs(angleDelta(actual, v)) <= 1.0, "\(stem) wind.turnTypeDirDeg")
            } else {
                #expect(expWind["turnTypeDirDeg"] is NSNull && wind.turnTypeDirDeg == nil,
                        "\(stem) wind.turnTypeDirDeg: \(describe(wind.turnTypeDirDeg))")
            }
        }
        if let v = num(expWind["source"] as? NSNumber) { _ = v }
        if let v = expWind["source"] as? String {
            #expect(wind.source == v, "\(stem) wind.source")
        }
    }

    private func checkTurns(_ stem: String, _ json: [String: Any], _ analysis: SessionAnalysis) {
        guard let expTurns = json["turns"] as? [[String: Any]] else { return }
        #expect(analysis.turns.count == expTurns.count,
                "\(stem): turn count \(analysis.turns.count) != \(expTurns.count)")
        for (i, pair) in zip(expTurns, analysis.turns).enumerated() {
            let (exp, act) = pair
            if let v = exp["type"] as? String {
                #expect(act.type == v, "\(stem) turns[\(i)].type: \(act.type) vs \(v)")
            }
            if let v = exp["outcome"] as? String {
                #expect(act.outcome == v, "\(stem) turns[\(i)].outcome: \(act.outcome) vs \(v)")
            }
            if let v = exp["side"] as? String {
                #expect(act.side == v, "\(stem) turns[\(i)].side")
            }
            if let v = exp["counted"] as? Bool { #expect(act.counted == v, "\(stem) turns[\(i)].counted") }
            if let v = exp["success"] as? Bool { #expect(act.success == v, "\(stem) turns[\(i)].success") }
            if let v = exp["borderline"] as? Bool {
                #expect(act.borderline == v, "\(stem) turns[\(i)].borderline")
            }
            if let v = num(exp["ts"]) {
                #expect(abs(act.ts - v) <= 1.0, "\(stem) turns[\(i)].ts: \(act.ts) vs \(v)")
            }
            if let v = num(exp["endTs"]) { #expect(abs(act.endTs - v) <= 1.0, "\(stem) turns[\(i)].endTs") }
            if let v = num(exp["minTs"]) {
                #expect(abs(act.minTs - v) <= 1.0, "\(stem) turns[\(i)].minTs: \(act.minTs) vs \(v)")
            }
            if let v = num(exp["entryKn"]) {
                #expect(abs(act.entryKn - v) <= 0.05,
                        "\(stem) turns[\(i)].entryKn: \(act.entryKn) vs \(v)")
            }
            if let v = num(exp["minKn"]) {
                #expect(abs(act.minKn - v) <= 0.05, "\(stem) turns[\(i)].minKn: \(act.minKn) vs \(v)")
            }
            if let v = num(exp["exitKn"]) {
                #expect(abs(act.exitKn - v) <= 0.05,
                        "\(stem) turns[\(i)].exitKn: \(act.exitKn) vs \(v)")
            }
            if let v = num(exp["netDeg"]) { #expect(abs(act.netDeg - v) <= 1.0, "\(stem) turns[\(i)].netDeg") }
            // Signed, so a sign flip is a failure rather than a rounding difference.
            if let v = num(exp["peakRateDegS"]) {
                #expect(abs(act.peakRateDegS - v) <= 1.0,
                        "\(stem) turns[\(i)].peakRateDegS: \(act.peakRateDegS) vs \(v)")
            }
            // TWA is null exactly when the session has no usable wind axis — the presence
            // of the key has to agree, not only the number under it.
            if exp.keys.contains("twaInDeg") {
                if let v = num(exp["twaInDeg"]), let a = act.twaInDeg {
                    #expect(abs(angleDelta(a, v)) <= 1.0,
                            "\(stem) turns[\(i)].twaInDeg: \(a) vs \(v)")
                } else {
                    #expect(exp["twaInDeg"] is NSNull && act.twaInDeg == nil,
                            "\(stem) turns[\(i)].twaInDeg: \(describe(act.twaInDeg))")
                }
            }
            if exp.keys.contains("twaOutDeg") {
                if let v = num(exp["twaOutDeg"]), let a = act.twaOutDeg {
                    #expect(abs(angleDelta(a, v)) <= 1.0,
                            "\(stem) turns[\(i)].twaOutDeg: \(a) vs \(v)")
                } else {
                    #expect(exp["twaOutDeg"] is NSNull && act.twaOutDeg == nil,
                            "\(stem) turns[\(i)].twaOutDeg: \(describe(act.twaOutDeg))")
                }
            }
            if let v = num(exp["stoppedS"]) {
                #expect(abs(act.stoppedS - v) <= 1.0, "\(stem) turns[\(i)].stoppedS")
            }
            if let v = num(exp["outcomeWindowS"]) {
                #expect(abs(act.outcomeWindowS - v) <= 1.0, "\(stem) turns[\(i)].outcomeWindowS")
            }
        }
    }

    private func checkFlightEnds(_ stem: String, _ json: [String: Any],
                                 _ analysis: SessionAnalysis) {
        guard let expEnds = json["flightEnds"] as? [[String: Any]] else { return }
        #expect(analysis.flightEnds.count == expEnds.count,
                "\(stem): flight-end count \(analysis.flightEnds.count) != \(expEnds.count)")
        for (i, pair) in zip(expEnds, analysis.flightEnds).enumerated() {
            let (exp, act) = pair
            if let v = exp["outcome"] as? String {
                #expect(act.outcome == v, "\(stem) flightEnds[\(i)].outcome: \(act.outcome) vs \(v)")
            }
            if let v = exp["truncated"] as? Bool {
                #expect(act.truncated == v, "\(stem) flightEnds[\(i)].truncated")
            }
            #expect(int(exp["ownedByTurn"]) == act.ownedByTurn,
                    "\(stem) flightEnds[\(i)].ownedByTurn: \(describe(act.ownedByTurn)) vs \(describe(int(exp["ownedByTurn"])))")
            if let v = num(exp["ts"]) { #expect(abs(act.ts - v) <= 1.0, "\(stem) flightEnds[\(i)].ts") }
            if let v = num(exp["stoppedS"]) {
                #expect(abs(act.stoppedS - v) <= 1.0, "\(stem) flightEnds[\(i)].stoppedS")
            }
        }
    }

    // MARK: - Phase 3 (takeoffs)

    private func checkTakeoffs(_ stem: String, _ json: [String: Any],
                               _ analysis: SessionAnalysis) {
        guard let expTakeoffs = json["takeoffs"] as? [[String: Any]] else { return }
        #expect(analysis.takeoffs.count == expTakeoffs.count,
                "\(stem): takeoff count \(analysis.takeoffs.count) != \(expTakeoffs.count)")
        for (i, pair) in zip(expTakeoffs, analysis.takeoffs).enumerated() {
            let (exp, act) = pair
            #expect(int(exp["pumps"]) == act.pumps,
                    "\(stem) takeoffs[\(i)].pumps: \(describe(act.pumps)) vs \(describe(int(exp["pumps"])))")
            if let v = exp["truncated"] as? Bool {
                #expect(act.truncated == v, "\(stem) takeoffs[\(i)].truncated")
            }
            if let v = exp["free"] as? Bool { #expect(act.free == v, "\(stem) takeoffs[\(i)].free") }
            if let v = num(exp["startTs"]) {
                #expect(abs(act.startTs - v) <= 1.0, "\(stem) takeoffs[\(i)].startTs")
            }
            if let v = num(exp["timeToFoilS"]) {
                #expect(abs(act.timeToFoilS - v) <= 1.0,
                        "\(stem) takeoffs[\(i)].timeToFoilS: \(act.timeToFoilS) vs \(v)")
            }
            if let v = num(exp["speedRiseS"]) {
                #expect(abs(act.speedRiseS - v) <= 1.0, "\(stem) takeoffs[\(i)].speedRiseS")
            }
            #expect(int(exp["inFlightStrokes"]) == act.inFlightStrokes,
                    "\(stem) takeoffs[\(i)].inFlightStrokes")
        }
    }

    /// The `pumpEpisodes` block (engine 0.3.0): every classified pumping effort, in
    /// detection order. Counts and verdicts are **exact** — strokes, bursts, outcome and
    /// both cross-reference indices — because they are the classifier's decisions, not
    /// measurements; the instants get the table's ± 1 s timestamp tolerance.
    ///
    /// The list order is itself part of the contract: iOS positions a failed-attempt marker
    /// by looking `startTs` up in the track, so two implementations that agreed on the set
    /// but not the sequence would still put markers in different places.
    private func checkPumpEpisodes(_ stem: String, _ json: [String: Any],
                                   _ analysis: SessionAnalysis) {
        guard let expEpisodes = json["pumpEpisodes"] as? [[String: Any]] else { return }
        #expect(analysis.pumpEpisodes.count == expEpisodes.count,
                "\(stem): pumpEpisode count \(analysis.pumpEpisodes.count) != \(expEpisodes.count)")
        for (i, pair) in zip(expEpisodes, analysis.pumpEpisodes).enumerated() {
            let (exp, act) = pair
            if let v = exp["outcome"] as? String {
                #expect(act.outcome.rawValue == v,
                        "\(stem) pumpEpisodes[\(i)].outcome: \(act.outcome.rawValue) vs \(v)")
            }
            if let v = int(exp["strokes"]) {
                #expect(act.strokes == v, "\(stem) pumpEpisodes[\(i)].strokes: \(act.strokes) vs \(v)")
            }
            if let v = int(exp["bursts"]) {
                #expect(act.bursts == v, "\(stem) pumpEpisodes[\(i)].bursts: \(act.bursts) vs \(v)")
            }
            #expect(int(exp["flightIndex"]) == act.flightIndex,
                    "\(stem) pumpEpisodes[\(i)].flightIndex: \(describe(act.flightIndex)) vs \(describe(int(exp["flightIndex"])))")
            #expect(int(exp["turnIndex"]) == act.turnIndex,
                    "\(stem) pumpEpisodes[\(i)].turnIndex: \(describe(act.turnIndex)) vs \(describe(int(exp["turnIndex"])))")
            if let v = num(exp["startTs"]) {
                #expect(abs(act.startTs - v) <= 1.0,
                        "\(stem) pumpEpisodes[\(i)].startTs: \(act.startTs) vs \(v)")
            }
            if let v = num(exp["endTs"]) {
                #expect(abs(act.endTs - v) <= 1.0,
                        "\(stem) pumpEpisodes[\(i)].endTs: \(act.endTs) vs \(v)")
            }
            if let v = num(exp["lookaheadS"]) {
                #expect(abs(act.lookaheadS - v) <= 1.0,
                        "\(stem) pumpEpisodes[\(i)].lookaheadS: \(act.lookaheadS) vs \(v)")
            }
        }

        // The block and the tallies beside it are two readings of the same classification;
        // if they ever disagree, one of them is lying about the session.
        let failed = analysis.pumpEpisodes.filter { $0.outcome == .failed }.count
        #expect(failed == analysis.summary.takeoff.failedAttempts,
                "\(stem): \(failed) failed episodes vs failedAttempts \(analysis.summary.takeoff.failedAttempts)")
        let succeeded = analysis.pumpEpisodes.filter { $0.outcome == .success }.count
        #expect(succeeded == (json["pumpEpisodes"] as? [[String: Any]] ?? [])
                    .filter { ($0["outcome"] as? String) == "success" }.count,
                "\(stem): success-episode count")
        #expect(analysis.pumpEpisodes.map(\.startTs) == analysis.pumpEpisodes
                    .map(\.startTs).sorted(), "\(stem): pumpEpisodes must be in time order")
    }

    // MARK: - Phase 3.5 (HR cost)

    /// Tolerances (docs/testing.md "Tolerances"): counts and verdicts **exact**
    /// (`hasHR`, every `n valid / n total`, `approximate`, `strokes`, `recoveryCensored`);
    /// timestamps and durations ± 1 s (anchors, peak lag, half-recovery, bin edges);
    /// percentages ± 0.5 (`successPct`, `usablePct`).
    ///
    /// The table has no row for heart rates, so bpm and the coverage *shares* are held to
    /// the **speeds** row's ± 0.05 — and that is generous rather than tight: nothing between
    /// the FIT and these numbers resamples, filters or integrates, so both implementations
    /// read the same stored bpm values off the same sample times. A drift beyond a rounding
    /// artefact would mean the two ports disagree about which samples are *usable*, which is
    /// the whole contract of this block.
    private func checkHr(_ stem: String, _ json: [String: Any], _ analysis: SessionAnalysis) {
        guard let expHr = json["hr"] as? [String: Any] else { return }
        guard let hr = analysis.hr else {
            Issue.record("\(stem) hr: golden carries the block, Swift produced none")
            return
        }
        if let v = expHr["hasHR"] as? Bool {
            #expect(hr.hasHR == v, "\(stem) hr.hasHR: \(hr.hasHR) vs \(v)")
        }
        checkHrEvents(stem, "takeoffEvents", expHr["takeoffEvents"], hr.takeoffEvents)
        checkHrEvents(stem, "swimEvents", expHr["swimEvents"], hr.swimEvents)
        checkHrBins(stem, expHr["bins"], hr.bins)
        checkHrSummary(stem, expHr["summary"], hr.summary)
    }

    private func checkHrEvents(_ stem: String, _ name: String, _ expected: Any?,
                               _ actual: [HrEvent]) {
        guard let exp = expected as? [[String: Any]] else { return }
        #expect(actual.count == exp.count,
                "\(stem) hr.\(name): count \(actual.count) != \(exp.count)")
        for (i, pair) in zip(exp, actual).enumerated() {
            let (e, a) = pair
            let at = "\(stem) hr.\(name)[\(i)]"
            if let v = e["kind"] as? String { #expect(a.kind.rawValue == v, "\(at).kind") }
            if let v = int(e["index"]) { #expect(a.index == v, "\(at).index: \(a.index) vs \(v)") }
            if let v = num(e["ts"]) { #expect(abs(a.t - v) <= 1.0, "\(at).ts: \(a.t) vs \(v)") }
            if let v = e["approximate"] as? Bool {
                #expect(a.approximate == v, "\(at).approximate: \(a.approximate) vs \(v)")
            }
            if let v = e["recoveryCensored"] as? Bool {
                #expect(a.recoveryCensored == v, "\(at).recoveryCensored")
            }
            // A missing stroke count and a zero are different facts; so are a missing bpm
            // and a zero bpm. Both must be nil on the same side of the port.
            #expect(int(e["strokes"]) == a.strokes,
                    "\(at).strokes: \(describe(a.strokes)) vs \(describe(int(e["strokes"])))")
            expectOptional(stem, "hr.\(name)[\(i)].baselineBpm", num(e["baselineBpm"]),
                           a.baselineBpm, tolerance: 0.05)
            expectOptional(stem, "hr.\(name)[\(i)].peakBpm", num(e["peakBpm"]),
                           a.peakBpm, tolerance: 0.05)
            expectOptional(stem, "hr.\(name)[\(i)].costBpm", num(e["costBpm"]),
                           a.costBpm, tolerance: 0.05)
            expectOptional(stem, "hr.\(name)[\(i)].peakLagS", num(e["peakLagS"]),
                           a.peakLagS, tolerance: 1.0)
            expectOptional(stem, "hr.\(name)[\(i)].recoveryHalfS", num(e["recoveryHalfS"]),
                           a.recoveryHalfS, tolerance: 1.0)
            if let v = num(e["baselineCoverage"]) {
                #expect(abs(a.baselineCoverage - v) <= 0.05,
                        "\(at).baselineCoverage: \(a.baselineCoverage) vs \(v)")
            }
            if let v = num(e["peakCoverage"]) {
                #expect(abs(a.peakCoverage - v) <= 0.05,
                        "\(at).peakCoverage: \(a.peakCoverage) vs \(v)")
            }
        }
    }

    private func checkHrBins(_ stem: String, _ expected: Any?, _ actual: [FatigueBin]) {
        guard let exp = expected as? [[String: Any]] else { return }
        #expect(actual.count == exp.count,
                "\(stem) hr.bins: count \(actual.count) != \(exp.count)")
        for (i, pair) in zip(exp, actual).enumerated() {
            let (e, a) = pair
            let at = "\(stem) hr.bins[\(i)]"
            let counts: [(String, Int)] = [("attempts", a.attempts), ("successes", a.successes),
                                           ("failed", a.failed),
                                           ("costValid", a.costCoverage.valid),
                                           ("costTotal", a.costCoverage.total)]
            for (key, value) in counts {
                guard let v = int(e[key]) else { continue }
                #expect(value == v, "\(at).\(key): \(value) vs \(v)")
            }
            if let v = num(e["startTs"]) { #expect(abs(a.startT - v) <= 1.0, "\(at).startTs") }
            if let v = num(e["endTs"]) { #expect(abs(a.endT - v) <= 1.0, "\(at).endTs") }
            expectOptional(stem, "hr.bins[\(i)].successPct", num(e["successPct"]),
                           a.successPct, tolerance: 0.5)
            expectOptional(stem, "hr.bins[\(i)].avgCostBpm", num(e["avgCostBpm"]),
                           a.avgCostBpm, tolerance: 0.05)
            expectOptional(stem, "hr.bins[\(i)].medianCostBpm", num(e["medianCostBpm"]),
                           a.medianCostBpm, tolerance: 0.05)
            expectOptional(stem, "hr.bins[\(i)].avgBaselineBpm", num(e["avgBaselineBpm"]),
                           a.avgBaselineBpm, tolerance: 0.05)
            expectOptional(stem, "hr.bins[\(i)].avgPumps", num(e["avgPumps"]),
                           a.avgPumps, tolerance: 0.05)
            expectOptional(stem, "hr.bins[\(i)].meanBpm", num(e["meanBpm"]),
                           a.meanBpm, tolerance: 0.05)
        }
    }

    private func checkHrSummary(_ stem: String, _ expected: Any?, _ s: HrSummary) {
        guard let e = expected as? [String: Any] else { return }
        let counts: [(String, Int)] = [
            ("takeoffCostValid", s.takeoffCostCoverage.valid),
            ("takeoffCostTotal", s.takeoffCostCoverage.total),
            ("approximateTakeoffs", s.approximateTakeoffs),
            ("bpmPerStrokeValid", s.bpmPerStrokeCoverage.valid),
            ("bpmPerStrokeTotal", s.bpmPerStrokeCoverage.total),
            ("takeoffRecoveryValid", s.takeoffRecoveryCoverage.valid),
            ("takeoffRecoveryTotal", s.takeoffRecoveryCoverage.total),
            ("swimRecoveryValid", s.swimRecoveryCoverage.valid),
            ("swimRecoveryTotal", s.swimRecoveryCoverage.total),
            ("swimCostValid", s.swimCostCoverage.valid),
            ("swimCostTotal", s.swimCostCoverage.total),
        ]
        for (key, value) in counts {
            guard let v = int(e[key]) else { continue }
            #expect(value == v, "\(stem) hr.summary.\(key): \(value) vs \(v)")
        }
        let bpm: [(String, Double?, Double?)] = [
            ("avgTakeoffCostBpm", num(e["avgTakeoffCostBpm"]), s.avgTakeoffCostBpm),
            ("medianTakeoffCostBpm", num(e["medianTakeoffCostBpm"]), s.medianTakeoffCostBpm),
            ("avgSwimCostBpm", num(e["avgSwimCostBpm"]), s.avgSwimCostBpm),
        ]
        for (key, expected, actual) in bpm {
            expectOptional(stem, "hr.summary.\(key)", expected, actual, tolerance: 0.05)
        }
        expectOptional(stem, "hr.summary.usablePct", num(e["usablePct"]), s.usablePct,
                       tolerance: 0.5)
        expectOptional(stem, "hr.summary.medianPeakLagS", num(e["medianPeakLagS"]),
                       s.medianPeakLagS, tolerance: 1.0)
        expectOptional(stem, "hr.summary.medianTakeoffRecoveryS",
                       num(e["medianTakeoffRecoveryS"]), s.medianTakeoffRecoveryS,
                       tolerance: 1.0)
        expectOptional(stem, "hr.summary.medianSwimRecoveryS", num(e["medianSwimRecoveryS"]),
                       s.medianSwimRecoveryS, tolerance: 1.0)
        // bpm per stroke is a ratio of two already-checked quantities, so it is held one
        // decimal tighter than the bpm it divides.
        expectOptional(stem, "hr.summary.bpmPerStroke", num(e["bpmPerStroke"]),
                       s.bpmPerStroke, tolerance: 0.005)
        expectOptional(stem, "hr.summary.medianBpmPerStroke", num(e["medianBpmPerStroke"]),
                       s.medianBpmPerStroke, tolerance: 0.005)

        guard let pc = e["pumpCruise"] as? [String: Any] else { return }
        let p = s.pumpCruise
        for (key, value) in [("pumpingSpans", p.pumpingSpans),
                             ("cruisingSpans", p.cruisingSpans)] {
            guard let v = int(pc[key]) else { continue }
            #expect(value == v, "\(stem) hr.summary.pumpCruise.\(key): \(value) vs \(v)")
        }
        expectOptional(stem, "hr.summary.pumpCruise.pumpingBpm", num(pc["pumpingBpm"]),
                       p.pumpingBpm, tolerance: 0.05)
        expectOptional(stem, "hr.summary.pumpCruise.cruisingBpm", num(pc["cruisingBpm"]),
                       p.cruisingBpm, tolerance: 0.05)
        expectOptional(stem, "hr.summary.pumpCruise.deltaBpm", num(pc["deltaBpm"]),
                       p.deltaBpm, tolerance: 0.05)
        let seconds: [(String, Double?, Double)] = [
            ("pumpingCoveredS", num(pc["pumpingCoveredS"]), p.pumpingCoveredS),
            ("pumpingSpanS", num(pc["pumpingSpanS"]), p.pumpingSpanS),
            ("cruisingCoveredS", num(pc["cruisingCoveredS"]), p.cruisingCoveredS),
            ("cruisingSpanS", num(pc["cruisingSpanS"]), p.cruisingSpanS),
        ]
        for (key, expected, actual) in seconds {
            guard let v = expected else { continue }
            #expect(abs(actual - v) <= 1.0,
                    "\(stem) hr.summary.pumpCruise.\(key): \(actual) vs \(v)")
        }
    }

    // MARK: - Summaries

    private func checkSummary(_ stem: String, _ json: [String: Any],
                              _ analysis: SessionAnalysis) {
        guard let expSummary = json["summary"] as? [String: Any] else { return }
        if let v = num(expSummary["foilTimeS"]) {
            #expect(abs(analysis.summary.foilTimeS - v) <= max(0.02 * abs(v), 2),
                    "\(stem) summary.foilTimeS: \(analysis.summary.foilTimeS) vs \(v)")
        }
        if let v = num(expSummary["foilPct"]) {
            #expect(abs(analysis.summary.foilPct - v) <= 2.0,
                    "\(stem) summary.foilPct: \(analysis.summary.foilPct) vs \(v)")
        }
        if let v = num(expSummary["flightCount"]) {
            #expect(analysis.summary.flightCount == Int(v), "\(stem) summary.flightCount")
        }
        if let v = num(expSummary["longestFlightS"]) {
            #expect(abs(analysis.summary.longestFlightS - v) <= 2.0, "\(stem) summary.longestFlightS")
        }
        if let v = num(expSummary["longestFlightM"]) {
            #expect(abs(analysis.summary.longestFlightM - v) <= max(0.02 * abs(v), 5),
                    "\(stem) summary.longestFlightM")
        }
        if let v = num(expSummary["distanceKm"]) {
            #expect(abs(analysis.summary.distanceKm - v) <= max(0.02 * abs(v), 0.05),
                    "\(stem) summary.distanceKm")
        }

        // Session rates (docs/algorithms.md "Session rates"). The duration is a wall clock,
        // so it is pinned tightly (± 0.1 s); the rates are per-hour numbers over it and
        // follow the ± 0.05 style of every other derived quantity.
        if let v = num(expSummary["durationS"]) {
            #expect(abs(analysis.summary.durationS - v) <= 0.1,
                    "\(stem) summary.durationS: \(analysis.summary.durationS) vs \(v)")
        }
        expectOptional(stem, "summary.avgSpeedKmh", num(expSummary["avgSpeedKmh"]),
                       analysis.summary.avgSpeedKmh, tolerance: 0.05)
        expectOptional(stem, "summary.turnsPerHour", num(expSummary["turnsPerHour"]),
                       analysis.summary.turnsPerHour, tolerance: 0.05)
        expectOptional(stem, "summary.jibesPerHour", num(expSummary["jibesPerHour"]),
                       analysis.summary.jibesPerHour, tolerance: 0.05)
        expectOptional(stem, "summary.cleanJibesPerHour", num(expSummary["cleanJibesPerHour"]),
                       analysis.summary.cleanJibesPerHour, tolerance: 0.05)
        expectOptional(stem, "summary.wetPerHour", num(expSummary["wetPerHour"]),
                       analysis.summary.wetPerHour, tolerance: 0.05)
        // The wet rate counts *every* fell-in flight end — the straight-line swims and the
        // turn-owned ones, both channels, once each. It is deliberately not the turn
        // ladder's `fellIn`, which counts a different event (a mid-turn swim that never
        // ended a flight is a fall to the turn ladder and no flight end at all).
        if analysis.summary.durationS > 0, let wet = analysis.summary.wetPerHour {
            let hours = analysis.summary.durationS / 3600
            let ends = analysis.summary.flightEnds
            #expect(ends.all.fellIn == ends.straight.fellIn + ends.inTurn.fellIn,
                    "\(stem) fell-in ends do not split into straight + inTurn")
            #expect(abs(wet - Double(ends.all.fellIn) / hours) < 1e-9,
                    "\(stem) summary.wetPerHour \(wet) is not every fell-in end over the hour")
        }
        // The 0.7.0 numerator: **dry** jibes, the ones he came out of still sailing. A jibe
        // he swam out of is one he did not make, so it may not raise the headline rate.
        if analysis.summary.durationS > 0, let jph = analysis.summary.jibesPerHour {
            let hours = analysis.summary.durationS / 3600
            let t = analysis.summary.turns
            let dry = t.jibes - t.jibeOutcomes.fellIn
            #expect(dry == t.jibeOutcomes.flewThrough + t.jibeOutcomes.touchdown,
                    "\(stem) the jibe ladder does not add up to its own total")
            #expect(abs(jph - Double(dry) / hours) < 1e-9,
                    "\(stem) summary.jibesPerHour \(jph) is not the DRY jibes over the hour")
            // …and the tally agrees with the golden's own turn rows, one event each.
            if let rows = json["turns"] as? [[String: Any]] {
                let counted = rows.filter { $0["counted"] as? Bool == true }
                let dryRows = counted.filter {
                    $0["type"] as? String == "jibe" && $0["outcome"] as? String != "fell_in"
                }
                #expect(dryRows.count == dry,
                        "\(stem) \(dryRows.count) dry jibe rows vs a numerator of \(dry)")
            }
        }

        // The 0.10.0 numerator: **clean** jibes, `turns.jibesSuccessful` over the same hour.
        // It is the strict reading of a set the dry rate already narrowed, so it can never
        // stand above JPH — a jibe he rode is a jibe he came out of.
        if analysis.summary.durationS > 0, let cph = analysis.summary.cleanJibesPerHour {
            let hours = analysis.summary.durationS / 3600
            let t = analysis.summary.turns
            #expect(abs(cph - Double(t.jibesSuccessful) / hours) < 1e-9,
                    "\(stem) summary.cleanJibesPerHour \(cph) is not jibesSuccessful over the hour")
            #expect(cph <= (analysis.summary.jibesPerHour ?? 0) + 1e-9,
                    "\(stem) CPH \(cph) stands above JPH — a clean jibe is a dry one")
        }

        expectWindowRates(stem, expSummary["windowRates"], analysis.summary.windowRates)

        if let t = expSummary["turns"] as? [String: Any] {
            let s = analysis.summary.turns
            let counts: [(String, Int)] = [
                ("tacks", s.tacks), ("tacksSuccessful", s.tacksSuccessful),
                ("jibes", s.jibes), ("jibesSuccessful", s.jibesSuccessful),
                ("unclassified", s.unclassified), ("turnsCounted", s.turnsCounted),
                ("turnsSuccessful", s.turnsSuccessful), ("rejected", s.rejected),
                ("port", s.port), ("starboard", s.starboard), ("unknownSide", s.unknownSide),
                ("longestDryStreak", s.longestDryStreak),
                ("longestFlewStreak", s.longestFlewStreak),
            ]
            for (key, actual) in counts {
                guard let v = int(t[key]) else { continue }
                #expect(actual == v, "\(stem) summary.turns.\(key): \(actual) vs \(v)")
            }
            if let v = num(t["successPct"]) {
                #expect(abs(s.successPct - v) <= 0.5, "\(stem) summary.turns.successPct")
            }
            // A strict run is a sub-run of a dry one, and neither can outnumber the turns
            // they run over — true of the goldens and of anything the engine may produce.
            #expect(s.longestFlewStreak <= s.longestDryStreak,
                    "\(stem) flew streak \(s.longestFlewStreak) > dry \(s.longestDryStreak)")
            #expect(s.longestDryStreak <= s.turnsCounted,
                    "\(stem) dry streak \(s.longestDryStreak) > counted \(s.turnsCounted)")
            expectOutcomes(stem, "outcomes", t["outcomes"], s.outcomes)
            expectOutcomes(stem, "tackOutcomes", t["tackOutcomes"], s.tackOutcomes)
            expectOutcomes(stem, "jibeOutcomes", t["jibeOutcomes"], s.jibeOutcomes)
        }

        if let e = expSummary["flightEnds"] as? [String: Any] {
            expectEnds(stem, "all", e["all"], analysis.summary.flightEnds.all)
            expectEnds(stem, "straight", e["straight"], analysis.summary.flightEnds.straight)
            expectEnds(stem, "inTurn", e["inTurn"], analysis.summary.flightEnds.inTurn)
        }

        if let sp = expSummary["outcomeSplit"] as? [String: Any] {
            let s = analysis.summary.outcomeSplit
            let counts: [(String, Int)] = [
                ("turnFalls", s.turnFalls), ("straightFalls", s.straightFalls),
                ("turnTouchdowns", s.turnTouchdowns),
                ("straightTouchdowns", s.straightTouchdowns),
                ("glideOuts", s.glideOuts), ("unknownEnds", s.unknownEnds),
            ]
            for (key, actual) in counts {
                guard let v = int(sp[key]) else { continue }
                #expect(actual == v, "\(stem) summary.outcomeSplit.\(key): \(actual) vs \(v)")
            }
        }

        if let k = expSummary["takeoff"] as? [String: Any] {
            let s = analysis.summary.takeoff
            let counts: [(String, Int)] = [
                ("takeoffAttempts", s.takeoffAttempts), ("takeoffSuccesses", s.takeoffSuccesses),
                ("failedAttempts", s.failedAttempts), ("unknownAttempts", s.unknownAttempts),
                ("recoveryEpisodes", s.recoveryEpisodes),
                ("inFlightEpisodes", s.inFlightEpisodes),
                ("runsJudged", s.runsJudged), ("runsTruncated", s.runsTruncated),
                ("freeTakeoffs", s.freeTakeoffs), ("pumpedTakeoffs", s.pumpedTakeoffs),
            ]
            for (key, actual) in counts {
                guard let v = int(k[key]) else { continue }
                #expect(actual == v, "\(stem) summary.takeoff.\(key): \(actual) vs \(v)")
            }
            #expect(int(k["totalPumpStrokes"]) == s.totalPumpStrokes,
                    "\(stem) summary.takeoff.totalPumpStrokes: \(describe(s.totalPumpStrokes)) vs \(describe(int(k["totalPumpStrokes"])))")
            #expect(int(k["inFlightPumpStrokes"]) == s.inFlightPumpStrokes,
                    "\(stem) summary.takeoff.inFlightPumpStrokes")
            expectOptional(stem, "summary.takeoff.successPct", num(k["successPct"]),
                           s.successPct, tolerance: 0.5)
            expectOptional(stem, "summary.takeoff.avgPumpsToTakeoff",
                           num(k["avgPumpsToTakeoff"]), s.avgPumpsToTakeoff, tolerance: 0.05)
            expectOptional(stem, "summary.takeoff.medianPumpsToTakeoff",
                           num(k["medianPumpsToTakeoff"]), s.medianPumpsToTakeoff, tolerance: 0.05)
            expectOptional(stem, "summary.takeoff.avgPumpsWhenPumped",
                           num(k["avgPumpsWhenPumped"]), s.avgPumpsWhenPumped, tolerance: 0.05)
            expectOptional(stem, "summary.takeoff.avgTakeoffS", num(k["avgTakeoffS"]),
                           s.avgTakeoffS, tolerance: 1.0)
            expectOptional(stem, "summary.takeoff.medianTakeoffS", num(k["medianTakeoffS"]),
                           s.medianTakeoffS, tolerance: 1.0)
        }
    }

    private func expectOutcomes(_ stem: String, _ name: String, _ expected: Any?,
                                _ actual: OutcomeCounts) {
        guard let e = expected as? [String: Any] else { return }
        let pairs: [(String, Int)] = [("flewThrough", actual.flewThrough),
                                      ("touchdown", actual.touchdown),
                                      ("fellIn", actual.fellIn),
                                      ("borderline", actual.borderline)]
        for (key, value) in pairs {
            guard let v = int(e[key]) else { continue }
            #expect(value == v, "\(stem) summary.turns.\(name).\(key): \(value) vs \(v)")
        }
    }

    private func expectEnds(_ stem: String, _ name: String, _ expected: Any?,
                            _ actual: FlightEndCounts) {
        guard let e = expected as? [String: Any] else { return }
        let pairs: [(String, Int)] = [("glideOut", actual.glideOut),
                                      ("touchdown", actual.touchdown),
                                      ("fellIn", actual.fellIn),
                                      ("unknown", actual.unknown),
                                      ("borderline", actual.borderline)]
        for (key, value) in pairs {
            guard let v = int(e[key]) else { continue }
            #expect(value == v, "\(stem) summary.flightEnds.\(name).\(key): \(value) vs \(v)")
        }
    }

    /// nil must match nil; both present must agree within `tolerance`.
    /// The rolling-window block (docs/algorithms.md "Session rates"): both peaks with the
    /// window each one names, and every point of the series, in order.
    ///
    /// Rates to ± 0.05 like the session rates; the window starts are timestamps and get the
    /// timestamp treatment (± 0.1 s, tighter than the ± 1 s a detector's instant earns —
    /// this one is arithmetic on a grid, not a judgement about a sample).
    private func expectWindowRates(_ stem: String, _ expected: Any?,
                                   _ actual: SessionWindowRates) {
        guard let w = expected as? [String: Any] else { return }
        if let v = num(w["windowMin"]) {
            #expect(abs(actual.windowMin - v) <= 1e-9,
                    "\(stem) windowRates.windowMin: \(actual.windowMin) vs \(v)")
        }
        expectOptional(stem, "windowRates.bestJph", num(w["bestJph"]),
                       actual.bestJph, tolerance: 0.05)
        expectOptional(stem, "windowRates.bestJphStartTs", num(w["bestJphStartTs"]),
                       actual.bestJphStartTs, tolerance: 0.1)
        expectOptional(stem, "windowRates.bestWph", num(w["bestWph"]),
                       actual.bestWph, tolerance: 0.05)
        expectOptional(stem, "windowRates.bestWphStartTs", num(w["bestWphStartTs"]),
                       actual.bestWphStartTs, tolerance: 0.1)

        let series = (w["series"] as? [[String: Any]]) ?? []
        #expect(series.count == actual.series.count,
                "\(stem) windowRates.series: \(actual.series.count) points vs \(series.count)")
        for (i, exp) in series.enumerated() where i < actual.series.count {
            let p = actual.series[i]
            #expect(abs(p.ts - (num(exp["ts"]) ?? -1)) <= 0.1,
                    "\(stem) windowRates.series[\(i)].ts: \(p.ts) vs \(describe(num(exp["ts"])))")
            #expect(abs(p.jph - (num(exp["jph"]) ?? -1)) <= 0.05,
                    "\(stem) windowRates.series[\(i)].jph: \(p.jph)")
            #expect(abs(p.wph - (num(exp["wph"]) ?? -1)) <= 0.05,
                    "\(stem) windowRates.series[\(i)].wph: \(p.wph)")
        }
        // The series is a sampling of the very function the peak maximizes, so a peak below
        // it would mean the search missed a window the file itself prints.
        if let best = actual.bestJph, let top = actual.series.map(\.jph).max() {
            #expect(best >= top - 1e-9, "\(stem) bestJph \(best) is under the series' \(top)")
        }
        if let best = actual.bestWph, let top = actual.series.map(\.wph).max() {
            #expect(best >= top - 1e-9, "\(stem) bestWph \(best) is under the series' \(top)")
        }
    }

    private func expectOptional(_ stem: String, _ label: String, _ expected: Double?,
                                _ actual: Double?, tolerance: Double) {
        switch (expected, actual) {
        case (nil, nil):
            break
        case let (e?, a?):
            #expect(abs(a - e) <= tolerance, "\(stem) \(label): \(a) vs \(e)")
        default:
            Issue.record("\(stem) \(label): expected \(describe(expected)), got \(describe(actual))")
        }
    }

    // MARK: - JSON helpers

    /// Numeric JSON value (NSNull / non-numbers → nil).
    private func num(_ any: Any?) -> Double? {
        guard let n = any as? NSNumber, !(any is NSNull) else { return nil }
        return n.doubleValue
    }

    /// "none" for nil, the value otherwise — keeps failure messages single literals
    /// (swift-testing's `Comment` is not built by `+`).
    private func describe<T>(_ value: T?) -> String {
        value.map { "\($0)" } ?? "none"
    }

    private func int(_ any: Any?) -> Int? {
        num(any).map { Int($0.rounded()) }
    }

    /// Smallest signed difference between two bearings, in degrees.
    private func angleDelta(_ a: Double, _ b: Double) -> Double {
        var m = (a - b + 180).truncatingRemainder(dividingBy: 360)
        if m < 0 { m += 360 }
        return m - 180
    }

    // MARK: - Schema shape

    /// The encoded SessionAnalysis must match the golden schema of docs/testing.md
    /// verbatim: exact top-level keys, `wind` explicit null, `takeoffPumps` explicit
    /// null per flight, `startTs`/`endTs` spelling, windows provenance shape.
    @Test func encodedAnalysisMatchesGoldenSchema() throws {
        var raw = RawTrack()
        let epoch = Date(timeIntervalSince1970: 1_700_000_000)
        for t in stride(from: 0.0, through: 120, by: 1) {
            var s = RecordSample(t: t, timestamp: epoch.addingTimeInterval(t))
            s.speedMps = (20 <= t && t <= 60) ? 6.0 : 1.0
            raw.samples.append(s)
        }
        raw.capabilities.hasSpeed = true
        raw.capabilities.sampleRateHz = 1
        let analysis = SessionSummarizer.analyze(raw)
        #expect(analysis.engineVersion == "0.11.0")
        #expect(analysis.flights.count == 1)

        let data = try JSONEncoder().encode(analysis)
        let obj = try #require(try JSONSerialization.jsonObject(with: data) as? [String: Any])
        #expect(Set(obj.keys) == ["engineVersion", "config", "capabilities", "flights",
                                  "turns", "flightEnds", "records", "wind", "takeoffs",
                                  "pumpEpisodes", "hr", "summary"])
        #expect(obj["wind"] is NSNull)                       // explicit null, not omitted
        #expect((obj["turns"] as? [Any])?.isEmpty == true)   // no positions ⇒ no COG ⇒ no turns

        // This synthetic carries no heart rate at all. The block is still written, with
        // `hasHR: false` — "this source had no HR" must not look like "this analysis
        // predates the HR block", and no average inside it may be a flattering zero.
        let hr = try #require(obj["hr"] as? [String: Any])
        #expect(Set(hr.keys) == ["hasHR", "takeoffEvents", "swimEvents", "bins", "summary"])
        #expect(hr["hasHR"] as? Bool == false)
        #expect((hr["takeoffEvents"] as? [Any])?.isEmpty == true)
        #expect((hr["swimEvents"] as? [Any])?.isEmpty == true)
        #expect((hr["bins"] as? [Any])?.isEmpty == true)
        let hrSummary = try #require(hr["summary"] as? [String: Any])
        #expect(hrSummary["usablePct"] is NSNull)
        #expect(hrSummary["avgTakeoffCostBpm"] is NSNull)
        #expect(int(hrSummary["takeoffCostTotal"]) == 0)
        let pumpCruise = try #require(hrSummary["pumpCruise"] as? [String: Any])
        #expect(pumpCruise["pumpingBpm"] is NSNull)
        #expect(pumpCruise["deltaBpm"] is NSNull)
        #expect(analysis.hr?.summary.hasHR == false)

        // Every flight gets a takeoff run and a flight end, even without an accel stream;
        // the stroke counts are then explicitly null rather than a flattering zero.
        let flights = try #require(obj["flights"] as? [[String: Any]])
        #expect(Set(flights[0].keys) == ["startTs", "endTs", "distM", "maxKn", "takeoffPumps"])
        #expect(flights[0]["takeoffPumps"] is NSNull)
        #expect((obj["takeoffs"] as? [Any])?.count == 1)
        #expect((obj["flightEnds"] as? [Any])?.count == 1)
        let takeoff = try #require((obj["takeoffs"] as? [[String: Any]])?.first)
        #expect(takeoff["pumps"] is NSNull)
        #expect(takeoff["success"] as? Bool == true)
        #expect(analysis.summary.takeoff.successPct == nil)  // failures invisible w/o accel
        // No wrist stream ⇒ no bursts to classify ⇒ an empty *list*, written rather than
        // omitted: "this source had no episodes" and "this analysis predates the block"
        // must not look the same, which is the whole reason the key is always encoded.
        #expect((obj["pumpEpisodes"] as? [Any])?.isEmpty == true)

        let caps = try #require(obj["capabilities"] as? [String: Any])
        #expect(Set(caps.keys) == ["hasDoppler", "hasDevFields", "hasWatchLaps",
                                   "hasAccel", "hasHR", "sampleRateHz"])

        let records = try #require(obj["records"] as? [String: Any])
        #expect(records.keys.contains("best2sKn"))
        let windows = try #require(records["windows"] as? [String: Any])
        let w2 = try #require(windows["best2s"] as? [String: Any])
        #expect(Set(w2.keys) == ["startTs", "durS"])
        // best5x10s is an ARRAY of windows, like the lab writes it; a record that was
        // never achieved has no key at all rather than a null.
        let w5 = try #require(windows["best5x10s"] as? [[String: Any]])
        #expect(w5.count == 5)
        #expect(Set(w5[0].keys) == ["startTs", "durS"])
        #expect(windows["alpha500"] == nil, "no positions ⇒ no alpha ⇒ absent key")

        let summary = try #require(obj["summary"] as? [String: Any])
        #expect(Set(summary.keys) == ["foilTimeS", "foilPct", "flightCount",
                                      "longestFlightS", "longestFlightM", "distanceKm",
                                      "durationS", "avgSpeedKmh", "turnsPerHour",
                                      "jibesPerHour", "cleanJibesPerHour",
                                      "wetPerHour", "windowRates",
                                      "turns", "flightEnds", "outcomeSplit", "takeoff"])
        // 120 s of synthetic, one flight, no turns: the duration is real and the rates are
        // real zeroes — "he did no jibes in that hour", not "unknown".
        #expect(abs((num(summary["durationS"]) ?? 0) - 120) <= 0.1)
        #expect(num(summary["turnsPerHour"]) == 0)
        #expect(num(summary["jibesPerHour"]) == 0)
        #expect(num(summary["cleanJibesPerHour"]) == 0)
        #expect(analysis.summary.avgSpeedKmh != nil)

        // The rolling block is written whole, like the HR block: this session is two minutes
        // long, far shorter than the 15-minute window, so it gets **one** point over the
        // span it actually lasted rather than a partial window scaled up to the hour.
        let windowRates = try #require(summary["windowRates"] as? [String: Any])
        #expect(Set(windowRates.keys) == ["windowMin", "bestJph", "bestJphStartTs",
                                          "bestWph", "bestWphStartTs", "series"])
        #expect(num(windowRates["windowMin"]) == 15)
        #expect(num(windowRates["bestJph"]) == 0)
        #expect((windowRates["series"] as? [Any])?.count == 1)

        // Round-trip: the model decodes its own encoding losslessly — except
        // `records.totalDistanceM`, which is deliberately not part of the golden
        // records object (the golden carries km in `summary`).
        let decoded = try JSONDecoder().decode(SessionAnalysis.self, from: data)
        var expected = analysis
        expected.records.totalDistanceM = 0
        #expect(decoded == expected)
    }

    /// The rate block's arithmetic and its one guard (docs/algorithms.md "Session rates"),
    /// mirroring `lab/tests/test_goldens.py`. Two hours, 40 km, 60 counted turns of which
    /// 44 dry jibes and 9 swims: 30 turns/h, 22 jibes/h, 4.5 swims/h, 20 km/h.
    @Test func sessionRatesDivideByTheElapsedHour() {
        let r = SessionRates(durationS: 7200, distanceM: 40_000,
                             turnsCounted: 60, dryJibes: 44, fellIn: 9, cleanJibes: 22)
        #expect(r.durationS == 7200)
        #expect(abs((r.avgSpeedKmh ?? 0) - 20) < 1e-9)
        #expect(abs((r.turnsPerHour ?? 0) - 30) < 1e-9)
        #expect(abs((r.jibesPerHour ?? 0) - 22) < 1e-9)
        // CPH is the strict reading of the same set: 22 clean in 2 h is 11/h.
        #expect(abs((r.cleanJibesPerHour ?? 0) - 11) < 1e-9)
        #expect(abs((r.wetPerHour ?? 0) - 4.5) < 1e-9)

        // No elapsed time ⇒ no hour to divide by. Every rate is nil, never a 0 that would
        // read as "he did nothing in an hour on the water".
        for empty in [SessionRates(durationS: 0, distanceM: 1234,
                                   turnsCounted: 7, dryJibes: 5, fellIn: 2, cleanJibes: 3),
                      SessionRates(durationS: -12, distanceM: 1234,
                                   turnsCounted: 7, dryJibes: 5, fellIn: 2, cleanJibes: 3)] {
            #expect(empty.durationS == 0)
            #expect(empty.avgSpeedKmh == nil)
            #expect(empty.turnsPerHour == nil)
            #expect(empty.jibesPerHour == nil)
            #expect(empty.cleanJibesPerHour == nil)
            #expect(empty.wetPerHour == nil)
        }
    }

    /// The rolling window's honesty rule, mirroring `lab/tests/test_goldens.py`: a session
    /// shorter than one window is rated over the span it actually lasted, and the same
    /// three-minute burst inside an hour is rated over the hour's busiest quarter.
    @Test func windowPeakNeverScalesAPartialWindowUp() {
        let short = SessionWindowRates(dryJibeTs: [10, 60, 120], wetTs: [30],
                                       startT: 0, durationS: 180)
        #expect(abs((short.bestJph ?? 0) - 60) < 1e-9)     // 3 jibes in the 3 min he sailed
        #expect(short.bestJphStartTs == 0)
        #expect(abs((short.bestWph ?? 0) - 20) < 1e-9)
        #expect(short.series.count == 1)
        #expect(short.series.first?.ts == 0)

        // The same burst inside an hour is three jibes in the busiest 15 minutes — 12 an
        // hour, never the 60 the burst alone would have claimed.
        let long = SessionWindowRates(dryJibeTs: [10, 60, 120], wetTs: [30],
                                      startT: 0, durationS: 3600)
        #expect(abs((long.bestJph ?? 0) - 12) < 1e-9)
        #expect(long.bestJphStartTs == 0)
        #expect(abs((long.bestWph ?? 0) - 4) < 1e-9)
    }

    /// The peak is the true sliding maximum, so it opens on the event that starts the
    /// burst: three jibes spanning 899 s fit in exactly one quarter-hour window, and no
    /// window on the 60 s grid can hold all three.
    @Test func windowPeakFindsTheBurstAtItsOwnStart() {
        let w = SessionWindowRates(dryJibeTs: [2000, 2450, 2899], wetTs: [],
                                   startT: 0, durationS: 3600)
        #expect(w.bestJphStartTs == 2000)
        #expect(abs((w.bestJph ?? 0) - 12) < 1e-9)
        #expect(abs((w.series.map(\.jph).max() ?? 0) - 8) < 1e-9)
        #expect((w.bestJph ?? 0) > (w.series.map(\.jph).max() ?? 0))
        // Nothing wet happened: a measured 0.0, at the first window there was.
        #expect(w.bestWph == 0 && w.bestWphStartTs == 0)
    }

    /// One point a minute, the first at the session's own start, the last a full window
    /// before its end — so every value in the series is a rate over 15 real minutes.
    @Test func windowSeriesWalksA60SecondGridOfFullWindows() {
        let w = SessionWindowRates(dryJibeTs: [100, 200], wetTs: [], startT: 0,
                                   durationS: 3600)
        let starts: [Double] = (0..<46).map { k in Double(k) * 60 }
        #expect(w.series.map(\.ts) == starts)              // 3600 - 900 = 2700, the last one
        let jphs: Set<Double> = Set(w.series.map(\.jph))
        #expect(jphs.isSubset(of: [0, 4, 8]))              // 0, 1 or 2 jibes / 0.25 h

        // A session that starts at a non-zero clock keeps the grid anchored to its own start.
        let off = SessionWindowRates(dryJibeTs: [], wetTs: [], startT: 1234.5, durationS: 1800)
        let offStarts: [Double] = (0..<16).map { k in 1234.5 + Double(k) * 60 }
        #expect(off.series.map(\.ts) == offStarts)

        // No duration, no window: null peaks and an empty series, never a flattering 0.0.
        let empty = SessionWindowRates(dryJibeTs: [1], wetTs: [2], startT: 0, durationS: 0)
        #expect(empty.bestJph == nil && empty.bestWph == nil)
        #expect(empty.bestJphStartTs == nil && empty.series.isEmpty)
        #expect(empty.windowMin == 15)
    }

    /// A stored `analysis.json` written by engine 0.2.0 has no `pumpEpisodes` key at all.
    /// It must still decode — the archive reads the document before it compares versions,
    /// and a decode failure there would look like a corrupt archive rather than a stale one.
    /// The row is stale by `engineVersion` and `reanalyzeStale()` re-derives it; what must
    /// not happen is a crash on the way to finding that out.
    @Test func analysisWithoutPumpEpisodesStillDecodes() throws {
        var raw = RawTrack()
        let epoch = Date(timeIntervalSince1970: 1_700_000_000)
        for t in stride(from: 0.0, through: 120, by: 1) {
            var s = RecordSample(t: t, timestamp: epoch.addingTimeInterval(t))
            s.speedMps = (20 <= t && t <= 60) ? 6.0 : 1.0
            raw.samples.append(s)
        }
        raw.capabilities.hasSpeed = true
        let analysis = SessionSummarizer.analyze(raw)
        var obj = try #require(try JSONSerialization.jsonObject(
            with: JSONEncoder().encode(analysis)) as? [String: Any])
        obj["pumpEpisodes"] = nil                       // the 0.2.0 document, key and all
        obj["engineVersion"] = "0.2.0"
        let old = try JSONSerialization.data(withJSONObject: obj)

        let decoded = try JSONDecoder().decode(SessionAnalysis.self, from: old)
        #expect(decoded.pumpEpisodes.isEmpty)
        #expect(decoded.engineVersion != AnalysisEngine.version)   // ⇒ stale ⇒ re-derived
    }

    /// The other direction of the same contract: a golden the *lab* wrote must decode
    /// straight into `SessionAnalysis` through Codable — not only through the lenient
    /// `JSONSerialization` path the comparisons above use — and re-encode to the same
    /// `records.windows` shape. `best5x10s` is the interesting key: the lab stores the
    /// array of every disjoint 10 s window it kept.
    @Test func labGoldensDecodeThroughCodable() throws {
        let dir = testFixturesDir.appendingPathComponent("goldens")
        let goldens = ((try? FileManager.default.contentsOfDirectory(
            at: dir, includingPropertiesForKeys: nil)) ?? [])
            .filter { $0.lastPathComponent.hasSuffix(".expected.json") }
            .sorted { $0.lastPathComponent < $1.lastPathComponent }
        guard !goldens.isEmpty else { return }

        var sawArray = false
        for url in goldens {
            let stem = String(url.lastPathComponent.dropLast(".expected.json".count))
            let data = try Data(contentsOf: url)
            let raw = try #require(try JSONSerialization.jsonObject(with: data)
                                   as? [String: Any])
            let expWindows = (raw["records"] as? [String: Any])?["windows"] as? [String: Any]

            let analysis: SessionAnalysis
            do {
                analysis = try JSONDecoder().decode(SessionAnalysis.self, from: data)
            } catch {
                Issue.record("golden \(stem): SessionAnalysis is not Codable against it: \(error)")
                continue
            }

            // Every window key the lab wrote survives the round trip, with its shape.
            if let expList = expWindows?["best5x10s"] as? [[String: Any]] {
                sawArray = true
                let actual = try #require(analysis.records.windows.best5x10s,
                                          "\(stem): best5x10s did not decode")
                #expect(actual.count == expList.count, "\(stem): best5x10s window count")
                for (i, exp) in expList.enumerated() where i < actual.count {
                    #expect(abs(actual[i].startTs - (num(exp["startTs"]) ?? -1)) < 1e-9,
                            "\(stem): best5x10s[\(i)].startTs")
                    #expect(abs(actual[i].durS - (num(exp["durS"]) ?? -1)) < 1e-9,
                            "\(stem): best5x10s[\(i)].durS")
                }
            }
            #expect((analysis.records.windows["best2s"] != nil)
                    == (expWindows?["best2s"] != nil), "\(stem): best2s presence")
            #expect((analysis.records.windows.alpha500 != nil)
                    == (expWindows?["alpha500"] != nil), "\(stem): alpha500 presence")

            // Re-encoding reproduces the golden's windows object key for key: single
            // windows stay objects, best5x10s stays an array, absent stays absent.
            let reencoded = try JSONEncoder().encode(analysis)
            let back = try #require(try JSONSerialization.jsonObject(with: reencoded)
                                    as? [String: Any])
            let outWindows = try #require((back["records"] as? [String: Any])?["windows"]
                                          as? [String: Any])
            #expect(Set(outWindows.keys) == Set(expWindows.map { Array($0.keys) } ?? []),
                    "\(stem): records.windows keys \(Set(outWindows.keys))")
            #expect(outWindows["best5x10s"] is [Any] || expWindows?["best5x10s"] == nil,
                    "\(stem): best5x10s must re-encode as an array")
        }
        #expect(sawArray, "no golden carried a records.windows.best5x10s array")
    }
}
