import Foundation
import Testing
@testable import WingFoilKit

/// The period card's artwork: many outlines, one scale — and the same one the analyzer uses.
///
/// A single outline is placed against itself, which is what a library row wants: every
/// thumbnail reads as the same consistent shape. A dozen laid on one another want the
/// opposite. Normalized one session at a time — which is what the phone did before
/// `TrackThumbnail` carried its `bounds` — a half-hour paddle is drawn exactly as large as a
/// three-hour reach, and the picture says nothing about either.
///
/// `fixtures/periods/outlines.expected.json` is the cross-platform half: polylines in metres,
/// a box in layout points, and every placed vertex, generated by
/// `web/tools/make_presentation_goldens.py`. `verify_presentation.py` §5e holds
/// `stackPlacer` in web/js/sharecard.js to the same file, so a card composed on the phone and
/// a card composed in the browser place the same outlines in the same places.
@Suite struct TrackStackTests {

    // MARK: - The fixture

    struct Fixture: Decodable {
        struct Rule: Decodable {
            let inset: Double
            let flatAxisM: Double
            let degenerateScale: Double
        }
        struct Case: Decodable {
            let name: String
            let box: Box
            let tracks: [[[Double]]]
            let scale: Double
            let centreX: Double
            let centreY: Double
            let placed: [[[Double]]]
        }
        struct Box: Decodable {
            let x: Double
            let y: Double
            let w: Double
            let h: Double
        }
        let rule: Rule
        let cases: [Case]
    }

    static func loadFixture() throws -> Fixture {
        let url = testFixturesDir
            .appendingPathComponent("periods")
            .appendingPathComponent("outlines.expected.json")
        return try JSONDecoder().decode(Fixture.self, from: try Data(contentsOf: url))
    }

    /// The fixture rounds to six places; so does the comparison. Everything here is one
    /// multiply and one add away from the input, so agreement is exact well past this — the
    /// rounding is against the last bit of a `Double` printed through JSON, not against a
    /// difference in the rule.
    static func round6(_ v: Double) -> Double { (v * 1_000_000).rounded() / 1_000_000 }

    static func extent(_ track: [[Double]]) -> TrackStack.Extent {
        let xs = track.map { $0[0] }, ys = track.map { $0[1] }
        return TrackStack.Extent(minX: xs.min()!, minY: ys.min()!,
                                 maxX: xs.max()!, maxY: ys.max()!)
    }

    // MARK: - The contract

    /// The constants both platforms fit by, before any of them is applied.
    @Test func theRulesAreTheAnalyzersRules() throws {
        let rule = try Self.loadFixture().rule
        #expect(rule.flatAxisM == TrackStack.flatAxisM)
        #expect(rule.degenerateScale == TrackStack.degenerateScale)
        // The inset is the card's, not the stack's: the same margin the session card reserves
        // for a mark on its outermost vertex, so a stack comes out the size a single outline
        // would have (`ShareCardMapper.inset`, `TRACK_INSET` in web/js/sharecard.js).
        #expect(rule.inset == ShareCardStats.trackInset)
    }

    @Test func everyVertexLandsWhereTheAnalyzerPutsIt() throws {
        let fixture = try Self.loadFixture()
        #expect(!fixture.cases.isEmpty)
        for want in fixture.cases {
            let box = TrackStack.Box(x: want.box.x, y: want.box.y,
                                     w: want.box.w, h: want.box.h)
            let placement = try #require(
                TrackStack.placement(of: want.tracks.map(Self.extent), in: box,
                                     inset: fixture.rule.inset),
                "\(want.name): no placement")
            #expect(Self.round6(placement.scale) == Self.round6(want.scale),
                    "\(want.name): scale")
            #expect(Self.round6(placement.centreX) == Self.round6(want.centreX),
                    "\(want.name): centreX")
            #expect(Self.round6(placement.centreY) == Self.round6(want.centreY),
                    "\(want.name): centreY")
            for (track, wanted) in zip(want.tracks, want.placed) {
                let got = track.map { point -> [Double] in
                    let p = placement.place(x: point[0], y: point[1])
                    return [Self.round6(p.x), Self.round6(p.y)]
                }
                #expect(got == wanted.map { $0.map(Self.round6) }, "\(want.name): placement")
            }
        }
    }

    // MARK: - The point of it

    /// **Two tracks of different extents come out at the same metres per point.**
    ///
    /// The follow-up the period card's author wrote down, as one assertion: the long reach
    /// and the short paddle are drawn by one scale, so the short one is visibly shorter. Under
    /// the old per-session normalization both filled the box, and a week of twelve afternoons
    /// looked like twelve identical rides.
    @Test func twoTracksOfDifferentExtentsShareOneMetresScale() throws {
        let box = TrackStack.Box(x: 16, y: 64, w: 328, h: 250)
        let long = TrackStack.Extent(minX: -450, minY: -50, maxX: 450, maxY: 50)
        let short = TrackStack.Extent(minX: 100, minY: -10, maxX: 200, maxY: 10)
        let placement = TrackStack.placement(of: [long, short], in: box, inset: 7.2)
        let together = try #require(placement)

        // One scale, by construction — and it is the one the *union* implies, which is the
        // long track's, because the long track is what binds the fit.
        let alone = TrackStack.placement(of: [long], in: box, inset: 7.2)!
        #expect(together.scale == alone.scale)

        // Drawn: the short track occupies a ninth of the width, because it is a ninth as long.
        func width(_ e: TrackStack.Extent) -> Double {
            together.place(x: e.maxX, y: 0).x - together.place(x: e.minX, y: 0).x
        }
        #expect(abs(width(short) / width(long) - 1.0 / 9) < 1e-9)
        // …and the long one fills the inset box exactly.
        #expect(abs(width(long) - (box.w - 7.2 * 2)) < 1e-9)
    }

    /// A stack of one is the same fit as the single track it holds — the period card of a
    /// month with one afternoon in it is that afternoon, at the size the session card draws it.
    @Test func aStackOfOneIsJustThatTrack() {
        let box = TrackStack.Box(x: 0, y: 0, w: 100, h: 100)
        let one = TrackStack.Extent(minX: -10, minY: -20, maxX: 30, maxY: 20)
        let placement = TrackStack.placement(of: [one], in: box, inset: 0)!
        #expect(placement.scale == 100.0 / 40)
        // Centred on the box: the union's centre lands on the box's centre, always.
        let centre = placement.place(x: 10, y: 0)
        #expect(centre.x == 50)
        #expect(centre.y == 50)
    }

    /// A perfectly straight leg has no extent on one axis, so that axis imposes no limit and
    /// the other takes the fit alone. The alternative is a division by a rounding error.
    @Test func aFlatAxisImposesNoLimit() {
        // 300 points across 200 metres: the horizontal axis alone decides, and the answer is
        // deliberately not 1, so a degenerate fallback could not pass this by accident.
        let box = TrackStack.Box(x: 0, y: 0, w: 300, h: 50)
        let flat = TrackStack.Extent(minX: -100, minY: 5, maxX: 100, maxY: 5)
        #expect(TrackStack.placement(of: [flat], in: box, inset: 0)?.scale == 1.5)
        // Under a centimetre is flat too: a track that drifted 5 mm sideways is a straight
        // leg, and fitting a 50-point box to it would put its ends 3 km apart.
        let nearlyFlat = TrackStack.Extent(minX: -100, minY: 0, maxX: 100, maxY: 0.005)
        #expect(TrackStack.placement(of: [nearlyFlat], in: box, inset: 0)?.scale == 1.5)
    }

    /// A rider who never moved: no extent on either axis, and an answer rather than a crash.
    @Test func aStackWithNoExtentGetsTheDegenerateScale() {
        let still = TrackStack.Extent(minX: 7, minY: -3, maxX: 7, maxY: -3)
        let placement = TrackStack.placement(of: [still],
                                             in: TrackStack.Box(x: 0, y: 0, w: 80, h: 60),
                                             inset: 4)!
        #expect(placement.scale == TrackStack.degenerateScale)
        let p = placement.place(x: 7, y: -3)
        #expect(p.x == 40)
        #expect(p.y == 30)
    }

    @Test func anEmptyStackHasNoPlacement() {
        #expect(TrackStack.placement(of: [], in: TrackStack.Box(x: 0, y: 0, w: 10, h: 10),
                                     inset: 0) == nil)
        #expect(TrackStack.union([]) == nil)
    }

    /// The opacity a stack is drawn at falls with the count, so a dozen read as one shape —
    /// the twin of the same expression in `drawTrackStack`, bounded at both ends.
    @Test func theStackFadesWithItsCount() {
        #expect(TrackStack.opacity(count: 1) == 0.6)
        #expect(TrackStack.opacity(count: 4) == 0.6)
        #expect(abs(TrackStack.opacity(count: 6) - 0.4) < 1e-12)
        #expect(TrackStack.opacity(count: 12) == 0.22)
        // A count of nothing is not a division by nothing.
        #expect(TrackStack.opacity(count: 0) == 0.6)
    }

    // MARK: - The thumbnail's own half

    /// The extent survives the normalization, and comes back out exactly.
    ///
    /// This is what makes the shared scale possible at all: `Point` is a session against
    /// itself, and `metres(x:y:)` is the inverse that puts it back on the water.
    @Test func aThumbnailGivesItsMetresBack() throws {
        let coordinates: [(lat: Double, lon: Double, flying: Bool)] = [
            (45.8760, 10.8710, true), (45.8772, 10.8734, true),
            (45.8751, 10.8759, false), (45.8766, 10.8701, true),
        ]
        let projection = try #require(
            TrackThumbnail.Projection(coordinates.map { (lat: $0.lat, lon: $0.lon) }))
        let thumbnail = TrackThumbnail(points: TrackThumbnail.outline(coordinates: coordinates),
                                       bounds: projection.bounds, speed: [], maxKn: 0)

        let bounds = try #require(thumbnail.bounds)
        // The extent is the projection's own, in metres about the track's centroid: this
        // track is about 380 m east–west and 230 m north–south.
        #expect(abs((bounds.maxX - bounds.minX) - 450) < 15)
        #expect(abs((bounds.maxY - bounds.minY) - 232) < 15)

        for (point, source) in zip(thumbnail.points, coordinates) {
            let back = try #require(thumbnail.coordinate(x: point.x, y: point.y))
            // Under a centimetre: the round trip is the projection's own arithmetic run
            // backwards, so what is left is `Double`'s last bits and nothing else.
            #expect(abs(back.lat - source.lat) < 1e-7)
            #expect(abs(back.lon - source.lon) < 1e-7)
        }
    }

    /// A thumbnail that does not carry its extent says so, rather than guessing at one. That
    /// is the whole reason `currentVersion` moved: a v2 blob decodes without `bounds`, and a
    /// period card would have quietly left it out of the stack for ever.
    @Test func aThumbnailWithoutBoundsCannotBeStacked() {
        let bare = TrackThumbnail(points: [.init(x: 0, y: 0, flying: true),
                                           .init(x: 1, y: 1, flying: true)],
                                  speed: [], maxKn: 0)
        #expect(bare.bounds == nil)
        #expect(bare.metres(x: 0.5, y: 0.5) == nil)
        #expect(bare.coordinate(x: 0.5, y: 0.5) == nil)
        #expect(bare.stackExtent == nil)
        // v2 is stale, so the cache rebuilds it rather than stacking a boundless outline.
        #expect(TrackThumbnail(version: 2, points: bare.points, speed: [], maxKn: 0).isStale)
        #expect(!bare.isStale)
    }
}
