// Generated by design/generate_tokens.py from design/tokens.json — do not edit.
// Edit the tokens, re-run the generator, and commit all four files together;
// design/check_tokens.py --check fails the build on drift.
//
// Contract: docs/presentation.md — the meanings. This file carries only values.

import SwiftUI

/// The presentation palette, generated from `design/tokens.json`.
///
/// iOS consumes the *semantic* half of each token (`Color.green`, `Color.teal`, …)
/// so the marks keep following the system's light/dark and accessibility palettes;
/// the web consumes the hex half. `Hex` is carried here too, not for drawing, but
/// so a test can hold the two halves of a token against each other.
public enum DesignTokens {

    /// The verdict ladder. Nothing outside a maneuver outcome may borrow it.
    public enum Outcome {
        /// flew through — carried the maneuver on the foil
        public static let flew = Color.green
        /// touchdown — lost it briefly
        public static let touchdown = Color.orange
        /// fell in — swam
        public static let fellIn = Color.red
        /// bear-away / round-up — a non-verdict, deliberately outside the ladder
        public static let courseChange = Color.gray
    }

    /// Effort and water: deliberately outside the ladder — nothing here is a verdict.
    public enum Effort {
        /// pump-burst spans on the track
        public static let pumping = Color.indigo
        /// takeoff attempts that flew
        public static let takeoff = Color.blue
        /// the barometer saw the wrist go under
        public static let splash = Color.cyan
        /// the one effort-layer event with an outcome, so it alone borrows the ladder's red
        public static let failedTakeoff = Color.red
        /// the selected record window: the glow on the track and the shading in the chart (the `effort` layer's ink, hex = systemOrange on dark)
        public static let window = Color.orange
    }

    /// Track tint by phase.
    public enum Phase {
        /// track tinted on foil (hex = systemTeal on dark, what SwiftUI .teal renders as)
        public static let flying = Color.teal
        /// track tinted off foil (hex = the secondary label over a dark surface, what SwiftUI .secondary renders as)
        public static let offFoil = Color.secondary
    }

    /// Course-of-travel chevrons: ink plus opacity, never a hue of its own.
    public enum Direction {
        /// chevron ink — subordinate to every marker, so ink plus opacity, no hue
        public static let ink = Color.primary
    }

    /// Opacities the chevrons are drawn at, per phase (web uses its own).
    public enum Opacity {
        public static let directionWeb: Double = 0.42
        public static let directionFlying: Double = 0.62
        public static let directionOffFoil: Double = 0.38
        public static let directionNeutral: Double = 0.22
    }

    /// SF Symbols. Shape is a channel of its own — see the contract.
    public enum Glyph {
        /// filled up-arrow — this cost something
        public static let takeoffPumped = "arrow.up.circle.fill"
        /// hollow up-arrow — the wind did it
        public static let takeoffFree = "arrow.up.circle"
        /// hollow red u-turn — went at it and came back down
        public static let takeoffFailed = "arrow.uturn.down.circle"
        /// drop glyph — submersion evidence
        public static let splash = "drop.fill"
    }

    /// The hex half of every colour token — what the web renders. Not used
    /// for drawing on iOS; it exists so the two halves stay in one file.
    public enum Hex {
        public static let outcomeFlew = "#0ca30c"
        public static let outcomeTouchdown = "#fab219"
        public static let outcomeFellIn = "#d03b3b"
        public static let outcomeCourseChange = "#7a7a72"
        public static let effortPumping = "#8f7ce8"
        public static let effortTakeoff = "#3987e5"
        public static let effortSplash = "#3fc4d8"
        public static let effortFailedTakeoff = "#d03b3b"
        public static let effortWindow = "#ff9f0a"
        public static let phaseFlying = "#40c8e0"
        public static let phaseOffFoil = "#97979d"
        public static let directionInk = "#c3c2b7"
    }

    /// The record picker: canonical order, display labels, and the window every
    /// session opens on.
    public enum RecordWindows {
        public static let defaultID = "best2s"
        public static let catalogue: [DesignTokenEntry] = [
            DesignTokenEntry(id: "best2s", label: "2 s"),
            DesignTokenEntry(id: "best10s", label: "10 s"),
            DesignTokenEntry(id: "best5x10s", label: "5 × 10 s"),
            DesignTokenEntry(id: "best100m", label: "100 m"),
            DesignTokenEntry(id: "best250m", label: "250 m"),
            DesignTokenEntry(id: "best500m", label: "500 m"),
            DesignTokenEntry(id: "bestNm", label: "1 NM"),
            DesignTokenEntry(id: "alpha500", label: "Alpha 500"),
        ]
        public static let order: [String] = catalogue.map(\.id)
    }

    /// The legend's layer catalogue: ids, chip text, and which layers a rider who
    /// has never touched a chip sees.
    public enum Layers {
        public static let catalogue: [DesignTokenEntry] = [
            DesignTokenEntry(id: "flying", label: "flying"),
            DesignTokenEntry(id: "offFoil", label: "off foil"),
            DesignTokenEntry(id: "effort", label: "best effort"),
            DesignTokenEntry(id: "pumping", label: "pumping"),
            DesignTokenEntry(id: "flewThrough", label: "flew through"),
            DesignTokenEntry(id: "touchdown", label: "touchdown"),
            DesignTokenEntry(id: "fellIn", label: "fell in"),
            DesignTokenEntry(id: "courseChange", label: "course change"),
            DesignTokenEntry(id: "takeoff", label: "takeoff"),
            DesignTokenEntry(id: "splash", label: "splash"),
            DesignTokenEntry(id: "direction", label: "direction"),
        ]
        public static let order: [String] = catalogue.map(\.id)
        public static let visibleByDefault: [String] = [
            "flying",
            "offFoil",
            "effort",
            "pumping",
            "flewThrough",
            "touchdown",
            "fellIn",
            "courseChange",
            "takeoff",
            "splash",
            "direction",
        ]
    }
}

/// One catalogue row: the id the code switches on, and the words the rider reads.
public struct DesignTokenEntry: Sendable, Equatable, Identifiable {
    public let id: String
    public let label: String

    public init(id: String, label: String) {
        self.id = id
        self.label = label
    }
}
