// Generated by design/generate_tokens.py from design/tokens.json — do not edit.
// Edit the tokens, re-run the generator, and commit all four files together;
// design/check_tokens.py --check fails the build on drift.
//
// Contract: docs/presentation.md — the meanings. This file carries only values.

import SwiftUI

/// The presentation palette, generated from `design/tokens.json`.
///
/// iOS consumes the *semantic* half of each token (`Color.green`, `Color.teal`, …)
/// so the marks keep following the system's light/dark and accessibility palettes;
/// the web consumes the hex half. `Hex` is carried here too, not for drawing, but
/// so a test can hold the two halves of a token against each other.
public enum DesignTokens {

    /// The verdict ladder. Nothing outside a maneuver outcome may borrow it.
    public enum Outcome {
        /// flew through — carried the maneuver on the foil
        public static let flew = Color.green
        /// touchdown — lost it briefly
        public static let touchdown = Color.orange
        /// fell in — swam
        public static let fellIn = Color.red
        /// bear-away / round-up — a non-verdict, deliberately outside the ladder
        public static let courseChange = Color.gray
    }

    /// Effort and water: deliberately outside the ladder — nothing here is a verdict.
    public enum Effort {
        /// pump-burst spans on the track
        public static let pumping = Color.indigo
        /// takeoff attempts that flew
        public static let takeoff = Color.blue
        /// the barometer saw the wrist go under
        public static let splash = Color.cyan
        /// the one effort-layer event with an outcome, so it alone borrows the ladder's red
        public static let failedTakeoff = Color.red
        /// the selected record window: the glow on the track and the shading in the chart (the `effort` layer's ink, hex = systemOrange on dark)
        public static let window = Color.orange
    }

    /// Track tint by phase.
    public enum Phase {
        /// track tinted on foil (hex = systemTeal on dark, what SwiftUI .teal renders as)
        public static let flying = Color.teal
        /// track tinted off foil (hex = the secondary label over a dark surface, what SwiftUI .secondary renders as)
        public static let offFoil = Color.secondary
    }

    /// Course-of-travel chevrons: ink plus opacity, never a hue of its own.
    public enum Direction {
        /// chevron ink — subordinate to every marker, so ink plus opacity, no hue
        public static let ink = Color.primary
    }

    /// Entry tack. A side is not a verdict, so it may borrow neither the ladder nor the
    /// effort inks: one hue at two intensities, and the quieter half is dashed.
    public enum Side {
        /// port ENTRY tack — a side, never a verdict, so deliberately outside the ladder
        public static let port = Color.brown
        /// starboard ENTRY tack — the same hue at a second lightness, plus a dashed stroke
        public static let starboard = Color.brown.opacity(0.55)
    }

    /// The strict verdict's own ink. Clean is what a jibe *cost*; the ladder's green is
    /// how it *ended*, and the two disagree on purpose — so the clean mark carries a
    /// green of its own and never the ladder's.
    public enum Clean {
        /// clean jibe — the strict verdict's own ink: a green deliberately NOT the ladder's flew-through green, because clean is what a jibe cost and flew through is how it ended
        public static let jibe = Color.mint
    }

    /// The speed ramp: five stops, cold to hot, for a line coloured by how fast it was
    /// going. Authored RGB on both platforms rather than system colours, because a ramp
    /// has to be ordered and the semantic palette is not (see `rampNote`).
    public enum Speed {
        /// ramp stop 1 of 5 — a standstill. The cold end: an indigo blue, the one hue nothing else on the turn page uses
        public static let stopped = Color(red: 0.3098, green: 0.3882, blue: 0.8471)
        /// ramp stop 2 of 5 — well under the speed he came in at
        public static let slow = Color(red: 0.2392, green: 0.6039, blue: 0.851)
        /// ramp stop 3 of 5 — THE ANCHOR: the speed the turn was entered at, and deliberately the same value as phase.flying, so 'he held his entry speed' is drawn in the ink the app already means flying with
        public static let entry = Color(red: 0.251, green: 0.7843, blue: 0.8784)
        /// ramp stop 4 of 5 — above the entry speed. Past the anchor the ramp leaves the cool half, because a rider who accelerated through a turn should be able to see it at a glance
        public static let fast = Color(red: 0.8784, green: 0.4784, blue: 0.8157)
        /// ramp stop 5 of 5 — the hot end, 1.3x the entry speed and up. A magenta, not the amber or the red: those are outcome words, and a fast vertex is not a verdict
        public static let fastest = Color(red: 1, green: 0.2392, blue: 0.6196)
        /// The five stops in order, cold to hot — what a renderer
        /// interpolates between. Index 2 is the entry-speed anchor.
        public static let ramp: [Color] = [stopped, slow, entry, fast, fastest]
        /// The same five stops as components, for interpolation:
        /// a `Color` cannot be taken apart again once built.
        public static let rampRGB: [DesignTokenRGB] = [
            DesignTokenRGB(red: 0.3098, green: 0.3882, blue: 0.8471),
            DesignTokenRGB(red: 0.2392, green: 0.6039, blue: 0.851),
            DesignTokenRGB(red: 0.251, green: 0.7843, blue: 0.8784),
            DesignTokenRGB(red: 0.8784, green: 0.4784, blue: 0.8157),
            DesignTokenRGB(red: 1, green: 0.2392, blue: 0.6196),
        ]
    }

    /// Opacities the chevrons are drawn at, per phase (web uses its own).
    public enum Opacity {
        public static let directionWeb: Double = 0.42
        public static let directionFlying: Double = 0.62
        public static let directionOffFoil: Double = 0.38
        public static let directionNeutral: Double = 0.22
    }

    /// SF Symbols. Shape is a channel of its own — see the contract.
    public enum Glyph {
        /// filled up-arrow — this cost something
        public static let takeoffPumped = "arrow.up.circle.fill"
        /// hollow up-arrow — the wind did it
        public static let takeoffFree = "arrow.up.circle"
        /// hollow red u-turn — went at it and came back down
        public static let takeoffFailed = "arrow.uturn.down.circle"
        /// drop glyph — submersion evidence
        public static let splash = "drop.fill"
        /// filled star — a clean jibe, drawn instead of that turn's outcome dot
        public static let cleanJibe = "star.fill"
    }

    /// The hex half of every colour token — what the web renders. Not used
    /// for drawing on iOS; it exists so the two halves stay in one file.
    public enum Hex {
        public static let outcomeFlew = "#0ca30c"
        public static let outcomeTouchdown = "#fab219"
        public static let outcomeFellIn = "#d03b3b"
        public static let outcomeCourseChange = "#7a7a72"
        public static let effortPumping = "#8f7ce8"
        public static let effortTakeoff = "#3987e5"
        public static let effortSplash = "#3fc4d8"
        public static let effortFailedTakeoff = "#d03b3b"
        public static let effortWindow = "#ff9f0a"
        public static let phaseFlying = "#40c8e0"
        public static let phaseOffFoil = "#97979d"
        public static let directionInk = "#c3c2b7"
        public static let sidePort = "#a38054"
        public static let sideStarboard = "#d9b9a3"
        public static let cleanJibe = "#2ee6a8"
        public static let speedStopped = "#4f63d8"
        public static let speedSlow = "#3d9ad9"
        public static let speedEntry = "#40c8e0"
        public static let speedFast = "#e07ad0"
        public static let speedFastest = "#ff3d9e"
    }

    /// The record picker: canonical order, display labels, and the window every
    /// session opens on.
    public enum RecordWindows {
        public static let defaultID = "best2s"
        public static let catalogue: [DesignTokenEntry] = [
            DesignTokenEntry(id: "best2s", label: "2 s"),
            DesignTokenEntry(id: "best10s", label: "10 s"),
            DesignTokenEntry(id: "best5x10s", label: "5 × 10 s"),
            DesignTokenEntry(id: "best100m", label: "100 m"),
            DesignTokenEntry(id: "best250m", label: "250 m"),
            DesignTokenEntry(id: "best500m", label: "500 m"),
            DesignTokenEntry(id: "bestNm", label: "1 NM"),
            DesignTokenEntry(id: "alpha500", label: "Alpha 500"),
        ]
        public static let order: [String] = catalogue.map(\.id)
    }

    /// The legend's layer catalogue: ids, chip text, and which layers a rider who
    /// has never touched a chip sees.
    public enum Layers {
        public static let catalogue: [DesignTokenEntry] = [
            DesignTokenEntry(id: "flying", label: "flying"),
            DesignTokenEntry(id: "offFoil", label: "off foil"),
            DesignTokenEntry(id: "effort", label: "best effort"),
            DesignTokenEntry(id: "pumping", label: "pumping"),
            DesignTokenEntry(id: "cleanJibe", label: "clean jibe"),
            DesignTokenEntry(id: "flewThrough", label: "flew through"),
            DesignTokenEntry(id: "touchdown", label: "touchdown"),
            DesignTokenEntry(id: "fellIn", label: "fell in"),
            DesignTokenEntry(id: "courseChange", label: "course change"),
            DesignTokenEntry(id: "takeoff", label: "takeoff"),
            DesignTokenEntry(id: "splash", label: "splash"),
            DesignTokenEntry(id: "direction", label: "direction"),
        ]
        public static let order: [String] = catalogue.map(\.id)
        public static let visibleByDefault: [String] = [
            "flying",
            "offFoil",
            "effort",
            "pumping",
            "cleanJibe",
            "flewThrough",
            "touchdown",
            "fellIn",
            "courseChange",
            "takeoff",
            "splash",
            "direction",
        ]
    }
}

/// One authored colour as numbers — the ramp's stops, so a renderer can mix two of
/// them. SwiftUI's `Color` is opaque and its own blend is newer than this package's
/// oldest platform, so the components live here rather than being read back out.
public struct DesignTokenRGB: Sendable, Equatable {
    public let red: Double
    public let green: Double
    public let blue: Double

    public init(red: Double, green: Double, blue: Double) {
        self.red = red
        self.green = green
        self.blue = blue
    }

    public var color: Color { Color(red: red, green: green, blue: blue) }
}

/// One catalogue row: the id the code switches on, and the words the rider reads.
public struct DesignTokenEntry: Sendable, Equatable, Identifiable {
    public let id: String
    public let label: String

    public init(id: String, label: String) {
        self.id = id
        self.label = label
    }
}
