import Foundation

/// **The words the presentation document points at**, and the one place they are written.
///
/// `PresentationDocument` carries no rider sentence: every label and every caption in it is
/// an **id** plus the arguments the sentence interpolates (ADR-033,
/// `docs/presentation/document.md`). This is where the ids that no other artefact already
/// owns are resolved, and it is the **author** of `docs/copy/presentation.json` — the file
/// is the artefact, regenerated by `COPY_WRITE=1 swift test --filter CopyContractTests`,
/// exactly the way `MetricGlossary` authors `glossary.json`.
///
/// It was hand-authored in that file until round 2 of ADR-033. That was the wrong home for
/// it by the copy contract's own rule (`docs/copy/README.md`, "The contract"): the kit is
/// the author for anything the app says, and the app is what prints these. Hand-authored
/// copy that the kit prints is copy the kit cannot be held to.
///
/// Four other namespaces a `labelId` may use, and **there are no others** — all four are
/// resolved by `text(_:args:)` below, so a renderer never learns which is which:
///
/// | namespace | resolves in |
/// |---|---|
/// | `glossary.<id>` | `MetricGlossary` (→ `docs/copy/glossary.json`) |
/// | `tokens.recordWindow.<id>` | `RecordKind.label` (→ `design/tokens.json`) |
/// | `tokens.layer.<id>` | `MapLayer.label` (→ `design/tokens.json`) |
/// | `verdicts.notASession.*` | `NotASessionNote` (→ `docs/copy/verdicts.json`) |
public enum PresentationCopy {

    /// One sentence, with the singular form a `{count}` placeholder needs where it has one.
    ///
    /// A `one` form is used when the caption's **first** argument is 1 — "of 1 tack" rather
    /// than "of 1 tacks". Held as a pair rather than as a format rule because English is
    /// not the only thing that changes ("of 1 tack" drops the number entirely).
    public struct Line: Sendable, Equatable {
        public let other: String
        public let one: String?

        public init(_ other: String, one: String? = nil) {
            self.other = other
            self.one = one
        }

        /// The form to print for a count. `nil` count takes `other`, which is what every
        /// caption with no number does.
        public func form(for count: Int?) -> String {
            count == 1 ? (one ?? other) : other
        }
    }

    // MARK: - The groups

    /// The key-metrics block's own labels — the word under a number.
    ///
    /// Lowercase on purpose: they are captions under a value, not titles
    /// (`docs/presentation/labels.md`, "Label table"). `max 2 s` is the one sanctioned
    /// divergence from `RecordKind.label`'s `Best 2 s`, because this names the *window* the
    /// number was measured over rather than the record it set.
    public static let label: [String: String] = [
        "alpha500": "alpha 500",
        "avgSpeed": "avg speed",
        "best5x10s": "5×10 s",
        "cleanJibes": "clean jibes",
        "distance": "distance",
        "duration": "duration",
        "max2s": "max 2 s",
        "outcomeLadder": "flew · touch · fell",
        "streaks": "best streaks",
    ]

    /// The library row's own short spelling of a metric. Deliberately shorter than the
    /// glossary term, because it sits under a value in caption type beside two others on a
    /// phone (`RowMetric`).
    public static let rowMetric: [String: String] = [
        "best10s": "best 10 s",
        "best2s": "best 2 s",
        "cleanJibes": "clean",
        "distance": "distance",
        "dryStreak": "dry streak",
        "duration": "time",
        "falls": "fell in",
        "flights": "flights",
        "foilShare": "foil",
        "jibes": "jibes",
        "turns": "turns",
    ]

    /// The rider's word for a kind of sweep. Interpolated **into** a caption rather than
    /// named by a `labelId` — the wrist-under callout is the one that asks for it.
    public static let turnKind: [String: String] = [
        "bearAway": "bear-away",
        "jibe": "jibe",
        "roundUp": "round-up",
        "tack": "tack",
        "turn": "turn",
    ]

    /// The small line under a cell.
    public static let caption: [String: Line] = [
        "fallsSplit": Line("{inTurn} in a turn · {straight} in a straight line"),
        "ofJibes": Line("of {jibes} jibes", one: "of 1 jibe"),
        "ofTacks": Line("of {tacks} tacks", one: "of 1 tack"),
        "ofTurns": Line("of {turns} turns"),
    ]

    /// "Wrist under" — the submersion callout's title and its `during` clause.
    public static let wristUnder: [String: String] = [
        "afterFlight": "after flight {flight} ended",
        "afterFlightStopped": "after flight {flight} ended, stopped {stoppedS} s",
        "duringAnyTurn": "during a {turn}",
        "duringTurn": "during {turn} {ordinal}",
        "offFoil": "while off foil",
        "title": "Wrist under",
        "titleFor": "Wrist under · {durationS} s",
    ]

    /// **The six divergence metrics that have no other home.** The other six the check can
    /// report are speed records and are named by `tokens.recordWindow.<id>`, so there is one
    /// spelling of `Best 2 s` in the product and the banner uses it
    /// (`DivergenceCheck`, `docs/algorithms/divergence.md`).
    public static let divergence: [String: String] = [
        "flights": "Flights",
        "foilTime": "Foil time",
        "jibes": "Jibes",
        "tacks": "Tacks",
        "takeoffAttempts": "Takeoff attempts",
        "takeoffs": "Takeoffs",
    ]

    /// The sentences a renderer **builds** rather than names: the divergence banner's one
    /// line, and the two ways its list of metrics ends.
    ///
    /// Not reachable by a `labelId`, like `turnKind` and for the same reason — the document
    /// carries the lines, the renderer carries the sentence that introduces them.
    public static let banner: [String: String] = [
        "divergence": "Watch and phone disagree on {metrics}",
        "divergenceMore": "{first} and {rest} more",
        "divergencePair": "{first} and {second}",
    ]

    /// **The share card's own words** (layout B v2, Jan, 26 Sep 2026). Not reachable by a
    /// document `labelId`: the card is a renderer of the block, and these are the words it
    /// lays the block's numbers out with — the hero's line, the two bars' names, the
    /// streak line, the rates in words and the composer's hero picker.
    ///
    /// The rates are spelled out on purpose: a card is read by people who have never seen
    /// the app, so "CPH" alone is a word nobody taught them. "dry" is the rider vocabulary
    /// (did not fall in), which is what the JPH and TPH numerators count.
    public static let card: [String: Line] = [
        "heroClean": Line("clean jibes", one: "clean jibe"),
        "heroMax2s": Line("top speed · best 2 s"),
        "heroTacks": Line("tacks", one: "tack"),
        "heroTacksDry": Line("{dry} dry"),
        "heroTacksBeside": Line("{dry} dry · beside {jibes}"),
        // The period card's third hero (26 Sep 2026): how many afternoons, and where.
        "heroSessions": Line("sessions", one: "session"),
        "heroSessionsSpots": Line("at {spots} spots", one: "at one spot"),
        "jibeCount": Line("{jibes} jibes", one: "1 jibe"),
        "barJibes": Line("jibes"),
        "barTacks": Line("tacks"),
        "barTurns": Line("turns"),
        "barClean": Line("{clean} clean"),
        "streak": Line("best streak"),
        "fellIn": Line("fell in {falls} times", one: "fell in once"),
        "fellInNone": Line("never fell in"),
        "rateCph": Line("clean jibes / h"),
        "rateJph": Line("dry jibes / h"),
        "rateTph": Line("dry turns / h"),
        "ribbonHours": Line("time on the water"),
        "speedEstimated": Line("speed estimated from GPS positions"),
        "optionTitle": Line("Big number"),
        "optionClean": Line("Clean jibes"),
        "optionMax2s": Line("Top speed"),
        "optionTacks": Line("Tacks"),
        "optionSessions": Line("Sessions"),
    ]

    /// One of the card's own words, with its singular form where `count` is 1.
    public static func card(_ key: String, count: Int? = nil,
                            _ args: [String: String] = [:]) -> String {
        guard let line = card[key] else { return "" }
        var text = line.form(for: count)
        for (k, v) in args { text = text.replacingOccurrences(of: "{\(k)}", with: v) }
        return text
    }

    // MARK: - Resolving an id

    /// Which spelling of a glossary word a cell wants.
    ///
    /// The glossary holds one word in four lengths and the cell that prints it decides
    /// which — the rate row prints `JPH · dry jibes per hour`, the falls cell prints
    /// `fell in`, the streaks pair prints `flew`. That is a *typographic* decision, which
    /// `docs/presentation/document.md` leaves with the renderer; what may never differ is
    /// the word itself, and all four come from one entry.
    public enum GlossaryForm: Sendable {
        /// `Fell in` — the term as the glossary spells it.
        case term
        /// `fell in` — the term under a number, where a capital would read as a title.
        case lowercased
        /// `JPH · dry jibes per hour` — the term and its expansion.
        case labelled
        /// `flew` — the watch's width, which is also the width of half a streaks cell.
        case short
    }

    /// One id, resolved into the words a rider reads.
    ///
    /// Returns `nil` for an id with no home, which is what
    /// `PresentationCopyTests.everyIdTheDocumentCanEmitHasAHome` fails on: an unresolvable
    /// id is a label a rider would read as an empty space.
    public static func text(_ id: String, args: [String: String] = [:],
                            glossary: GlossaryForm = .term) -> String? {
        let parts = id.split(separator: ".").map(String.init)
        guard parts.count >= 2 else { return nil }

        switch parts[0] {
        case "presentation":
            guard parts.count == 3, let line = line(group: parts[1], key: parts[2]) else {
                return nil
            }
            return interpolate(line, args)

        case "glossary":
            guard parts.count == 2,
                  let entry = MetricGlossary.entries.first(where: { $0.id == parts[1] })
            else { return nil }
            switch glossary {
            case .term: return entry.term
            case .lowercased: return entry.term.lowercased()
            case .labelled: return entry.labelled
            case .short: return entry.short
            }

        case "tokens":
            guard parts.count == 3 else { return nil }
            switch parts[1] {
            case "recordWindow": return RecordKind(rawValue: parts[2])?.label
            case "layer": return MapLayer(rawValue: parts[2])?.label
            default: return nil
            }

        case "verdicts":
            guard parts.count >= 3, parts[1] == "notASession" else { return nil }
            if parts[2] == "tag" { return NotASessionNote.tag }
            // The two lines are a *function* of the two numbers that decided, so the id
            // resolves by calling the one that writes them rather than by interpolating a
            // template — which is what keeps the page's sentence and the row's tag one
            // author (`NotASessionNote`).
            guard parts.count == 4, parts[2] == "lines", let index = Int(parts[3]),
                  index == 0 || index == 1 else { return nil }
            return NotASessionNote.line(reason: index == 0 ? .noRecording : .tooShort,
                                        durationS: args["durationS"].flatMap(Double.init),
                                        distanceKm: args["distanceKm"].flatMap(Double.init))

        default:
            return nil
        }
    }

    /// One caption of the document — an id and the arguments its sentence interpolates —
    /// as the sentence itself.
    public static func captionText(_ id: String,
                                   args: [String: PresentationValue]) -> String? {
        text(id, args: arguments(args, forCaption: id))
    }

    /// A document caption cell — `{"id": …, "args": {…}}` — as its sentence.
    public static func captionText(_ value: PresentationValue) -> String? {
        guard let id = value["id"]?.stringValue else { return nil }
        return captionText(id, args: value["args"]?.objectValue ?? [:])
    }

    /// The sentence for a group and a key, singular form included where the first argument
    /// is a 1.
    static func line(group: String, key: String) -> Line? {
        switch group {
        case "label": return label[key].map { Line($0) }
        case "rowMetric": return rowMetric[key].map { Line($0) }
        case "turnKind": return turnKind[key].map { Line($0) }
        case "caption": return Self.caption[key]
        case "wristUnder": return wristUnder[key].map { Line($0) }
        case "divergence": return divergence[key].map { Line($0) }
        case "banner": return banner[key].map { Line($0) }
        case "card": return card[key]
        default: return nil
        }
    }

    /// `{placeholder}` substitution, and the plural rule.
    ///
    /// The **first** argument decides the form, which is why the caption's arguments are
    /// turned into strings by `arguments(_:forCaption:)` rather than handed over as a
    /// dictionary the plural rule would have to guess at.
    static func interpolate(_ line: Line, _ args: [String: String]) -> String {
        var text = line.form(for: args["_count"].flatMap(Int.init))
        for (key, value) in args where key != "_count" {
            text = text.replacingOccurrences(of: "{\(key)}", with: value)
        }
        return text
    }

    static func interpolate(_ line: String, _ args: [String: String]) -> String {
        interpolate(Line(line), args)
    }

    /// A caption's document arguments as the strings its sentence interpolates.
    ///
    /// Three rules, and they are the whole of it:
    ///
    /// * a number is printed plainly (the document already rounded it to the decimals its
    ///   `unitKind` carries, which is why `4` and never `4.0` reaches a sentence);
    /// * an argument named `<name>Id` is itself an id — the wrist-under callout's
    ///   `turnId: "bearAway"` — and fills the `{<name>}` the sentence spells;
    /// * the plural form follows the caption's own counting argument, which is the one the
    ///   `one` line drops.
    static func arguments(_ args: [String: PresentationValue],
                          forCaption id: String) -> [String: String] {
        var out: [String: String] = [:]
        for (key, value) in args {
            if key.hasSuffix("Id"), case .string(let raw) = value {
                let name = String(key.dropLast(2))
                out[name] = text("presentation.turnKind." + raw) ?? raw
                continue
            }
            out[key] = plain(value)
        }
        if let key = countingArgument(of: id), case .int(let count)? = args[key] {
            out["_count"] = String(count)
        }
        return out
    }

    /// Which argument decides a caption's singular form. Named per caption rather than
    /// guessed from the argument order, because a dictionary has none.
    static func countingArgument(of id: String) -> String? {
        switch id {
        case "presentation.caption.ofTacks": "tacks"
        case "presentation.caption.ofTurns": "turns"
        case "presentation.caption.ofJibes": "jibes"
        default: nil
        }
    }

    /// A document value as the digits a sentence prints. Whole numbers lose the `.0` the
    /// JSON spells them with: the document rounds for determinism, the sentence prints.
    static func plain(_ value: PresentationValue) -> String {
        switch value {
        case .int(let v): return String(v)
        case .number(let v): return v == v.rounded() ? String(Int(v)) : String(v)
        case .string(let v): return v
        case .bool(let v): return v ? "true" : "false"
        case .null: return "—"
        case .array, .object: return ""
        }
    }
}
