// Generated by design/generate_tokens.py from design/tokens.json — do not edit.
// Edit the tokens, re-run the generator, and commit every generated file
// together; design/check_tokens.py --check fails the build on drift.
//
// Contract: docs/presentation.md — the meanings. This file carries only values.
//
// The watch consumes the HEX half of every token, the way the web does:
// `Dc.setColor` takes a literal 0xRRGGBB on every product in garmin/manifest.xml,
// and `Graphics.createColor` is not needed (nor uniformly available) for that. What
// the watch does NOT have is iOS's semantic layer, so a token used here is a fixed
// RGB, and this file is the only place those RGBs may be written.
//
// THE _MIP TWINS. The AMOLED products (fenix 8 43/47 mm) are 16 bpp and render the
// hex as authored. The 8 bpp products — both fenix 8 Solars and the whole fenix 7
// family — quantise every colour to a fixed 64-entry palette, one of
// {0x00, 0x55, 0xAA, 0xFF} per channel. The firmware does that snapping on its own,
// so passing the AMOLED literal would still *render* correctly; the twin is written
// down anyway so the fallback is a reviewable value rather than a surprise, and so a
// token whose nearest palette entry collides with another token's is visible here
// instead of on the water. Ink.mc picks the right half per device.
//
// Palette collisions on 8 bpp — distinguishable on AMOLED, identical
// on MIP. None of these pairs is drawn on the same watch screen:
//   0xFFAA00  outcome.touchdown = effort.window
//   0xAA5555  outcome.fellIn = effort.failedTakeoff
//   0x55AAFF  effort.takeoff = effort.splash = phase.flying
//   0xAAAAAA  phase.offFoil = direction.ink
//
import Toybox.Lang;

module DesignTokens {

    // ---- outcome: The verdict ladder. Nothing outside a maneuver outcome may borrow it.
    // flew through — carried the maneuver on the foil
    const OUTCOME_FLEW = 0x0CA30C;
    const OUTCOME_FLEW_MIP = 0x00AA00;
    // touchdown — lost it briefly
    const OUTCOME_TOUCHDOWN = 0xFAB219;
    const OUTCOME_TOUCHDOWN_MIP = 0xFFAA00;
    // fell in — swam
    const OUTCOME_FELL_IN = 0xD03B3B;
    const OUTCOME_FELL_IN_MIP = 0xAA5555;
    // bear-away / round-up — a non-verdict, deliberately outside the ladder
    const OUTCOME_COURSE_CHANGE = 0x7A7A72;
    const OUTCOME_COURSE_CHANGE_MIP = 0x555555;

    // ---- effort: Effort and water: outside the ladder — nothing here is a verdict.
    // pump-burst spans on the track
    const EFFORT_PUMPING = 0x8F7CE8;
    const EFFORT_PUMPING_MIP = 0xAA55FF;
    // takeoff attempts that flew
    const EFFORT_TAKEOFF = 0x3987E5;
    const EFFORT_TAKEOFF_MIP = 0x55AAFF;
    // the barometer saw the wrist go under
    const EFFORT_SPLASH = 0x3FC4D8;
    const EFFORT_SPLASH_MIP = 0x55AAFF;
    // the one effort-layer event with an outcome, so it alone borrows the ladder's red
    const EFFORT_FAILED_TAKEOFF = 0xD03B3B;
    const EFFORT_FAILED_TAKEOFF_MIP = 0xAA5555;
    // the selected record window: the glow on the track and the shading in the chart (the `effort` layer's ink, hex = systemOrange on dark)
    const EFFORT_WINDOW = 0xFF9F0A;
    const EFFORT_WINDOW_MIP = 0xFFAA00;

    // ---- phase: Track / ring / bar tint by phase. NOT the ladder's green.
    // track tinted on foil (hex = systemTeal on dark, what SwiftUI .teal renders as)
    const PHASE_FLYING = 0x40C8E0;
    const PHASE_FLYING_MIP = 0x55AAFF;
    // track tinted off foil (hex = the secondary label over a dark surface, what SwiftUI .secondary renders as)
    const PHASE_OFF_FOIL = 0x97979D;
    const PHASE_OFF_FOIL_MIP = 0xAAAAAA;

    // ---- direction: Course-of-travel ink: subordinate to every mark.
    // chevron ink — subordinate to every marker, so ink plus opacity, no hue
    const DIRECTION_INK = 0xC3C2B7;
    const DIRECTION_INK_MIP = 0xAAAAAA;

    // ---- side: Entry tack. A side is not a verdict — never the ladder's inks.
    // port ENTRY tack — a side, never a verdict, so deliberately outside the ladder
    const SIDE_PORT = 0xA38054;
    const SIDE_PORT_MIP = 0xAAAA55;
    // starboard ENTRY tack — the same hue at a second lightness, plus a dashed stroke
    const SIDE_STARBOARD = 0xD9B9A3;
    const SIDE_STARBOARD_MIP = 0xFFAAAA;

    // ---- clean: The clean jibe. A STRICTER question than the ladder's top rung, so it
    // gets its own ink and never the ladder's green.
    // clean jibe — the strict verdict's own ink: a green deliberately NOT the ladder's flew-through green, because clean is what a jibe cost and flew through is how it ended
    const CLEAN_JIBE = 0x2EE6A8;
    const CLEAN_JIBE_MIP = 0x55FFAA;
}
