/* GENERATED by web/tools/make_app_copy.py from docs/ — do not edit.
 *
 * The browser app's shell, in the iPhone app's words: the four tabs, the app menu, the
 * session sub-tabs, the ways in, the welcome, What's new, Help and the feedback door.
 *
 * Regenerate after a deliberate wording change:
 *
 *     python3 web/tools/make_app_copy.py
 *
 * The lists are pinned from both sides. `web/tools/verify_app_shell.py` reads the kit's own
 * Swift and fails when this and the phone disagree, and reads web/app/index.html and fails
 * when the page has drifted from either.
 */

/** The four tabs, the five menu rows and the four session sub-tabs
 *  (docs/copy/app-shell.json). One order, one wording, both surfaces. */
export const SHELL = {
  "tabs": [
    {
      "id": "sessions",
      "title": "Sessions"
    },
    {
      "id": "records",
      "title": "Records"
    },
    {
      "id": "trends",
      "title": "Trends"
    },
    {
      "id": "gear",
      "title": "Gear & spots"
    }
  ],
  "menu": [
    {
      "id": "whatItDoes",
      "title": "What CleanJibe does"
    },
    {
      "id": "gettingStarted",
      "title": "Getting started"
    },
    {
      "id": "settings",
      "title": "Settings",
      "afterDivider": true
    },
    {
      "id": "help",
      "title": "Help"
    },
    {
      "id": "support",
      "title": "Support & ideas"
    }
  ],
  "sessionSections": [
    {
      "id": "ride",
      "title": "Ride"
    },
    {
      "id": "turns",
      "title": "Turns"
    },
    {
      "id": "takeoffs",
      "title": "Takeoffs"
    },
    {
      "id": "log",
      "title": "Details"
    }
  ]
};

/**
 * The empty Sessions tab: the iPhone's ways-in card, with the two doors only a
 * browser has at the top of it.
 *
 * `here` is false on a door a browser cannot open. Those rows say why in their own
 * line and still link to the route, because the route is real and the reader may
 * be about to take it on the phone.
 */
export const WAYS_IN = {
  "title": "How your sessions get in",
  "rows": [
    {
      "id": "drop",
      "title": "Drop a .fit, .gpx or .tcx here",
      "line": "Or choose a file. It never leaves this tab.",
      "here": true
    },
    {
      "id": "example",
      "title": "Load the example session",
      "line": "10 real minutes on Lake Garda, already analysed.",
      "here": true
    },
    {
      "id": "garmin",
      "title": "Garmin with the CleanJibe watch app",
      "line": "Paste your intervals.icu key in Settings. Sessions arrive by themselves.",
      "here": true,
      "href": "/start/#guide-garmin",
      "status": "fenix, epix, Forerunner and the rest"
    },
    {
      "id": "appleWatchApp",
      "title": "The CleanJibe Apple Watch app",
      "line": "On the iPhone app. A browser cannot reach your watch.",
      "here": false,
      "href": "/start/#guide-appleWatchApp",
      "status": "Apple Watch · everything a Garmin gets"
    },
    {
      "id": "appleWorkoutApp",
      "title": "Apple's own Workout app",
      "line": "On the iPhone app. Apple Health is closed to a browser.",
      "here": false,
      "href": "/start/#guide-appleWorkoutApp",
      "status": "Apple Watch · nothing to install"
    },
    {
      "id": "fit",
      "title": "Any watch that writes a .fit",
      "line": "Export the file. Then drop it here.",
      "here": true,
      "href": "/start/#guide-fit",
      "status": "Polar, Suunto, COROS and everything else"
    },
    {
      "id": "strava",
      "title": "Strava",
      "line": "On the iPhone app. Strava sign-in needs it.",
      "here": false,
      "href": "/start/#guide-strava",
      "status": "any watch that syncs to Strava"
    }
  ]
};

/** The five routes in, as the welcome screen lists them
 *  (docs/guide/getting-started.json, the order both surfaces print). */
export const GUIDE = {
  "framing": "Ride one session as you always do. Open it in CleanJibe. Check each turn: flew through, touchdown, fell in. Only you know which it really was.",
  "lede": "Take the route that matches your wrist. Go outside: every route needs GPS, and a watch indoors records no positions. Every route ends the same way. The session lands in CleanJibe, analysed as it arrives.",
  "routes": [
    {
      "id": "garmin",
      "title": "Garmin with the CleanJibe watch app",
      "status": "fenix, epix, Forerunner and the rest",
      "summary": "Install it from Connect IQ, ride, save. Sessions sync through intervals.icu: Settings → intervals.icu, 4 steps, once.",
      "href": "/start/#guide-garmin"
    },
    {
      "id": "appleWatchApp",
      "title": "The CleanJibe Apple Watch app",
      "status": "Apple Watch · everything a Garmin gets",
      "summary": "Record on your Apple Watch. The session comes to the phone by itself, with pump strokes and takeoff attempts included.",
      "href": "/start/#guide-appleWatchApp"
    },
    {
      "id": "appleWorkoutApp",
      "title": "Apple's own Workout app",
      "status": "Apple Watch · nothing to install",
      "summary": "No extra app on the watch: record a Surfing workout and import it from Apple Health.",
      "href": "/start/#guide-appleWorkoutApp"
    },
    {
      "id": "fit",
      "title": "Any watch that writes a .fit",
      "status": "Polar, Suunto, COROS and everything else",
      "summary": "Sync it through intervals.icu, or share the file into CleanJibe from Files, Mail, AirDrop or any share sheet.",
      "href": "/start/#guide-fit"
    },
    {
      "id": "strava",
      "title": "Strava",
      "status": "any watch that syncs to Strava",
      "summary": "Settings → Strava → Connect with Strava, then Import → Import from Strava…. Positions only, records uncertified. Without the watch's own speed, a fall can read as a touchdown.",
      "href": "/start/#guide-strava"
    }
  ]
};

/** The sentence at the top of a Settings section, the phone's own
 *  (`GettingStartedGuide.settingsIcu` / `.settingsStrava`). */
export const SETTINGS = {
  "intervalsIcu": "Garmin has no open API, so intervals.icu is the bridge. Connect Garmin there once. Every session then arrives here by itself. Free.",
  "strava": "Any watch that syncs to Strava, no file needed. Positions only, so speed records are uncertified. Without the watch's own speed, a fall can read as a touchdown."
};

/**
 * The Settings page, section by section, in the order the iPhone draws it
 * (docs/copy/settings.json, written out of the kit's `SettingsCopy`).
 *
 * `lead` is what a rider reads by default: what you get, in one line (pattern K).
 * `footer` is the phone's own paragraphs, shown only in the extensive reading.
 * `help` is the topic the section's `?` opens; a section without one has no `?`.
 */
export const SETTINGS_SECTIONS = [
  {
    "id": "icu",
    "title": "intervals.icu",
    "lead": "Your sessions arrive by themselves, from any watch that syncs there.",
    "footer": [
      "Downloads the original FIT of every windsurf, wing, kite, surf and SUP activity in your intervals.icu account. Two years back.",
      "Activities already in the library are never downloaded again."
    ],
    "help": "icuSetup"
  },
  {
    "id": "strava",
    "title": "Strava",
    "lead": "Import what you already ride with. CleanJibe only ever reads it.",
    "footer": [
      "Strava opens, you say yes, and CleanJibe can list your activities on the Import screen.",
      "CleanJibe only reads your Strava account. It never writes, renames or posts anything.",
      "Sessions imported this way are analysed from positions alone. Their speed records are marked uncertified.",
      "Strava lets a new app connect a limited number of riders. Connecting is refused while CleanJibe is full.",
      "That says nothing about your account."
    ],
    "help": "stravaImport"
  },
  {
    "id": "deleted",
    "title": "Deleted sessions",
    "lead": "Put back a session you deleted.",
    "footer": [
      "Sessions you deleted stay deleted. Syncing intervals.icu leaves them alone, by hand and in the background.",
      "Restoring forgets that. The next sync brings back every one of them that is still on intervals.icu."
    ],
    "help": "libraryBackup"
  },
  {
    "id": "units",
    "title": "Units",
    "lead": "Read speeds in knots or in km/h.",
    "footer": [
      "Speeds are read in knots by the speedsurfing world. Pick km/h if that is the number you think in."
    ],
    "help": "speedRecords"
  },
  {
    "id": "data",
    "title": "Your data",
    "lead": "What this browser holds, a copy you keep, and the way to wipe it.",
    "footer": [
      "Saved sessions are written to this browser's private per-origin storage.",
      "They are not synced, not backed up and not visible to any other site.",
      "Clearing this site's data, or using a private window, deletes them.",
      "Download all writes one zip. Restore from a backup reads that same file."
    ],
    "help": "libraryBackup"
  },
  {
    "id": "about",
    "title": "About",
    "lead": "What is running here, and where the privacy policy is.",
    "footer": [
      "Wind is estimated on this device from your track."
    ],
    "help": "privacy"
  },
  {
    "id": "whatsNew",
    "title": "What's new",
    "lead": "The release notes, newest first.",
    "footer": [],
    "help": "whatsNew"
  }
];

/** The welcome's headline and promise, and the four glossary ids it shows.
 *  The lines come from `GLOSSARY` in ./copy.js, which is their one home. */
export const WELCOME = {
  "headline": "Every flight, every jibe, every swim.",
  "promise": "Did you fly through that jibe? CleanJibe reads your session off the watch. It tells you your time on the foil, every flight, your speed records, and a verdict on every turn. Flew through, touchdown, or fell in.",
  "highlights": [
    "foilShare",
    "flights",
    "dryStreak",
    "speedRecords"
  ]
};

/** What's new, release and beta only — the filter /whats-new/ uses. */
export const WHATS_NEW = [
  {
    "version": "1.0.1",
    "build": 93,
    "channel": "beta",
    "date": "2026-09-20",
    "title": "Eleven traps on the wrist",
    "lines": [
      "The watch app closes eleven traps of its own, and counts a run that never reached its end.",
      "The feedback mail prints the watch's count beside the phone's crashes.",
      "Version 1.0.1 across every channel now. TestFlight ranks by version first.",
      "Pair with watch app 0.9.15 from the store."
    ]
  },
  {
    "version": "0.15.0",
    "build": 91,
    "channel": "beta",
    "date": "2026-09-20",
    "title": "The last trap",
    "lines": [
      "The file reader's library is ours now. A value past its type no longer takes the app down.",
      "Please sync your intervals.icu once more on this build."
    ]
  },
  {
    "version": "0.15.0",
    "build": 89,
    "channel": "beta",
    "date": "2026-09-19",
    "title": "A year in one sync",
    "lines": [
      "A year of another rider's recordings syncs without a crash. Six traps in the file reader are closed.",
      "A file cut off mid-download, or a broken clock, is refused with its name instead of taking the app down.",
      "The sync shows which file it is on, and many failures become one message.",
      "Please sync your intervals.icu again and tell us if anything still falls over."
    ]
  },
  {
    "version": "0.15.0",
    "build": 81,
    "channel": "beta",
    "date": "2026-09-19",
    "title": "SUP by default",
    "lines": [
      "Stand-up paddling is a Strava sport by default now. Sail is the one switch left.",
      "Please check Import → Strava if your sessions are filed under SUP."
    ]
  },
  {
    "version": "0.15.0",
    "build": 79,
    "channel": "beta",
    "date": "2026-09-19",
    "title": "Names, help and three more trend lines",
    "lines": [
      "Every screen is named by what it does. Details, Turn 3 of 12, Import from Strava.",
      "Trends draw jibes per hour, turns per hour and the best 2 seconds.",
      "A best 2 s without the watch's own speed draws as an open ring. The caption names the session.",
      "Help answers a Garmin rider: why Windsurf, where Garmin Connect shows the jibes, why Runs stays empty.",
      "Help says why the watch shows km/h while the app shows knots.",
      "Please check the Trends tab and the new screen names."
    ]
  },
  {
    "version": "0.15.0",
    "build": 77,
    "channel": "beta",
    "date": "2026-09-19",
    "title": "Swipe, words, and a map that fits",
    "lines": [
      "Swipe left for the next session, right for the previous one. The page slides.",
      "Each number in the list carries its word. Pick the three in Settings → Session list.",
      "The map behind a track sits under the track now.",
      "Speed records from Strava or GPX: a best 2 s far above the best 10 s is not accepted.",
      "Without the watch's own speed, a fall can read as a touchdown. The Strava pages say so.",
      "Crashes iOS collected ride along in the feedback mail. Delete the lines you would rather keep.",
      "Every sentence is short now. Tell us where one still runs long.",
      "Coming in a future release names the planned Apple Watch live view.",
      "Please check the swipe, the list words and Settings → Session list."
    ]
  },
  {
    "version": "0.15.0",
    "build": 75,
    "channel": "beta",
    "date": "2026-09-19",
    "title": "Every door, one order",
    "lines": [
      "Import lists its doors in one order, the Garmin export last.",
      "Every door stays visible. A door that is off says why.",
      "Both Apple Health switches are always in Settings.",
      "The menu sits on all four tabs.",
      "The session page names where the recording came from.",
      "Tap the title to rename a session.",
      "Swipe left or right for the next or previous session.",
      "Settings → Session list can put a map behind each track.",
      "Help and Settings carry What's new.",
      "A Strava recording can read a fall as a touchdown. The setup pages say so.",
      "Every paragraph is short now. Tell us where the old style still shows.",
      "Please check Import, Settings → Apple Health and the swipe between sessions."
    ]
  },
  {
    "version": "0.15.0",
    "build": 73,
    "channel": "beta",
    "date": "2026-09-15",
    "title": "Jan's morning round",
    "lines": [
      "The empty Sessions page shows the ways in, one row each.",
      "intervals.icu, the Apple Watch app, Strava, a file.",
      "The 4 intervals.icu steps live in Settings only.",
      "Help → Share from your watch app names the brands plainly, Garmin first.",
      "Getting started lists the Apple Watch routes right after Garmin.",
      "Routes have no letters now.",
      "Each route says which class you get.",
      "cleanjibe.org follows: routes without letters, and a class table with a Route column.",
      "Apple Watch appears once on Which watch.",
      "*Show the steps* sits on every route card.",
      "Please check the empty Sessions page after Start over.",
      "Please check Help → Share from your watch app, and Menu → Getting started."
    ]
  },
  {
    "version": "0.15.0",
    "build": 53,
    "channel": "beta",
    "date": "2026-09-14",
    "title": "The beta channel, with its own icon",
    "lines": [
      "The first build of the **beta channel**.",
      "It is the app that goes to the App Store, plus the doors still proving themselves.",
      "GPX and TCX files, the Garmin export ZIP, Apple Health, the video export, grouping and filters, the Apple Watch app.",
      "Settings → Beta lists them and has a *Request a feature* line.",
      "The icon and the start screen wear a red **BETA** label.",
      "This build and the App Store one are told apart at a glance.",
      "The app follows your phone's **text size** everywhere, up to the largest accessibility sizes.",
      "The dense tables stop growing where they would break.",
      "**Feedback from every page**, with a footer on each.",
      "Menu → Support & ideas opens the same mail.",
      "The mail starts with three blanks for you and the facts below.",
      "Settings → Beta → Send usage report mails counters kept on your phone.",
      "Nothing leaves unless you send it.",
      "Sessions group by month, year or spot and filter by source.",
      "Strava shows the official *Connect with Strava* button.",
      "An imported session links back with *View on Strava*.",
      "The three recording classes are named before you import, and in Help.",
      "Worth checking: the BETA icon on your home screen, and Settings → Display → Text Size at its largest.",
      "Nothing should be cut off."
    ]
  },
  {
    "version": "0.15.0",
    "build": 51,
    "channel": "release",
    "date": "2026-09-14",
    "title": "The card from the watch",
    "lines": [
      "A session that arrived as a summary card from the watch opens as what it is.",
      "You get the card's numbers, and how the full recording follows.",
      "It no longer says the file is damaged.",
      "The Sessions list's first grouping reads *All* instead of *None*.",
      "The start screen shows cleanjibe.org under the name."
    ]
  },
  {
    "version": "0.9.10",
    "build": null,
    "channel": "release",
    "date": "2026-09-13",
    "title": "Nine more watches, and the shore",
    "lines": [
      "Nine more watches.",
      "**Venu 2, 2S, 2 Plus, 3 and 3S, vívoactive 5 and 6, Instinct 3 AMOLED 45 and 50 mm.**",
      "That was 39 products in all when 0.9.10 shipped.",
      "They pass the layout checks in the simulator.",
      "They have **not been ridden on a real watch**.",
      "If you have one, tell us how the pages look and whether the touch controls behave.",
      "The live map page and the post-save Track page can draw the shore of your spot.",
      "The shore is drawn under the trail.",
      "The CleanJibe iPhone app sends it over Bluetooth.",
      "Take Settings → Garmin watch → Send map to watch.",
      "No firmware map view is involved.",
      "The firmware's own map kills the app on a fenix 8.",
      "A splash page with the mark on the first launch after an install or update.",
      "A larger mark on the start page."
    ]
  },
  {
    "version": "0.15.0",
    "build": 49,
    "channel": "release",
    "date": "2026-09-13",
    "title": "A crash fix for the watch link",
    "lines": [
      "The app no longer crashes when the Garmin sends it something.",
      "A summary card, or an answer to a map push.",
      "Builds 43 to 47 fell over the moment a message arrived from a watch.",
      "That watch was running a CleanJibe beta build.",
      "Worth checking: send a map to the watch, and finish a short recording on it.",
      "The phone should stay up and the session should appear."
    ]
  },
  {
    "version": "0.15.0",
    "build": 47,
    "channel": "release",
    "date": "2026-09-13",
    "title": "You choose which maps the watch gets",
    "lines": [
      "**Map for the watch** is a page now.",
      "The two most-ridden spots by default, or up to two picks among your own spots.",
      "*Where I am now* is one of the picks.",
      "Settings → Garmin watch → Map for the watch.",
      "The phone reads its own position **once per send**, only when you picked it.",
      "It never reads your position in the background.",
      "The tick asks for the permission where you can see it.",
      "The automatic send at launch never prompts."
    ]
  },
  {
    "version": "0.15.0",
    "build": 45,
    "channel": "release",
    "date": "2026-09-13",
    "title": "The session list groups and narrows",
    "lines": [
      "**Group by** None, Month, Year or Spot at the top of Sessions, newest group first.",
      "A library of twenty or more opens grouped by month until you say otherwise.",
      "A **filter** beside Import: one spot, one source, a date window.",
      "The sources are intervals.icu, Strava, Apple Health, the Garmin watch and a file.",
      "What is active shows as chips you can tap away.",
      "The count line reads *3 of 41 sessions*.",
      "Records and Trends keep reading the whole library on purpose.",
      "The menu at the top left of Sessions, in the order a new rider needs it.",
      "Getting started, Settings, Support, then What CleanJibe does and What the numbers mean.",
      "The build number sits at the foot of that menu.",
      "The welcome screen has a close button now.",
      "**Something off? Send feedback** sits at the foot of every page.",
      "On a session page the mail names the session by itself.",
      "Connect Strava from Settings → Strava as well as from Import.",
      "The full-screen map's legend no longer floats to the middle of the screen.",
      "It used to float after a keyboard was used somewhere else."
    ]
  },
  {
    "version": "0.15.0",
    "build": 43,
    "channel": "release",
    "date": "2026-09-13",
    "title": "Two fixes from build 41",
    "lines": [
      "**Send map to watch** now finds whichever CleanJibe build you have on the watch.",
      "Release, public beta or dev, instead of assuming the release one.",
      "*Failure_AppNotFound* is gone.",
      "The turn page scrolls from anywhere again.",
      "A vertical finger on a strip scrolls the page, a sideways one scrubs the playhead.",
      "A tap places the playhead.",
      "The small window words no longer overprint each other."
    ]
  },
  {
    "version": "0.15.0",
    "build": 41,
    "channel": "release",
    "date": "2026-09-13",
    "title": "The session video, and a wider way in",
    "lines": [
      "**Export video:** a session becomes a short film.",
      "The map draws itself along your track, and the numbers land.",
      "It shares like any other clip.",
      "Open a session → share → Export video.",
      "**Send map to watch:** the phone draws the shore of your spot.",
      "It pushes the shore to a Garmin running CleanJibe 0.9.10.",
      "The live map then has ground under the breadcrumb.",
      "Take Settings → Garmin watch.",
      "**Imports take GPX and TCX** as well as FIT.",
      "A Polar, Suunto or COROS session comes in through intervals.icu.",
      "It also comes straight from the vendor's app through the share sheet.",
      "Without a speed channel the speed records are estimated and marked uncertified.",
      "**Import from Strava:** connect your account under Import and pick the sessions.",
      "Positions only, so speed records are uncertified.",
      "One connected rider at the time this build shipped.",
      "*[Since 14 September: Strava lets a new app connect a limited number of riders.]*",
      "Analysis engine 0.18.0: the pump rung now asks the minimum foil speed.",
      "Every touchdown and fall says *why* it ended that way on the turn page."
    ]
  },
  {
    "version": "0.9.9",
    "build": null,
    "channel": "release",
    "date": "2026-09-09",
    "title": "A clean jibe needs ten quiet seconds",
    "lines": [
      "No touchdown, no swim and no dunked wrist in the ten seconds after the sweep.",
      "The star, the clean count and CPH on the wrist now mean what the phone means.",
      "cleanjibe.org means the same by them.",
      "The clean-jibe buzz therefore arrives up to ten seconds after the turn.",
      "The flew through, touched down and fell in verdicts are unchanged.",
      "They still buzz at once."
    ]
  }
];

/** The help catalogue (docs/copy/help.json). `stub` is true while the kit's own
 *  export is still to come, and the page says so. */
export const HELP = {
  "stub": false,
  "sections": [
    {
      "id": "gettingStarted",
      "title": "Getting started",
      "topics": [
        {
          "body": [
            "Ride one session as you always do. Open it in CleanJibe. Check each turn: flew through, touchdown, fell in. Only you know which it really was."
          ],
          "channels": [
            "release",
            "beta",
            "dev"
          ],
          "id": "gettingStarted",
          "items": [
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "Install it from Connect IQ, ride, save. Sessions sync through intervals.icu: Settings → intervals.icu, 4 steps, once.",
              "term": "Garmin with the CleanJibe watch app"
            },
            {
              "channels": [
                "beta",
                "dev"
              ],
              "detail": "Record on your Apple Watch. The session comes to the phone by itself, with pump strokes and takeoff attempts included.",
              "term": "The CleanJibe Apple Watch app"
            },
            {
              "channels": [
                "beta",
                "dev"
              ],
              "detail": "No extra app on the watch: record a Surfing workout and import it from Apple Health.",
              "term": "Apple's own Workout app"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "Sync it through intervals.icu, or share the file into CleanJibe from Files, Mail, AirDrop or any share sheet.",
              "term": "Any watch that writes a .fit"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "Settings → Strava → Connect with Strava, then Import → Import from Strava…. Positions only, records uncertified. Without the watch's own speed, a fall can read as a touchdown.",
              "term": "Strava"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "Record a 3 to 5 minute walk on the watch. It proves the route from the watch to the phone, nothing else.",
              "term": "If you cannot wait for wind"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "Menu → Support & ideas opens a mail with the facts filled in. TestFlight's own feedback works too if you are on the beta.",
              "term": "Then say how it read"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "cleanjibe.org/start",
              "term": "The same guide, with every step, on the web"
            }
          ],
          "related": [
            "icuSetup",
            "shareFromWatchApp",
            "stravaImport",
            "appleWatchApp",
            "appleWorkoutApp",
            "exampleSession",
            "whichWatch",
            "sendingFeedback"
          ],
          "summary": "Your first session on the water, and where to send what you find.",
          "title": "Getting started"
        },
        {
          "body": [
            "Every release, with the day it shipped. The iPhone app ships as TestFlight builds. The Garmin watch app ships as Connect IQ versions. The two number differently and land on different days."
          ],
          "channels": [
            "release",
            "beta",
            "dev"
          ],
          "id": "whatsNew",
          "items": [],
          "related": [
            "gettingStarted",
            "sendingFeedback"
          ],
          "summary": "What changed in the build you are holding, newest first.",
          "title": "What's new"
        }
      ]
    },
    {
      "id": "setup",
      "title": "Getting set up",
      "topics": [
        {
          "body": [
            "The easiest way in is intervals.icu. Garmin has no open API, so intervals.icu receives your activities and hands CleanJibe the original recording. You can also open a .fit by hand, from Files, Mail or a Garmin export ZIP.",
            "Nothing is uploaded and nothing is changed on either side. CleanJibe lists your activities. It downloads the original recording of the watersport ones. It analyses them on the phone.",
            "Polar, Suunto and Coros work this way too. Their own apps sync to intervals.icu, and CleanJibe syncs from there.",
            "What comes back decides how much you get. A FIT gives the full analysis. A GPX or a speedless TCX gives estimated, uncertified speed records."
          ],
          "channels": [
            "release",
            "beta",
            "dev"
          ],
          "id": "icuSetup",
          "items": [
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "Open intervals.icu and sign up. It is free, and the Google, Strava or e-mail account you already have will do.",
              "term": "1. Create a free intervals.icu account"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "In intervals.icu, Settings → device connections: connect your Garmin account. Your history back-fills in a few minutes, and every new session arrives on its own.",
              "term": "2. Connect Garmin in intervals.icu"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "Still in intervals.icu: Settings → Developer Settings → API Key. Copy it. Developer settings are free for every user. No subscription is needed.",
              "term": "3. Generate your personal API key"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "Paste it into the field below. In the app that field is Settings → intervals.icu. Tap Save & check. CleanJibe verifies it and says how many activities it can see.",
              "term": "4. Paste the key into CleanJibe"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "Garmin has no wingfoil profile. Garmin and Strava call the session Windsurf. CleanJibe calls it Wingfoil.",
              "term": "Why Garmin says Windsurf"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "Under Connect IQ on the activity page: jibes, tacks, foil time, flights and the best 2 seconds. They are written once a wind direction was set.",
              "term": "Where Garmin Connect shows the jibes"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "Runs belong to Garmin's own windsurf profile. No Connect IQ app can fill that card. CleanJibe's flights are the runs.",
              "term": "Why the Runs card stays empty"
            }
          ],
          "related": [
            "exampleSession",
            "icuTroubleshooting",
            "icuPrivacy",
            "sourceClass"
          ],
          "summary": "Four steps, about five minutes, once.",
          "title": "Get set up with intervals.icu"
        },
        {
          "body": [
            "A real wingfoil session on Lake Garda. Ten minutes, 2 flights, 10 jibes, 2.6 km and 68 % foil time. The track, the speed chart, the turn outcomes, the pump counts and the heart-rate cost are all filled in.",
            "It is not your data. CleanJibe badges it EXAMPLE in the list and on its own page. It stays out of Records, Trends and the gear rollups.",
            "Delete it with a swipe. This screen offers it again.",
            "It was recorded at Nago-Torbole, Lake Garda with the CleanJibe watch app, every identifier removed. The accelerometer stream was left out because it is larger than the rest of the app. Pump strokes and takeoff effort show as unavailable."
          ],
          "channels": [
            "release",
            "beta",
            "dev"
          ],
          "id": "exampleSession",
          "items": [],
          "related": [
            "icuSetup",
            "sourceClass",
            "speedRecords",
            "riderAttribution"
          ],
          "summary": "One real session ships with the app. Load it before you connect anything.",
          "title": "Look around with the example session"
        },
        {
          "body": [
            "The watch app records the GPS track, your heart rate and the wrist accelerometer at 50 Hz. Start it on the watch, ride, end the workout. The session transfers to the phone while both are in range.",
            "Because the wrist is recorded, pump strokes and failed takeoff attempts are analysed on the phone. The speed is the watch's own, so the records certify."
          ],
          "channels": [
            "beta",
            "dev"
          ],
          "id": "appleWatchApp",
          "items": [
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "A wrist under water counts as a fall. The pressure sensor sees it. The GPS gap is marked, not filled.",
              "term": "The wrist may go under"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "The session is handed over once you end the workout. If it is not in the list yet, look again in a minute.",
              "term": "Let the workout finish"
            }
          ],
          "related": [
            "appleWorkoutApp",
            "sourceClass",
            "whichWatch",
            "exampleSession"
          ],
          "summary": "Record on your Apple Watch. The session comes to the phone by itself.",
          "title": "Recording with the CleanJibe Apple Watch app"
        },
        {
          "body": [
            "Record a session with Apple's own Workout app and analyse it here. No Garmin, no account, no cable, not even CleanJibe's own watch app.",
            "Health has no wingfoil workout type. CleanJibe reads the one you picked as a wingfoil session, because you asked it to.",
            "Then Import → Apple Health, allow CleanJibe to read workouts, and pick the ones you want. After the first one, switch on \"Import new Health workouts automatically\". The next session is then waiting when you open the app.",
            "Speed comes off the watch's own GPS receiver, so these speed records are certified. Nothing records your wrist accelerometer, so there are no pump strokes and no failed takeoff attempts."
          ],
          "channels": [
            "beta",
            "dev"
          ],
          "id": "appleWorkoutApp",
          "items": [
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "Both are on by default, and Surfing is what CleanJibe's own watch app writes. Sailing works too. Switch it on in Import → Apple Health.",
              "term": "Pick Surfing or Water Sports"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "A wrist under water counts as a fall. The pressure sensor sees it. The GPS gap is marked, not filled.",
              "term": "The wrist may go under"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "The route is written to Health when you end the workout. The watch may take a minute to hand it over.",
              "term": "Let the workout finish saving"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "CleanJibe reads the route and the heart rate of the workouts you pick, and analyses them on your phone. It never reads anything else in Health.",
              "term": "Nothing is uploaded"
            }
          ],
          "related": [
            "appleWatchApp",
            "sourceClass",
            "speedRecords",
            "icuSetup"
          ],
          "summary": "No Garmin, no extra app: record on your Apple Watch and import from Health.",
          "title": "Recording with the Apple Workout app"
        },
        {
          "body": [
            "CleanJibe lists your Strava sessions and imports the ones you pick. It only reads. It never writes, renames or posts to your account.",
            "A Strava session shows everything that comes from the track. Foil time, flights, every turn verdict, the wind axis, the map.",
            "Strava hands over no speed channel, so the speed records are marked uncertified. Without the watch's own speed, a fall can read as a touchdown. Your wrist was not recorded, so there are no pump strokes.",
            "If the same afternoon is also on intervals.icu, import it from there instead. That is the original file off your watch, so those records certify. Importing both is harmless, because the same session is never added twice."
          ],
          "channels": [
            "release",
            "beta",
            "dev"
          ],
          "id": "stravaImport",
          "items": [
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "Settings → Strava → Connect with Strava. Leave the private-activities box ticked or your \"Only you\" sessions will be missing.",
              "term": "Connect"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "Tap the sessions you want, or use Import all new. Anything already in your library is marked and cannot be picked twice.",
              "term": "Pick, or take everything new"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "Windsurf, Kitesurf, Surf, Workout and Stand-up paddling by default. Sail can be switched on. Anything named wing, foil, kite, surf or SUP is offered too.",
              "term": "Which activities are offered"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "Once one session has come in this way, a toggle appears: CleanJibe then checks Strava whenever you open the app.",
              "term": "Keep it automatic"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "Strava answers 200 requests every 15 minutes. A first import of many seasons may ask you to come back shortly.",
              "term": "A long history takes its time"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "Strava lets a new app connect a limited number of riders. That says nothing about your account. Menu → Support & ideas is the way to report it.",
              "term": "If connecting is refused"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "Settings → Strava → Disconnect Strava. The sessions you already imported stay in your library. They are yours now, analysed on this phone.",
              "term": "Disconnecting"
            }
          ],
          "related": [
            "sourceClass",
            "speedRecords",
            "icuSetup",
            "shareFromWatchApp",
            "whichWatch"
          ],
          "summary": "Connect once, then pick the sessions you want. Positions only, so speed records are uncertified.",
          "title": "Import from Strava"
        },
        {
          "body": [
            "Every watch app can export a recording as a file, and CleanJibe reads .fit files. Export the session as a FIT and pick CleanJibe from the share sheet.",
            "If it is not in the row, Save to Files and open it from there.",
            "Which format, if you are asked: FIT, every time. A FIT carries the receiver's own speed, so its records certify.",
            "A .gpx or a .tcx carries positions only, so its records are marked uncertified. Those two formats open in the CleanJibe beta.",
            "Garmin Connect's phone app has no export at all. Garmin owners have two better routes: intervals.icu, or connect.garmin.com on a computer."
          ],
          "channels": [
            "release",
            "beta",
            "dev"
          ],
          "id": "shareFromWatchApp",
          "items": [
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "No phone export. On a computer: connect.garmin.com → Activities → the activity → gear icon → Export File.",
              "term": "Garmin"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "On the phone: Calendar → tap the workout → ⋯ top right → FIT. Then Save to Files, or pick CleanJibe from the share sheet.",
              "term": "Suunto"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "On the phone: Activities → tap the activity → ⋯ top right → Export → FIT. Older versions call it Export Data. Then use the share sheet.",
              "term": "COROS"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "Not on the phone. On flow.polar.com: Diary → click the session → Export → FIT. A computer is the reliable way.",
              "term": "Polar"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "If an app can produce a FIT, CleanJibe reads it. Take it from AirDrop, Mail or Files. A ZIP of recordings works too: Import → FIT or ZIP….",
              "term": "Anything else"
            }
          ],
          "related": [
            "whichWatch",
            "icuSetup",
            "stravaImport",
            "sourceClass",
            "phoneOnly",
            "speedRecords"
          ],
          "summary": "Polar, Suunto and COROS can hand a session to CleanJibe as a file. Garmin's phone app cannot.",
          "title": "Share from your watch app straight into CleanJibe"
        },
        {
          "body": [
            "A phone records a GPS track as well as most watches do. CleanJibe reads it the same way.",
            "It is Class C · positions only. The speed is worked out from the positions.",
            "Foil time, flights, every turn verdict and clean jibe, the wind axis. Speed records are estimated from positions and marked uncertified, and there are no pump strokes or takeoff attempts.",
            "Where to put the phone: dry, still and pointing at the sky. A waterproof pouch on the upper arm or high on the chest works.",
            "A pocket at hip height spends half the session underwater. Start the recording on the beach."
          ],
          "channels": [
            "release",
            "beta",
            "dev"
          ],
          "id": "phoneOnly",
          "items": [
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "Record in the Strava app and connect Strava here. Strava's phone app cannot export a file, so the import reads the activity out of your account instead.",
              "term": "Strava, the route that needs no file"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "Anything on your phone that records a track and writes a .fit or a .gpx works. Save the track, tap Share, pick CleanJibe. Or open it from Files.",
              "term": "Any GPS-logging app that writes a file"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "FIT. CleanJibe reads a .fit in every build, and a file with the receiver's own speed certifies its records. A .gpx or a .tcx opens in the CleanJibe beta.",
              "term": "Which format, if you are offered a choice"
            }
          ],
          "related": [
            "stravaImport",
            "shareFromWatchApp",
            "whichWatch",
            "sourceClass",
            "speedRecords"
          ],
          "summary": "No watch at all. A tracker app in a pouch. The session comes in through Strava or as a file.",
          "title": "Recording with a phone only"
        },
        {
          "body": [
            "Open cleanjibe.org/app and drop a recording in. You get the session back with its flights, its turns and its speed records.",
            "It keeps a library, records and trends of its own. Any phone with a browser can read a session this way.",
            "The file is read inside the tab. Nothing is uploaded and no account is asked for."
          ],
          "channels": [
            "release",
            "beta",
            "dev"
          ],
          "id": "browserApp",
          "items": [
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "A .fit, a .gpx or a .tcx, from any watch. The browser app is not the iPhone app and has no channels.",
              "term": "What it reads"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "Where a browser offers it, the page installs. It gets an icon, opens without browser chrome and works with no signal.",
              "term": "Install it from the browser"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "Once it is installed, hold a file on the phone and pick Share, then CleanJibe. The analysis opens on it.",
              "term": "Into the share sheet"
            }
          ],
          "related": [
            "whichWatch",
            "phoneOnly",
            "shareFit",
            "privacy"
          ],
          "summary": "The same analysis in any browser. Nothing to install, no account.",
          "title": "CleanJibe in a browser"
        },
        {
          "body": [
            "CleanJibe analyses a recording, not a brand. Anything that can produce a GPS track can be read. A source that cannot answer a question leaves that number blank and says why.",
            "Two things separate the rows. **Certified speed** means the file holds the receiver's own speed. Without it, speed is worked out from positions and every record is marked uncertified.",
            "**Pump strokes and takeoff effort** need a wrist accelerometer recorded during the session, which only the CleanJibe watch apps do."
          ],
          "channels": [
            "release",
            "beta",
            "dev"
          ],
          "id": "whichWatch",
          "items": [
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "Everything: flights, turns, certified speed records, the wind axis, pump strokes, failed takeoff attempts and accelerometer-confirmed touchdowns. Sessions arrive through intervals.icu.",
              "term": "Garmin, with the CleanJibe watch app"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "Everything except pump strokes and takeoff effort. Speed records certify. Sessions come in through intervals.icu, or as a FIT from connect.garmin.com on a computer.",
              "term": "Garmin, with Garmin's own profile or another app"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "Record with Apple's Workout app and import through Strava or intervals.icu. The beta adds two doors: Apple Health, and the CleanJibe watch app, which records the wrist too.",
              "term": "Apple Watch"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "Connect the watch to intervals.icu, or export one session from the phone app as a FIT and share it in. A FIT certifies its records. A .gpx does not.",
              "term": "Polar, Suunto, COROS and the rest"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "Connect Strava and pick the sessions. Strava hands over positions, altitude and heart rate but no speed channel, so those records are uncertified.",
              "term": "Anything that ends up on Strava"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "Any GPS-logging app works: record, then import through Strava or share the file in. Positions only, so the records are uncertified. The flights, turns and map are all there.",
              "term": "A phone in a pocket, or no watch at all"
            }
          ],
          "related": [
            "shareFromWatchApp",
            "icuSetup",
            "appleWatchApp",
            "appleWorkoutApp",
            "stravaImport",
            "phoneOnly",
            "sourceClass",
            "speedRecords"
          ],
          "summary": "All of them, one way or another. Each row says what that one costs you.",
          "title": "Which watches work with CleanJibe"
        },
        {
          "body": [
            "Every failure CleanJibe can see is reported as a cause, because the fix differs. A rejected key is your key. An empty list is usually Garmin not connected yet. A network error is neither."
          ],
          "channels": [
            "release",
            "beta",
            "dev"
          ],
          "id": "icuTroubleshooting",
          "items": [
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "A 401: the key is wrong or was regenerated after you pasted it. Copy it again from Settings → Developer Settings. A stray space at either end breaks it.",
              "term": "\"intervals.icu rejected the API key\""
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "Either Garmin is not connected in intervals.icu yet, or none of your activities is a watersport. CleanJibe pulls Windsurf, Kitesurf, Sail, Surfing, SUP and anything named wing or foil.",
              "term": "The sync succeeds but the list stays empty"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "A network problem rather than a key problem: nothing was lost and nothing was half-imported. Check your connection and sync again.",
              "term": "\"Could not reach intervals.icu\""
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "The sync looks two years back and skips what the library already holds. For more, use Import → FIT or ZIP… with the Garmin export ZIP.",
              "term": "Older sessions are missing"
            }
          ],
          "related": [
            "icuSetup",
            "icuPrivacy"
          ],
          "summary": "The four things that actually go wrong, and the fix for each.",
          "title": "When the sync does not work"
        },
        {
          "body": [
            "Your API key is stored in this iPhone's Keychain. It is never copied to iCloud and never written to a log. There is no CleanJibe server to send it to. It goes to intervals.icu itself, over HTTPS, and nowhere else.",
            "The key is a personal read/write token for your intervals.icu account, so treat it like a password. Clear the field in Settings to remove it, or regenerate it in Developer Settings. The old key stops working the moment you do."
          ],
          "channels": [
            "release",
            "beta",
            "dev"
          ],
          "id": "icuPrivacy",
          "items": [],
          "related": [
            "icuSetup",
            "icuTroubleshooting",
            "privacy"
          ],
          "summary": "In the iOS Keychain, on this phone, and sent only to intervals.icu.",
          "title": "Where your API key is kept"
        },
        {
          "body": [
            "There is no CleanJibe account and no CleanJibe server. A session you import is analysed on this phone and stays on it. No advertising, no analytics, no tracking of any kind.",
            "Four places can be reached, each only if you choose it. Your own credential goes to intervals.icu and Strava. Apple Maps loads while a map is on screen. One rounded coordinate per new spot looks up its name.",
            "CleanJibe never asks for your location. Every coordinate it draws was already inside a file you imported."
          ],
          "channels": [
            "release",
            "beta",
            "dev"
          ],
          "id": "privacy",
          "items": [],
          "related": [
            "icuPrivacy",
            "shareFit",
            "libraryBackup"
          ],
          "summary": "No account, no server, nothing uploaded. The whole policy is on the web.",
          "title": "What leaves your phone"
        },
        {
          "body": [
            "Setting up a new iPhone from this one carries your library across, and so does an iCloud backup.",
            "Settings → Library backup is for the case neither covers. That is a phone set up as new, or the app deleted and installed again.",
            "The file holds every recording you imported, and what nothing else can bring back. That is each session's name and caption, whose it was, its gear. Your spot names and the sessions you deleted on purpose are there too.",
            "Restoring is additive. Sessions already in your library keep their own analysis. Details you changed since are left alone. Restoring the same file twice does nothing the second time. Sessions you deleted after the backup stay deleted."
          ],
          "channels": [
            "release",
            "beta",
            "dev"
          ],
          "id": "libraryBackup",
          "items": [
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "Back up library writes a temporary file. Save… puts it in Files, iCloud Drive or on a Mac. CleanJibe keeps no copy.",
              "term": "Save the file yourself"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "The .fit and .gpx files inside are the originals. Nothing is removed. A session you send a friend is stripped first. This file is for you, not for sharing.",
              "term": "Your own recordings, nothing stripped"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "A session recorded with the CleanJibe watch app carries a 100 Hz accelerometer stream, about 95 % of its size. The app estimates the total before it starts.",
              "term": "How big it will be"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "A backup from a newer version of CleanJibe is refused rather than partly read: update the app and try again. An older one is brought up to date.",
              "term": "A newer backup"
            }
          ],
          "related": [
            "icuSetup",
            "riderAttribution",
            "shareFit",
            "icuPrivacy"
          ],
          "summary": "A new phone carries everything by itself. A fresh start needs a file.",
          "title": "Backing up your library"
        },
        {
          "body": [
            "One mail carries all of it. Name a missing column, a word that reads wrong, or something you would rather the app did differently.",
            "Menu → Support & ideas opens the mail. So do \"Something off, or an idea? Send feedback\" at the foot of every page and \"Report a problem with this session…\" in the share sheet.",
            "The mail asks three questions, with a blank line under each.",
            "Nothing leaves the phone until you tap Send. It is Apple's own composer, and the address is info@cleanjibe.org. No part of CleanJibe sends anything by itself. There is no CleanJibe server to send it to."
          ],
          "channels": [
            "release",
            "beta",
            "dev"
          ],
          "id": "sendingFeedback",
          "items": [
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "Under a line of dashes: app and engine version, tuned thresholds, your phone, iOS and locale. The paired watch is there, with how many sessions came in by which door.",
              "term": "What is already in the mail"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "It also carries that session's date, spot, discipline, duration, source class, engine stamp and identifier, with its share card attached.",
              "term": "From a session"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "Every line is there to read and to edit. If this phone has no mail account, the app hands the same text to whatever you do use.",
              "term": "Read it before you send"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "A screenshot taken inside the app offers Send Beta Feedback. That attaches the screenshot and the device logs. Take it for a crash.",
              "term": "If you are on the beta"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "Anything about the watch app can go through its Connect IQ store listing. For a number that looks wrong, the mail here is the one worth sending.",
              "term": "About the watch app itself"
            }
          ],
          "related": [
            "sourceClass",
            "engineVersion",
            "divergence"
          ],
          "summary": "The app fills in build, phone and session. You write the sentence. Ideas and wishes are as welcome as bugs.",
          "title": "Sending feedback"
        }
      ]
    },
    {
      "id": "foil",
      "title": "On the foil",
      "topics": [
        {
          "body": [
            "A flight starts when your speed holds above the entry threshold, 12 km/h by default, for 2 seconds. It ends when the speed drops below the exit threshold, 8 km/h, for 3 seconds.",
            "Start and end are backdated to the first qualifying sample.",
            "\"On foil\" is that flying time divided by timer time. Timer time is the total, minus any stretch where the recording stopped or the GPS dropped out.",
            "Taxiing, swimming and the drift upwind count against it. A gap in the recording does not.",
            "Anything under 5 seconds is not counted as a flight. \"Foil time\" is the number of minutes. \"On foil\" is the share of the session they are."
          ],
          "channels": [
            "release",
            "beta",
            "dev"
          ],
          "id": "foilPct",
          "items": [],
          "related": [
            "flights",
            "longestFlight",
            "sourceClass"
          ],
          "summary": "How much of the session you spent actually flying.",
          "title": "Foil time / foil %"
        },
        {
          "body": [
            "One flight is one continuous stretch above the entry threshold, lasting at least 5 seconds.",
            "A brief touchdown does not split a flight. The exit needs 3 seconds below the exit speed. A one- or two-second tap of the water stays inside it.",
            "The flight count answers \"how many times did I have to get up again\". The touchdown count answers \"how clean was it\"."
          ],
          "channels": [
            "release",
            "beta",
            "dev"
          ],
          "id": "flights",
          "items": [],
          "related": [
            "foilPct",
            "touchdowns",
            "takeoffAttempts"
          ],
          "summary": "How many separate times you got up and stayed up.",
          "title": "Flights"
        },
        {
          "body": [
            "The longest flight by duration, with the distance covered during it shown underneath.",
            "Both come from the same segmentation as foil %. So a session with many short flights and a session with one long one can share a foil %."
          ],
          "channels": [
            "release",
            "beta",
            "dev"
          ],
          "id": "longestFlight",
          "items": [],
          "related": [
            "foilPct",
            "flights"
          ],
          "summary": "Your best single stretch, in time and in distance.",
          "title": "Longest flight"
        },
        {
          "body": [
            "Distance is integrated from the device's Doppler speed rather than summed from GPS positions. Position noise inflates a distance total badly at low speed. Doppler does not.",
            "It covers the whole session: flying, taxiing and drifting."
          ],
          "channels": [
            "release",
            "beta",
            "dev"
          ],
          "id": "distance",
          "items": [],
          "related": [
            "sourceClass"
          ],
          "summary": "Distance over the water, integrated from the speed channel.",
          "title": "Distance"
        },
        {
          "body": [
            "Every chip under the map is a switch. Tapping one hides that category on the map and in the speed chart at once. The two are one reading of the same session.",
            "A hidden chip stays in place, struck through, and \"show all\" brings everything back. A category this session has none of is not a switch. The three rows are the track, the events on it, and the map's own controls.",
            "Tap the track to move the replay playhead. Tap a mark, or a flown stretch, for its own facts."
          ],
          "channels": [
            "release",
            "beta",
            "dev"
          ],
          "id": "mapLegend",
          "items": [
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "Tinted by phase: teal where you were flying, grey where you were not. Small chevrons along it point the way you were riding.",
              "term": "The track"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "Verdicts on one ladder: green flew through, orange touched down, red fell in. Grey is a course change and no verdict at all.",
              "term": "The dots"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "Fill carries the channel rather than a second colour. Solid is a maneuver's outcome. Hollow is a straight-line flight end that no turn explains.",
              "term": "Solid or hollow"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "A clean jibe, in a green of its own, taking the place of that jibe's dot. It needs both its chips: hide the outcome and the star goes with it.",
              "term": "A star"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "Takeoffs: an up-arrow got you up, a red u-turn is an attempt that did not. One chip hides both halves.",
              "term": "Arrows, not dots"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "The indigo bands are pump bursts. The cyan drop is the barometer seeing your wrist go under.",
              "term": "Bands and drops"
            }
          ],
          "related": [
            "foilPct",
            "turnOutcomes",
            "takeoffAttempts"
          ],
          "summary": "What the chips, the colours, the arrows and the dots mean.",
          "title": "Reading the map"
        }
      ]
    },
    {
      "id": "records",
      "title": "Speed records",
      "topics": [
        {
          "body": [
            "The set is fixed, so a number here means the same thing as the same number posted anywhere else. That is the six windows below, plus 100 m, 250 m and your best hour.",
            "All are computed on the device's Doppler speed, with fractional samples interpolated at the window edges. So the result does not depend on whether your watch recorded at 1 Hz or 4 Hz. No minimum-speed filter is applied.",
            "A window never spans a recording gap. Tap a record card to see where on the track and on the speed trace it happened.",
            "A record certifies only when the recording holds the receiver's own speed channel. The rest are marked uncertified."
          ],
          "channels": [
            "release",
            "beta",
            "dev"
          ],
          "id": "speedRecords",
          "items": [
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "Your peak speed, averaged over 2 seconds. A single-sample maximum is noise. 2 seconds is a real burst, and the number most riders compare.",
              "term": "Best 2 s"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "The fastest 10-second run, a burst you had to hold. Luck and a single gust cannot carry it, so it usually sits 1 to 3 knots below your 2 s.",
              "term": "Best 10 s"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "The mean of your best five separate 10-second runs. They may not overlap, so one lucky reach cannot carry it.",
              "term": "Best 5×10 s"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "Your fastest half-kilometre, measured on integrated Doppler distance rather than straight-line distance. A curved run still counts, and cutting the corner flatters nothing.",
              "term": "Best 500 m"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "Your fastest nautical mile, 1852 m. On most spots it needs more than one leg, so it measures how well you keep speed through your turns.",
              "term": "Best 1 NM"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "Your fastest 500 m that ends within 50 m of where it started. It contains a jibe, so it measures the turn as well as the speed.",
              "term": "Alpha 500"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "CleanJibe shows knots. The watch app has its own switch, under Garmin Connect → CleanJibe → Settings. Garmin Connect follows its own setting. Strava shows a windsurf session in knots.",
              "term": "Knots or km/h"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "A recording with positions but no speed channel has its speed differentiated from them, which reads high. Every GPX is one, and some converted exports. Shown, never a personal best.",
              "term": "\"Uncertified\""
            }
          ],
          "related": [
            "sourceClass",
            "turnOutcomes",
            "divergence"
          ],
          "summary": "Your fastest 2 seconds, 10 seconds, 500 m and nautical mile. The speedsurfing world uses the same windows.",
          "title": "Speed records"
        }
      ]
    },
    {
      "id": "turns",
      "title": "Turns & losses",
      "topics": [
        {
          "body": [
            "A turn is detected from your course. It needs at least 60° of net heading change within 8 seconds, with a peak rate of 25°/s. You must be on the foil, or within 3 s of it.",
            "It must also carve a real arc. That means at least 12 m of path, at an effective radius of at least 6 m. A rider spinning around beside the board carves no arc.",
            "What kind of turn it was depends on the wind axis:"
          ],
          "channels": [
            "release",
            "beta",
            "dev"
          ],
          "id": "turnTypes",
          "items": [
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "Your course crosses the wind axis through downwind.",
              "term": "Jibe"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "Your course crosses the wind axis through upwind.",
              "term": "Tack"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "A real course change that never crosses the axis. Counted separately and left out of the tack and jibe tallies. It is not a maneuver you either made or blew.",
              "term": "Bear-away / round-up"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "A detected maneuver on a session where the wind axis was too uncertain to name it. Still counted, just unnamed.",
              "term": "Turn"
            }
          ],
          "related": [
            "windAxis",
            "turnOutcomes",
            "portStarboard"
          ],
          "summary": "What counts as a maneuver, and what is just a change of direction.",
          "title": "Tacks, jibes and course changes"
        },
        {
          "body": [
            "Every turn gets one of three outcomes. The judgement runs from the turn start until you are flying again. That means speed back above 70 % of your entry speed for 2 seconds. The window is capped at 12 seconds.",
            "A jibe exited at marginal speed can bleed off for 6 to 12 seconds before the foil stalls. That mush-out is the jibe's fault. A jibe you power out of closes its window in a second or two.",
            "Three channels are read inside it. Speed always. The barometer, where a wrist under water reads as a huge altitude drop. The accelerometer, on a CleanJibe watch recording."
          ],
          "channels": [
            "release",
            "beta",
            "dev"
          ],
          "id": "turnOutcomes",
          "items": [
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "You never left the foil. No sample in the window is off-foil.",
              "term": "Flew through"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "You lost the foil but not the session: you stopped for 3 s or less, or pumped it back up. Borderline between 3 s and 5 s.",
              "term": "Touchdown"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "You stopped for more than 5 s, or the barometer says your wrist went under.",
              "term": "Fell in"
            }
          ],
          "related": [
            "turnSuccess",
            "falls",
            "glideOuts"
          ],
          "summary": "What actually happened to the foil in the turn.",
          "title": "Turn outcomes: flew through, touchdown, fell in"
        },
        {
          "body": [
            "A turn that **flew through** never lost the foil, from its start until you were flying again. A **clean** jibe flew through, held its speed, and stayed quiet after.",
            "Holding the speed: your minimum speed through the turn stays at or above 70 % of your entry speed. You never drop below the foil exit speed.",
            "Staying quiet means the 10 seconds after the turn. They hold no touchdown or fall, no second or more off the foil, and no wrist under water.",
            "So clean is a strict subset of flew through. A jibe that held its speed and then lost the foil coming out is not clean."
          ],
          "channels": [
            "release",
            "beta",
            "dev"
          ],
          "id": "turnSuccess",
          "items": [
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "The outcome: you kept the foil through the turn and through the recovery out of it. No touchdown, no swim.",
              "term": "Flew through"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "A jibe that flew through, held at least 70 % of its entry speed, and stayed quiet for 10 seconds. The jibe CPH counts.",
              "term": "Clean"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "A tack has no clean reading to carry, so the Tacks card reports only how its tacks ended.",
              "term": "Jibes only"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "You did not fall in. A touchdown still counts as dry. JPH counts dry jibes per hour, so it never sits below CPH.",
              "term": "Dry"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "The share of your entry speed you held through the turn, 0 to 100. The evidence behind \"clean\", printed beside every turn.",
              "term": "Score"
            }
          ],
          "related": [
            "turnOutcomes",
            "speedRecords"
          ],
          "summary": "A jibe you fly all the way through without losing much speed. The 10 seconds after it stay quiet too.",
          "title": "Clean jibes"
        },
        {
          "body": [
            "The side is read from your wind angle before the turn. A 50/50 split means you work both sides equally. A lopsided split is the tack you quietly stop choosing, and usually the one worth practising.",
            "The Trends screen plots this over time as \"% port\", with 50 % marked."
          ],
          "channels": [
            "release",
            "beta",
            "dev"
          ],
          "id": "portStarboard",
          "items": [],
          "related": [
            "turnTypes",
            "windAxis"
          ],
          "summary": "Which tack you were on going in, and which side you avoid.",
          "title": "Port / starboard"
        },
        {
          "body": [
            "A fall means you stopped for more than 5 seconds, or the barometer caught your wrist going under.",
            "The split matters. Falls in turns are a maneuver problem. Falls in a straight line are a gust, a ventilation or a tip catching. Each fall is counted once. A fall inside a turn's window belongs to that turn."
          ],
          "channels": [
            "release",
            "beta",
            "dev"
          ],
          "id": "falls",
          "items": [],
          "related": [
            "turnOutcomes",
            "touchdowns",
            "glideOuts"
          ],
          "summary": "Every fall, split into the ones in turns and the ones in a straight line.",
          "title": "Falls"
        },
        {
          "body": [
            "You came off the foil but were making way again within a few seconds, or you pumped straight back up. A short touchdown inside a flight does not break the flight."
          ],
          "channels": [
            "release",
            "beta",
            "dev"
          ],
          "id": "touchdowns",
          "items": [],
          "related": [
            "turnOutcomes",
            "falls",
            "flights"
          ],
          "summary": "Brief losses of the foil, in turns and in a straight line.",
          "title": "Touchdowns"
        },
        {
          "body": [
            "The flight ended and you kept moving. You settled onto the board and taxied on, or you chose to stop riding. No stop was ever measured, so this is not counted as a loss.",
            "Flight ends where the recording itself stopped are reported as unknown. There is no evidence there, so they are left out of every tally."
          ],
          "channels": [
            "release",
            "beta",
            "dev"
          ],
          "id": "glideOuts",
          "items": [],
          "related": [
            "falls",
            "touchdowns",
            "sourceClass"
          ],
          "summary": "Flights that ended without ever stopping.",
          "title": "Glide-outs"
        }
      ]
    },
    {
      "id": "takeoff",
      "title": "Takeoff & pumping",
      "topics": [
        {
          "body": [
            "Attempts = flights + failed attempts. A pumping burst counts as a failed attempt when no flight starts within 10 seconds of your last stroke. Bursts closer together than that are chained into one attempt.",
            "Flights alone cannot show this. Getting up 20 times out of 22 looks like getting up 20 out of 40.",
            "It needs the wrist accelerometer, which only the CleanJibe watch app records. Without it your failures are invisible, so the success rate is shown as unknown rather than a flattering 100 %."
          ],
          "channels": [
            "release",
            "beta",
            "dev"
          ],
          "id": "takeoffAttempts",
          "items": [],
          "related": [
            "pumpsToTakeoff",
            "sourceClass",
            "heartRate"
          ],
          "summary": "How often you pumped, including the times you did not get up.",
          "title": "Attempts & success rate"
        },
        {
          "body": [
            "The takeoff run starts at the rising speed before the flight. It starts at the pump burst that led into it, if that came first. So the count is the strokes of the effort that produced the flight.",
            "Takeoffs under 3 strokes are counted as free: you got up on the wind alone. That is a fact about the conditions, so free takeoffs are kept out of the averages and reported separately.",
            "Runs the recording cut short are left out of the averages. They still count as takeoffs that worked: the flight happened, only its cost is unknown."
          ],
          "channels": [
            "release",
            "beta",
            "dev"
          ],
          "id": "pumpsToTakeoff",
          "items": [],
          "related": [
            "takeoffAttempts",
            "pumpStrokes",
            "heartRate"
          ],
          "summary": "How many strokes each flight cost you.",
          "title": "Pumps to takeoff"
        },
        {
          "body": [
            "Strokes are detected from the wrist accelerometer, using the magnitude only. How your wrist was rotated does not matter.",
            "In-flight strokes hold or extend a glide rather than get you up. That is different work, so they are counted separately."
          ],
          "channels": [
            "release",
            "beta",
            "dev"
          ],
          "id": "pumpStrokes",
          "items": [],
          "related": [
            "pumpsToTakeoff",
            "sourceClass"
          ],
          "summary": "Every stroke in the session, and the ones you did in flight.",
          "title": "Pump strokes"
        }
      ]
    },
    {
      "id": "effort",
      "title": "Effort",
      "topics": [
        {
          "body": [
            "HR cost is the rise from your baseline just before an effort to the peak that follows. The baseline is the median of the 10 seconds ending at the start of the takeoff run.",
            "The peak is searched 30 seconds forward, because an optical wrist sensor trails effort by 10 to 20 seconds. Negative values are reported rather than hidden: \"still recovering when you started\" is a different fact from \"this cost nothing\".",
            "The card does not appear on a session whose recording has no usable heart rate. Nothing here is estimated when the sensor was silent."
          ],
          "channels": [
            "release",
            "beta",
            "dev"
          ],
          "id": "heartRate",
          "items": [
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "The share of a window covered by unstuck samples between 30 and 220 bpm, no more than 10 seconds apart. Below 60 % coverage no number is produced.",
              "term": "Coverage"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "A wrist sensor under a wetsuit sleeve in cold water drops out and sticks. A made-up average is worse than a missing one.",
              "term": "Why it drops out"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "20-minute bins, each showing what its takeoffs cost, with the share of attempts that got up underneath. Bins with nothing usable are shaded, not drawn as zero.",
              "term": "The fatigue chart"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "A rise measured against a baseline that has drifted upward gets smaller as you tire. A shrinking late cost is not evidence that the takeoffs got easier.",
              "term": "Read the cost bars with the baseline note"
            }
          ],
          "related": [
            "takeoffAttempts",
            "pumpsToTakeoff",
            "sourceClass"
          ],
          "summary": "What an attempt costs in heartbeats, and when that can be trusted.",
          "title": "Heart rate: cost and coverage"
        }
      ]
    },
    {
      "id": "conditions",
      "title": "Conditions",
      "topics": [
        {
          "body": [
            "No weather station is involved. The estimate comes from your own track. Your foiling course headings are collected into a weighted histogram. The two dominant reaching directions are found. The wind axis is the line that bisects them.",
            "That gives an axis but not a side. The tie is broken by the no-go zone. Of the two ends, the wind came from the one you sailed almost nothing within ±45° of.",
            "Confidence combines how cleanly the two reaches separate with how decisive the no-go zone was. Below 50 % the axis is still shown, but your turns stay unnamed \"turns\" rather than tacks and jibes.",
            "A wind direction you set on the watch always wins."
          ],
          "channels": [
            "release",
            "beta",
            "dev"
          ],
          "id": "windAxis",
          "items": [],
          "related": [
            "turnTypes",
            "portStarboard"
          ],
          "summary": "The wind direction estimated from how you actually sailed.",
          "title": "Wind axis & confidence"
        }
      ]
    },
    {
      "id": "sharing",
      "title": "Sharing",
      "topics": [
        {
          "body": [
            "Any session becomes a card. It holds the track, the numbers that matter, and where the analysis came from. Pick portrait, square or landscape, and Complete or Lean. A photo from your library can go behind it.",
            "Or turn on the map background and the track is drawn over the water you sailed. That one needs a connection. Without one the card comes out plain.",
            "The card is made on your phone and goes nowhere until you send it."
          ],
          "channels": [
            "release",
            "beta",
            "dev"
          ],
          "id": "shareCard",
          "items": [],
          "related": [
            "replayClip",
            "shareFit"
          ],
          "summary": "One picture of a session, made to post.",
          "title": "Share cards"
        },
        {
          "body": [
            "The replay plays a session back on its own track, with a commentary that follows what is happening. Scrub to the part worth watching, then record it as a video.",
            "Ask for a 10, 25 or 60-second clip. The app solves the playback rate to land on it. Or take \"full detail\" and let the session run as long as it runs.",
            "The frame is yours too. Take 9:16 for a story, 1:1 for a post, 16:9 for a chat, or the whole screen. Photos from that afternoon can be spliced in.",
            "You can lay your own music under it, trimmed or looped and faded at both ends. Nothing is uploaded: the video is rendered on the phone."
          ],
          "channels": [
            "release",
            "beta",
            "dev"
          ],
          "id": "replayClip",
          "items": [],
          "related": [
            "shareCard",
            "mapLegend"
          ],
          "summary": "Record the replay as a video.",
          "title": "Replay clips"
        },
        {
          "body": [
            "You can share the original .fit file of any session. The watch serial, your rider profile and your lifetime totals are removed first. The ride itself is untouched, so the analysis your friend gets is identical to yours.",
            "They can open it in CleanJibe, or drop it into the free browser analyzer at cleanjibe.org without installing anything."
          ],
          "channels": [
            "release",
            "beta",
            "dev"
          ],
          "id": "shareFit",
          "items": [],
          "related": [
            "riderAttribution",
            "shareCard"
          ],
          "summary": "Share the original recording, stripped of anything identifying.",
          "title": "Sending a session to a friend"
        },
        {
          "body": [
            "When you import a file, CleanJibe asks whose session it is. A friend's session is saved and shown in full: map, replay, every turn. It stays out of your records, trends and gear totals.",
            "Their fast run never becomes your personal best. The name you give is stored on your phone only."
          ],
          "channels": [
            "release",
            "beta",
            "dev"
          ],
          "id": "riderAttribution",
          "items": [],
          "related": [
            "shareFit",
            "exampleSession"
          ],
          "summary": "A friend's session is shown in full but kept out of your records.",
          "title": "Sessions someone else rode"
        }
      ]
    },
    {
      "id": "quality",
      "title": "Where the numbers come from",
      "topics": [
        {
          "body": [
            "CleanJibe reads whatever your watch put in the file, and every metric degrades gracefully rather than failing or guessing. There are four cases, with the names cleanjibe.org and the Import screen print.",
            "A GPX never carries a speed channel, and a TCX sometimes does. Strava hands over positions and no speed channel, so a Strava import belongs in the last row."
          ],
          "channels": [
            "release",
            "beta",
            "dev"
          ],
          "id": "sourceClass",
          "items": [
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "Everything. Foil time, flights, every turn verdict and clean jibe, certified speed records, the wind axis. Pump strokes and takeoff attempts too.",
              "term": "Class A · Garmin watch app"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "Everything except pump strokes and takeoff attempts, which need a wrist accelerometer nothing else records. Speed records certify. Garmin's own profile, another Connect IQ app, Apple's Workout app.",
              "term": "Class B · any speed-certified file"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "Everything class B gets, plus pump strokes and takeoff attempts. The watch app records the wrist at 50 Hz. The phone analyses it.",
              "term": "Class B+ · Apple Watch app"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "Foil time, flights, every turn verdict and clean jibe, the wind axis. Speed records are estimated from positions and marked uncertified, and there are no pump strokes or takeoff attempts.",
              "term": "Class C · positions only"
            }
          ],
          "related": [
            "speedRecords",
            "divergence",
            "engineVersion",
            "whichWatch",
            "stravaImport",
            "phoneOnly"
          ],
          "summary": "Everything works from any Garmin recording. Two things need the CleanJibe watch app.",
          "title": "What your recording can and cannot show"
        },
        {
          "body": [
            "A session from the CleanJibe watch app carries the summary the watch computed live. It was computed in one forward pass with no memory to spare. The phone recomputes the same session properly, and the two are compared.",
            "The banner appears when foil time differs by more than 5 %. It appears for a speed record off by more than 0.3 knots. It appears for a flight, turn or attempt count off by more than one.",
            "The phone's number is the authoritative one. Nothing is wrong with your session. The banner says the watch's live approximation needs tuning."
          ],
          "channels": [
            "release",
            "beta",
            "dev"
          ],
          "id": "divergence",
          "items": [],
          "related": [
            "sourceClass",
            "engineVersion"
          ],
          "summary": "Normal, expected, and the phone's number is the right one.",
          "title": "When the watch and the phone show different numbers"
        },
        {
          "body": [
            "The footer of a session shows which version of the analysis engine produced its numbers.",
            "Sessions computed with an older version are recomputed when the engine changes results. The recompute reads each session's archived original file the next time you open it.",
            "The original recording is never modified. Only the derived analysis is, and you can drop and rebuild it at any time from Settings."
          ],
          "channels": [
            "release",
            "beta",
            "dev"
          ],
          "id": "engineVersion",
          "items": [],
          "related": [
            "sourceClass",
            "divergence"
          ],
          "summary": "Every session is re-derived when the engine changes.",
          "title": "Analysis engine version"
        },
        {
          "body": [
            "A session can be analysed as **Wingfoil**, **Windsurf foil** or **Windsurf fin**. The row is on the session's Details tab, under \"Analyse as\". Changing it re-derives that session and nothing else.",
            "None of Garmin, Strava, intervals.icu and Apple Health has a wingfoil sport. Most riders record under the windsurf profile. A new session cannot say which rig it was ridden on.",
            "So it is read as whatever you set under Settings → \"I mostly ride\", marked with a **?** until you have looked, and listed after each import. Sessions from the CleanJibe watch app are never asked about."
          ],
          "channels": [
            "dev"
          ],
          "id": "windsurf",
          "items": [
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "Jibes and tacks are the same detector, the same thresholds and the same three verdicts. So are the speed records, the wind axis, the wrist-under marks and the map.",
              "term": "What works"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "Pumping. With no wing to load, pump chips, stroke counts, pumps-to-takeoff and the heart-rate cost are **absent rather than zero**. A takeoff becomes a planing start.",
              "term": "What is off"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "The wingfoil reading with pumping switched off. Every speed and every threshold is the same, because a foil flies the same way under either rig.",
              "term": "Windsurf foil"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "Also moves the two speeds that decide when you are going. 20 km/h starts planing and 15 km/h stops it, against 12 and 8 on a foil.",
              "term": "Windsurf fin"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "A first guess, not a reading off real fin sessions. There are none in the corpus yet. If your planing time looks wrong, report that number.",
              "term": "Those two speeds are provisional"
            },
            {
              "channels": [
                "release",
                "beta",
                "dev"
              ],
              "detail": "\"Foil time\" reads as planing time and \"lost the foil\" as stopped planing. Windsurf sessions count towards your trends. There is no separate record set.",
              "term": "In the library"
            }
          ],
          "related": [
            "foilPct",
            "turnOutcomes",
            "pumpsToTakeoff",
            "engineVersion"
          ],
          "summary": "The same engine without the wing. The planing speeds are a guess.",
          "title": "Windsurf (experimental)"
        }
      ]
    }
  ]
};

/** The feedback door, word for word (docs/copy/feedback.json). */
export const FEEDBACK = {
  "doors": {
    "app": "Menu → Support & ideas",
    "footer": "Something off, or an idea? Send feedback",
    "share": "Report a problem with this session…",
    "testflight": "Send Beta Feedback",
    "web": "info@cleanjibe.org"
  },
  "invitation": "Ideas and wishes are as welcome as bugs.",
  "prompts": [
    "What happened, or what you would like:",
    "What you expected instead:",
    "Which session, its date and spot, if it is about one:"
  ],
  "subjectPrefix": "CleanJibe feedback"
};
