/* GENERATED by web/tools/make_copy_js.py from docs/copy/ — do not edit.
 *
 * The rider-facing sentences this site has to say at run time. docs/copy/README.md holds
 * the contract: the kit is the author, the JSON is the artefact, and both sides are pinned
 * — `CopyContractTests` on the Swift side, `web/tools/verify_copy.py` on the pages and
 * `make_copy_js.py --check` (run by verify_links.py) on this file.
 *
 * Regenerate after a deliberate wording change:
 *
 *     cd ios/WingFoilKit && COPY_WRITE=1 swift test --filter CopyContractTests
 *     python3 web/tools/make_copy_js.py
 */

/**
 * What the rider is told about a recording that is not a session — the kit's
 * `NotASessionNote` (docs/copy/verdicts.json).
 *
 * `lines[0]` is the no-recording case, which the analyzer cannot reach: it only
 * ever sees a file somebody dropped on it. `lines[1]` is the short /
 * went-nowhere case, and carries `{duration}` (m:ss under an hour, h:mm:ss over
 * it) and `{distance}` (metres under a kilometre, otherwise one decimal of km) —
 * the row's own displayed numbers, so the line reads against the key metrics
 * directly above it.
 */
export const NOT_A_SESSION = {
  "lines": [
    "Your watch says this afternoon happened, but its recording has not arrived yet. It is not counted in totals, trends or records until it does.",
    "No time on the foil, {duration} long and {distance} covered. This looks like a recording rather than a session. It is kept, and left out of totals, trends and records."
  ],
  "tag": "No riding detected"
};

/** The three sentences the product says about itself (docs/copy/phrases.json). */
export const PHRASES = {
  "promise": "Did you fly through that jibe? CleanJibe reads your session off the watch. It tells you your time on the foil, every flight, your speed records, and a verdict on every turn. Flew through, touchdown, or fell in.",
  "callToAction": "analyze your wingfoil sessions free — cleanjibe.org",
  "captionOffer": "analysed with CleanJibe, free at cleanjibe.org"
};

/**
 * The words the product is made of, one line each — the kit's `MetricGlossary`
 * (docs/copy/glossary.json), which /learn/'s definition list carries and the
 * analyzer's `?` beside the key-metrics block opens.
 *
 * `id` is a slug that outlives a rewording, so it is what a caller keys on.
 * `short` is the same word at the watch's width and `expansion` is what follows
 * it after a middot where a rate is printed in full — the two lengths a
 * presentation-document cell picks between (js/presentation.js). Entries carry
 * other fields in the JSON; only these five are copied here.
 */
export const GLOSSARY = [
  {
    "id": "foilShare",
    "term": "On foil",
    "short": "on foil",
    "expansion": "",
    "line": "How much of your session you spent flying rather than just moving."
  },
  {
    "id": "flights",
    "term": "Flights & touchdowns",
    "short": "flights",
    "expansion": "",
    "line": "One takeoff starts a flight. A touchdown or a fall ends it. Both are counted."
  },
  {
    "id": "turnVerdicts",
    "term": "Turn verdicts",
    "short": "verdict",
    "expansion": "",
    "line": "Every turn gets one: flew through, touchdown, or fell in."
  },
  {
    "id": "dryStreak",
    "term": "Dry streak",
    "short": "dry",
    "expansion": "",
    "line": "How many jibes in a row you stayed out of the water, and the best run of the day."
  },
  {
    "id": "jph",
    "term": "JPH",
    "short": "JPH",
    "expansion": "dry jibes per hour",
    "line": "Dry jibes per hour. Falling in more often cannot raise it."
  },
  {
    "id": "cph",
    "term": "CPH",
    "short": "CPH",
    "expansion": "clean jibes per hour",
    "line": "Clean jibes per hour. Clean: flew through, held your speed, and 10 quiet seconds after."
  },
  {
    "id": "tph",
    "term": "TPH",
    "short": "TPH",
    "expansion": "turns per hour",
    "line": "Dry turns per hour, tacks and jibes together. It takes the place of JPH once a session has tacks in it."
  },
  {
    "id": "wph",
    "term": "WPH",
    "short": "WPH",
    "expansion": "swims per hour",
    "line": "Swims per hour. Nobody wants it high, and it counts every fall."
  },
  {
    "id": "speedRecords",
    "term": "Speed records",
    "short": "best",
    "expansion": "",
    "line": "Your fastest 2 seconds, 10 seconds, 500 m and nautical mile. The speedsurfing world uses the same windows."
  },
  {
    "id": "best5x10s",
    "term": "Best 5×10 s",
    "short": "5×10 s",
    "expansion": "",
    "line": "The mean of your best five separate 10-second runs. They may not overlap, so one lucky reach cannot carry it."
  },
  {
    "id": "alpha500",
    "term": "Alpha 500",
    "short": "alpha",
    "expansion": "",
    "line": "Your fastest 500 m that ends within 50 m of where it started. It contains a jibe, so it measures the turn as well as the speed."
  },
  {
    "id": "flewThrough",
    "term": "Flew through",
    "short": "flew",
    "expansion": "",
    "line": "The turn kept the foil, from the sweep until you were flying again."
  },
  {
    "id": "clean",
    "term": "Clean",
    "short": "clean",
    "expansion": "",
    "line": "A jibe that flew through, held 70 % of its entry speed, and stayed quiet for 10 s."
  },
  {
    "id": "speedKept",
    "term": "Speed kept",
    "short": "speed",
    "expansion": "",
    "line": "The share of counted turns that held 70 % of their entry speed and never dropped off the foil."
  },
  {
    "id": "dry",
    "term": "Dry",
    "short": "dry",
    "expansion": "",
    "line": "You did not fall in. A touchdown still counts as dry."
  },
  {
    "id": "touchdown",
    "term": "Touchdown",
    "short": "touch",
    "expansion": "",
    "line": "The foil went in and you kept going. Dry, and not clean."
  },
  {
    "id": "fellIn",
    "term": "Fell in",
    "short": "fell in",
    "expansion": "",
    "line": "Every time you ended up in the water, in a turn or in a straight line."
  },
  {
    "id": "takeoffs",
    "term": "Takeoffs",
    "short": "up",
    "expansion": "",
    "line": "How many times you got up on the foil. One takeoff starts every flight."
  },
  {
    "id": "takeoffAttempts",
    "term": "Attempts",
    "short": "tries",
    "expansion": "",
    "line": "Every pumping burst, whether you got up or not. Attempts are takeoffs plus failed attempts."
  }
];
