/* GENERATED by web/tools/make_copy_js.py from docs/copy/ — do not edit.
 *
 * The rider-facing sentences this site has to say at run time. docs/copy/README.md holds
 * the contract: the kit is the author, the JSON is the artefact, and both sides are pinned
 * — `CopyContractTests` on the Swift side, `web/tools/verify_copy.py` on the pages and
 * `make_copy_js.py --check` (run by verify_links.py) on this file.
 *
 * Regenerate after a deliberate wording change:
 *
 *     cd ios/WingFoilKit && COPY_WRITE=1 swift test --filter CopyContractTests
 *     python3 web/tools/make_copy_js.py
 */

/**
 * What the rider is told about a recording that is not a session — the kit's
 * `NotASessionNote` (docs/copy/verdicts.json).
 *
 * `lines[0]` is the no-recording case, which the analyzer cannot reach: it only
 * ever sees a file somebody dropped on it. `lines[1]` is the short /
 * went-nowhere case, and carries `{duration}` (m:ss under an hour, h:mm:ss over
 * it) and `{distance}` (metres under a kilometre, otherwise one decimal of km) —
 * the row's own displayed numbers, so the line reads against the key metrics
 * directly above it.
 */
export const NOT_A_SESSION = {
  "lines": [
    "Your watch says this afternoon happened, but its recording has not arrived yet — so it is not counted in totals, trends or records until it does.",
    "No time on the foil, {duration} long and {distance} covered — so this looks like a recording rather than a session. It is kept, and left out of totals, trends and records."
  ],
  "tag": "No riding detected"
};

/** The three sentences the product says about itself (docs/copy/phrases.json). */
export const PHRASES = {
  "promise": "CleanJibe reads a wingfoil session off your watch and tells you what actually happened: how much of it you spent on the foil, how long each flight lasted, your speed records, and — for every turn — whether you flew through it, touched down, or fell in.",
  "callToAction": "analyze your wingfoil sessions free — cleanjibe.org",
  "captionOffer": "analysed with CleanJibe, free at cleanjibe.org"
};
