/*
  Generated by design/generate_tokens.py from design/tokens.json — do not edit.
  Edit the tokens, re-run the generator, and commit all four files together;
  design/check_tokens.py --check fails the build on drift.

  Contract: docs/presentation.md. js/viz.js maps these onto its own names (C.good,
  C.foil, …) so nothing downstream has to know a token from a literal.
*/

export const TOKENS = {
  "outcome": {
    "flew": {
      "hex": "#0ca30c",
      "swiftUI": "green"
    },
    "touchdown": {
      "hex": "#fab219",
      "swiftUI": "orange"
    },
    "fellIn": {
      "hex": "#d03b3b",
      "swiftUI": "red"
    },
    "courseChange": {
      "hex": "#7a7a72",
      "swiftUI": "gray"
    }
  },
  "effort": {
    "pumping": {
      "hex": "#8f7ce8",
      "swiftUI": "indigo"
    },
    "takeoff": {
      "hex": "#3987e5",
      "swiftUI": "blue"
    },
    "splash": {
      "hex": "#3fc4d8",
      "swiftUI": "cyan"
    },
    "failedTakeoff": {
      "hex": "#d03b3b",
      "swiftUI": "red"
    },
    "window": {
      "hex": "#ff9f0a",
      "swiftUI": "orange"
    }
  },
  "phase": {
    "flying": {
      "hex": "#40c8e0",
      "swiftUI": "teal"
    },
    "offFoil": {
      "hex": "#97979d",
      "swiftUI": "secondary"
    }
  },
  "direction": {
    "ink": {
      "hex": "#c3c2b7",
      "swiftUI": "primary"
    }
  },
  "opacity": {
    "directionWeb": 0.42,
    "directionFlying": 0.62,
    "directionOffFoil": 0.38,
    "directionNeutral": 0.22
  },
  "glyphs": {
    "takeoffPumped": {
      "sfSymbol": "arrow.up.circle.fill",
      "webShape": "arrow-up"
    },
    "takeoffFree": {
      "sfSymbol": "arrow.up.circle",
      "webShape": "arrow-up-hollow"
    },
    "takeoffFailed": {
      "sfSymbol": "arrow.uturn.down.circle",
      "webShape": "uturn"
    },
    "splash": {
      "sfSymbol": "drop.fill",
      "webShape": "drop"
    }
  },
  "recordWindows": {
    "default": "best2s",
    "order": [
      {
        "id": "best2s",
        "label": "2 s"
      },
      {
        "id": "best10s",
        "label": "10 s"
      },
      {
        "id": "best5x10s",
        "label": "5 × 10 s"
      },
      {
        "id": "best100m",
        "label": "100 m"
      },
      {
        "id": "best250m",
        "label": "250 m"
      },
      {
        "id": "best500m",
        "label": "500 m"
      },
      {
        "id": "bestNm",
        "label": "1 NM"
      },
      {
        "id": "alpha500",
        "label": "Alpha 500"
      }
    ]
  },
  "layers": [
    {
      "id": "flying",
      "label": "flying",
      "defaultVisible": true
    },
    {
      "id": "offFoil",
      "label": "off foil",
      "defaultVisible": true
    },
    {
      "id": "effort",
      "label": "best effort",
      "defaultVisible": true
    },
    {
      "id": "pumping",
      "label": "pumping",
      "defaultVisible": true
    },
    {
      "id": "flewThrough",
      "label": "flew through",
      "defaultVisible": true
    },
    {
      "id": "touchdown",
      "label": "touchdown",
      "defaultVisible": true
    },
    {
      "id": "fellIn",
      "label": "fell in",
      "defaultVisible": true
    },
    {
      "id": "courseChange",
      "label": "course change",
      "defaultVisible": true
    },
    {
      "id": "takeoff",
      "label": "takeoff",
      "defaultVisible": true
    },
    {
      "id": "splash",
      "label": "splash",
      "defaultVisible": true
    },
    {
      "id": "direction",
      "label": "direction",
      "defaultVisible": true
    }
  ]
};
