import Toybox.Lang;

// GENERATED by lab/tools/make_autowind_arrays.py — do not edit by hand.
//
// Recorded 1 Hz (cog, speed, foil-state) streams from the two `ciq` fixtures, for the
// auto-wind acceptance test in WingfoilTests.mc (docs/testing.md layer 3, and
// docs/algorithms.md "Watch approximation: auto wind"). Every function here is
// (:debug)-annotated, so none of these kilobytes reach a RELEASE build. It cannot be
// (:test): the unit-test runner treats every annotated function as a test case, and
// these take arguments and return data.
//
// Encoding, three printable ASCII characters per sample:
//     char 0   course over ground   cell(round(cog / 4) % 90)       -> 4 deg cells
//     char 1   Doppler speed        cell(min(89, round(v / 0.2)))   -> 0.2 m/s cells
//     char 2   foil state           '1' while the flight detector is ON, else '0'
//
// cell(v) is 33 + v STEPPING OVER 34 and 92 — the codes for the quote and the
// backslash, the only two a Monkey C string literal cannot carry raw. The reader in
// WingfoilTests.mc undoes exactly that.
//
// The stream is decimated by 3 and replayed with dt = 3.0 s, which
// keeps the distance weights and the 60 s evaluation cadence on the session's own
// clock while fitting a two-hour session into a watch unit test.
module AutoWindFixtures {

    // Samples are replayed with this dt.
    (:debug) function stepS() as Float { return 3.0; }

    (:debug) function count() as Number { return 2; }

    // ---- 2026-08-07-0754_nago-torbole-windsurfen_ciq ----
    // 1361 samples at 3 s, 11181 m of flying
    // distance. Engine (fixtures/goldens): wind from 35.58 deg.
    // Replica: locks at 658 m on 28.03 deg,
    // finishes on 28.03 deg (-7.55 deg vs the engine),
    // 0 later update(s), largest adopted step 0.0 deg.
    (:debug) function name0() as String { return "2026-08-07-0754_nago-torbole-windsurfen_ciq"; }
    (:debug) function engineDeg0() as Float { return 35.58; }
    (:debug) function chunks0() as Array<String> {
        return [
            "%!0%!0%!0v!0t!0t!0t!0t#0m!0m!0m!0m!0V%0V!0V!0V!0V!0V$0V#0V!0h%0]&0N%0a!0a!0a!0e!05!05!05!05!05!0g!0b&0I!0I$0I!0m'0i'0k%0t%0#$0#!0#!0r$0l$0l!0l$0l!0l!0l#0l#0l!0l!0l!0l!0l!0s$0g$0L$0d#0d!0k$0g&0q%0g'0j%0m&0j%0g%0n%0o$0p%0d'0r&0e'0j'0g&0j(0p(0`+0l)0j/0k.0j00h41q61i51o;1n71q81q91t<1u:1q;1t91t:1q;1s=1m>1b?1L611612%0>+0a%0`!0`$0B$0N&0F'0F(0>'0E)0L'0C(0J)0<(0A)0F00D00B10B61?61<91=;1<;1;<19=1:<19<1;81?:1K;1h01J'0d%0-%0-$0-$0[!0[#0;$0J$0d%0c#0l(0e/0o41h11i31g21g71h61j71k61k71m71r:1s=1p<1p:1n:1h51o71Y51P*1`(0b(0=#0D$0A%0>$0>#0>#0N(05%0='0E&0J.0F71E61G41G41D81E:1A:1B81B81B71@91@81=81=71;716:18919;1D71e21l)1_#0k#0k!0k#0k!0k!0x!0q#0h$0o&0b(0s&0c'0h)0m)0l.0g.0m61i51m91k81m71k61n:1n;1r91q=1p:1l91o:1q91t=1u<1t<1q:1o?1s;1o;1^91P.1F*0F+0G,0H10G51@91C<1<<1>;1=;1>;1?:1C;1B:1>:1A<1?61A71?51@51@41U41b'0g'0j)0k-0l(0k,0m00l20p81n61r71q:1s91p=1u<1u:1u;1t<1x;1v<1w:1z91w=1p91b71N31J.1O.1L31J31F51D71C81A71B71<51D'0",
            "2&0T'0J%0H&0>'0<'0<'0;'0C&0=&0A'0;'0?,0E.0B/0?31>71;91?71;91<91:81=71:91981;916:1981=71?51<31?51?01='0>(06'05&09$0D%0D!0D!0D!0D!0A!06!0A%0*%03%00%0#$08%0B'0.%0;%03#0u!0u#0C!0Z$0R'06$0c$0l'0f'0i'0n&0m$0m!0g&09#09!0X%0u$0B!0B%0b%0i%0i(0j(0h'0k'0a)0m'0l(0k)0k(0n(0j(0k(0i00m91r:1q=1q91r71g51r81q<1p:1r91o91n:1o;1r;1n81q91s:1n:1p:1q81r<1t:1t91p91g;1Q61J,1G.1E91C81:<1;;1?=1?=1@?1D<1><1>;1>>1:>1<91<81>>1Q>1c81j91j81m:1o61k41p91q61n:1l51k81(.16&0A$0]$0_%0g$0r$0R'0Y$0X'0b'0h$0i'0m(0u'0m.0o61s81n91v=1v:1v91t81r<1m91e=1R81D51d&1r$0b$0a%0a&0O%0C'0C)0F)0G00A91C91@<1<;1=>1;=1??1;:1?<1>:1<=1><1><1=?1>=1@;1>:1<<1A:1P=1h61m51h71o91j91o;1k<1r>1r=1r<1s<1t;1r<1u;1s?1u=1t;1n81i<1^81M71C61f$1v(0V&0V#0Q%0A$0?#0?$0?#0R%0W'0G&0I'0E,0C)0D)0G10A71>71A81?91<<1?;1==1><1><1?=1=:1=91=:1?:1?<1;91E;1R;1b91i71l61l71`81W'1Z&0,&0{$0W*0`#0U%0g&0h$0r'0i(0m,0q*0k31m41s71t91x;1u<1w81q51w91v<1x<1s<1n=1d:1R61C51I51E81><1>81A91?<1",
            "A;1<;1A81<<1==1<<1?<1==1?>1D<1L>1W91e71p:1g,15$0I%0r#0n%0F#0P!0P#0c$0U&0[%0v%0j(0h,0n)0i10p61p81q91p91u=1s:1t91v<1t:1r;1s<1w>1t=1w?1t;1v=1v:1x:1x=1v<1w=1o91V41Q/1D21C(1E%0t!0t#0t$0Z$0c$0c$0x$0r$0Z%0M%0H%0L%0I&0I&0K+0I*0G(0G)0D10C41E51?91C81B81>;1?<1A?1>>1A<1?<1@=1@=1?;1@<1><1?<1B91>91C;1T:1h41h61j51k51_*0g,0j*0i/0o61n81p91r:1q:1q;1p81n91m<1s81r;1s;1t=1u>1s=1s;1p91t91s;1s<1t=1s<1s<1s<1t<1p<1b:1N31O/1M,0!*0p#0b#0d!0Z$0<$0<!0<'0Q$0W$0L&0H(0G(0H'0H(0M'0K(0E*0F,0>)0A'0E/0C81<91A;1A91C81C71D81H51A91D:1@91F81B91C71@71B71A91=91=:1?<1?<1><1?:1A<1?:1F>1T:1d61h71e11>.04$0?%0Z$0P%0U%0k&0f'0g'0d&0h(0n*0i*0i,0m61k61r91q71n91r:1n:1r:1n91q81q:1p<1m:1t<1p:1n:1r<1p:1j<1d;1T71E41C11B71B51B81?;1>919<1;=1;=1=>1=?1@<1><1<=1>918=1==1>;1<=1@<1J=1X61`41i51c-1j%0L%0V#0F$0y#0Q&0K!0K#0K$0K$0i#0m#0*%0L%0l&0h(0g%0p(0k(0n+0h+0j61h61l71o91o;1o91n:1n91p81p81q81m61j61q61p:1p:1r91r91o51p61p81n71m81o91g71c<1P61A41C/1@61=91",
            "?81>81=<1;<1=91@91>81?:1>;1=<1;;1;>1?;1><1;;1;;1;<1<<1?:1>91=;1><1B=1M<1_71k71j61g41e51q91q:1r;1q91r<1t;1s:1p81q<1p81p91q81p91s81o71t81p81n91p91r:1p51q81q81o81m71i81h61h91l81d;1U;1L31=51D31A91;=1=91?91A:1@:1@:1?<1A71A:1@;1D:1B;1A;1A:1=91D91?;1>;1@:1@;1A;1A<1A<1==1@;1B91B:1@=1K=1a61[#0p'0m)0e*0h'0m*0o(0h,0l)0g*0n)0j)0j.0j.0j/0k10o71s91r81t81v71s71t81p;1t:1t;1v<1w91s91u:1v:1t91p91q81q51q81u81p71q81m:1w81r81u81w61j41o91u81r91p91s:1p91r<1u81i71o81n;1r91k:1j=1^81S11V*0F!0Y#0Y$0p#0p'0Y$0S&0D(0K&0O)0I%0J)0G*0F,0F)0H00@71A:1?81B71=;1@91>;1C;1A=1@;1C:1E81D81G61C:1E91D81D<1A=1?;1?;1C=1B<1A<1A;1D;1C:1B<1@<1?:1F71A;1@81A91=:1C;1?>1A:1D;1R<1e61o41o51i+1i.1j41n61n71r91t:1v91u:1q81t61t:1s<1t:1s:1w;1s:1v:1r91u91w:1u:1s91q91g;1s<1u<1o71t91s71p51n61l41s91u81t:1s81p51o91s91m81c>1U71G71E41D21A61;<1=:1=<1><1A71@71C91F71K61E91F91H81F;1D;1C;1A91A<1B;1A;1B=1G<1V91e61m61i11o51p61n71o71n81l81p:1n71o:1l61l91n91n<1",
            "t:1r91t:1s91q91u81s71i<1q:1h81W71G01B)0A(0D'0J'0?*0B-0D.0C*0?(0@)0D)0A'0C(0A'0<(0>'0J&0@&0B'0A'0H'0F'0C(0@(0=(0C'0>*08'0?'0<*0B+0D-0F/0=(0>(0D'0A)0@(0J(0>'0B(0E'0E(0H(0D)0;'0D(0E-0B41A:1@81C61B81B81B:1B51E41?319'0H&0B%0A&0J%0J&0P'0J%06%0E&0H&08'0B%0<%0C%0='0G)0?&0D%0I&0D'0='0?'0C)0B(0G*0C'0<&0A%0A&0>'0A(0:'0>)0?*0@*0F*0@(0E+0=(0=+0?,0=*0A*0@)0>'0D)0;(0>)0?)0B+0>*0;)0B(0F(0A(0@*0E(0E'0@)0A*0@+0>(0@)0B*0;+0@*0D31@51C81D81A91@81>91@71=61=41>+1<)0W'09&0d!0d!0d!0g%05&0O#0O#0+#0.$0M$0",
        ] as Array<String>;
    }

    // ---- 2026-08-29-1440_nago-torbole-windsurfen_ciq ----
    // 2241 samples at 3 s, 20219 m of flying
    // distance. Engine (fixtures/goldens): wind from 199.88 deg.
    // Replica: locks at 2320 m on 195.91 deg,
    // finishes on 195.91 deg (-3.97 deg vs the engine),
    // 0 later update(s), largest adopted step 0.0 deg.
    (:debug) function name1() as String { return "2026-08-29-1440_nago-torbole-windsurfen_ciq"; }
    (:debug) function engineDeg1() as Float { return 199.88; }
    (:debug) function chunks1() as Array<String> {
        return [
            "/!0/#0/!0/!0/!0/!0]!0P$0q#0q#0!'0!&0y%0u'0u%0u#0u!0u!0r$0+$0+$0+!0+!0E$0k&0h&0p(0d&0k!0o)0b$0b$0^&0g$0z$0L!0e$0#$0e$0^#0^!0:'0r&0w%0h%0h(0u(0j)0l)0j+0m,0q10m61l:1g<1g;1iA1g>1g@1gA1fA1dA1fB1gB1f>1hA1eB1eA1f@1fA1gB1eD1dB1fB1eC1dB1cC1cA1hA1i@1i@1f?1fA1fB1dA1h@1jA1oB1hA1oA1mA1gA1f@1g@1fA1e@1p?1g?1d?1i?1u@1)814;1>81841911l)0f$0?$0^%0.$0U#0a#0t&03$0l#0&#0&#0&!0z$0/%0,$0$'07(0)$07*0<'06&07*0<'06*00(0m)01$0N$0?#0b$0b#0b!0<'0g#0{$0*$0u&0=%0:&0:$0g%0g$0_$0&#0!%0k(0n&0q%0n)0l+0s-0t51o61l81h;1e?1i=1f>1f>1e@1c>1b=1d@1e>1c?1d?1d>1hA1k@1b@1m?1l>1c?1e>1eA1gA1k>1vC1)=16<1?:1>41941;:1>:1A>1?>1A?1>:1?<1B>1@:1?A1AA1A?1@?1C>1>?1<B1?B1@?1@?1>>1?>1=>1@A1:@1=@1C@1A;1@>1@>1@A1@>1A>1A?1>;1;>1?>1@=1?>1>?1>?1@>1B>1?>1>>1=?1=?1?A1=>1A=1A?1@>1?:1;>1C>1A=1A;1@>1@>1<?1?>1A=1@?1C>1D:1=81C;1==17<1.<1{21%.1%*0o$05&0i#0?$08%08$0w%0#$0w$0o(0m)0m+0t31g:1g;1g;1g<1h;1g>1e<1h>1i;1d=1h<1i?1g;1d;1g=1f>1d=1i71e=1k=1_=1i;1f:1g<1h>1",
            "k=1s=1'?1591=617216+06/08/0810<71>;1@>1A<1B>1B?1C?1D?1A?1C?1C?1B?1B<1A=1B=1@=1A>1D=1A:1?81?<1H<1C<1>@1;=16C1(@1x;1t;1p:1h;1n<1k>1hA1g@1gA1e@1e>1o=1|>13<1?:1821641>'08&00(0@!0{'0<'0|'0@#0q!0|$0a!0-%0,%0C$0=$07%0=)0F(0;%0D)0@(0=,0=10@71B;1B<1B>1E;1D>1B;1B>1@=1E>1?;15?10B1{31k31w,1s31q61j:1j:1l:1g>1i<1g?1k=1f?1c<1h=1g;1h=1i;1h;1h<1k<1u>1k=1g=1h<1i:1f=1g>1i=1j;1g=1b=1f=1f<1g;1f?1n<1s?1#B12?1?81901==1B?1C;1=81A<1B<1E>1C;1B;1<61??1E=1=:1A<1C?1C>1B?1B:1D;1D=1D=1D=1C<1C;1?;17<1.;1u61t41x.1>)1_%0i#0'#0?%00$0x'0y&0t%0#'0n(0g)0m,0q-0s51i;1f51j<1g=1i>1j;1f>1f;1h=1f?1f?1g=1i=1h?1l<1u>1v=1l=1d?1b@1g@1p=1{?1.91=71741;:1A<1E?1A<1?=1C;1C=1D>1B;1?<1E<1B=1B@1=?1A?1<>19?1<=1A<1A=16@10>1,<1)81)61S/1S$0U$0Q'0#$0K$0u!0.%0{(0s$0s(0i(0p*0p50q00m51n91p:1o=1i@1g?1b=1f@1j>1d=1h<1g<1h;1f=1q>1m@1i<1k?1s@1p;1f<1fA1g?1k@1z?1+?19;1?;12014+0]$0R)0M$08#0t$05$0!$0@(04+0,'0:(0;'0D)08)0@)09-08.0:00w,0B$0&$0,%0,!0;%0.$0>$04%0",
            "##0-#0'$02&0B&0:(0;(05)06)01%09*0A+0:,0940!*0R&0R$0R!0R!0R$0.'05$00%0/%0u'0'%07&0;*09(07(0=-07,0?.0830710561@:1C;1D=1@=1D<1A?1G@1E<1F<1C=1C<1E<1<=1D>1F?1D=1B?1A=19?13@1&=1t71n71g=1j=1l;1n:1o>1i?1f>1f@1i;1l=1l91i?1h?1p?1p@1f@1f=1gA1c@1j=1o<1k=1m=1x?1.<1<91?81791A=1=:1?<1<<1;;10>1->1/71V11W%0{&0r&0C'0e$0e#0,'0($0h%0u&0m(0l*0u+0r+0p+0o41i<1g=1d?1e;1e:1g>1g;1c>1g<1eA1a=1d;1h<1f=1j?1sA1p@1h?1h?1r@1'@16:1;<1;<1;;1)=1p81d?1e?1e@1gA1p?1!B10A1<=1=:1==1?=1;41:;1>=1@613@1w<1p51f?1eB1d?1dB1eA1f@1n=1x31|$0|#0?(0s&0'$0%%0-#0-!0)(0n%0k&0#$0r'0f&0i+0m+0i+0o-0o61f=1c:1j91d<1q?1d@1mA1d@1f;1h<1o=1c@1d<1l=1l@1eB1s@1x@1p:1W-0u%0H$0)$0M$0f&0'%00#08'09)02$09'07(07,0@,0700;91;;1C=1C<1A;1@>1><1A=1@<1B>1>>1?A1D>1C>1?@1=@1>=1<<1B@1A>1??1?=1<=1D>1>>1>>1CB1B?1@A1@@1B@1AA1=<1>@1C>1B?1?;18?1@A1B<1AB1C>18@19C1.B1z;1q91o51o81m<1d>1f:1i;1k81i<1f=1q=1m?1g>1i91l>1gA1i>1n?1dB1i:1e>1b<1n:1o?1i?1v@1tA1m=1e>1m=1!=1*916;1;:1@;1",
            ">71:81<=1E01E+0D+0/!0D$05!05#0Y%0%%0t%0q%0u'0l(0q)0e)0q00o31n31e:1f<1f91h=1b<1l81l91y91>,19$09%0o$05!0G!0*%0W$0*$0v'0z#0{&0o$0r)0i*0j*0n+0o20h81g91f71h91g:1h:1i91i=1g=1h91j71k:1p=1s=1{A1&71461991;81>:1>91>91]'12'02!07&0'%0'%0%#0B#0+%0*$0-%0?%05%0-&0'!0i%0Z'0^(0?(0x$0z&0t(0t)04&08$0Z%0O%0s%0/$0)&0.%05&05(0<#0.*0<)0?)0=.0531=61;;1=;1A>1A=1?>1>=1==1<=1A<1A>1D>1C@1DE1B@1A@1B?1E<1??19?16>1B>1D=1?@1D@19?1>A1B=1:>1C@1C>18>1BB1E@1C>1:A1>A1?C1@B1F?1D@1<>1=>19@15@1|91n91Y11#$0|&0D!0.#0z(0N$0(%0'$0z%0z&0s%0a)0v)0q(0t)0g+0q/0p31p61j;1h91f:1j:1k<1n;1e?1m>1h?1h;1h>1j;1{>1-?19;1?=1B;1<=1B=1>;1@<1==1/?1x81i>1dA1gA1fA1g<1g=1h>1p=1'>19>1A71@;1@;1B<1;>1?;14<1u91l91hB1gA1i?1m?1q>1tA1)=17;1<:1@>1@=1?=1@>1C>1B;1>:1>?1@<1B<1C=1B:1B;1A=1871k*03%0+!0;#0!%0q%0F$0O%0g$0+%0$&0a&0a$0!%0/$0D$0]%0K#0K$0&&0f$0.%0x&0r)0t(0g*0l+0l'0s10l71f>1l=1f?1p>1u?1vB1gB1fA1g?1eA1kA1p=1'@17<1><1@=1@=1B>1<;1A>1B?1@;1@=1@<1?>1:?1'<1m51",
            "j<1f?1k>1n>1v?1(B15@1@=1B>1D?1@<1><1B@1B>1B<1@<1??1==11<1911'&02.0.,0w$0m$0q$0M%0A#0S&0*%02(0n&0o(0t&0j)0q-0p41j91h;1h<1j=1j81g;1j;1k<1l;1p;1|>1.<1?91?91?>1??1C>1@=1;=1-<1v;1h@1g>1i@1fA1fA1kA1i>1o<1%?12<13A1$@1+/1,/1d$17%0S$0L!0:$0i%0y(0q'0q*0p)0o+0o71f=1g;1i;1i;1g?1m<1k91h:1g>1i?1m>1!?15<1>818<18<1?>1=616+15,05/0(%0K'05#0Z$0O#0O!0{#0&&0+$08$0=$0@$0@%0/$00&0;'09(04(0?)06'03+0:)0=*0=-0641981C>1C=1><1E<1H<1E<1D<1F>1C=1C?1B?1D?1@=1G?1D@1F>1A<1@@1??17;12A1y%11)07(0#(0&$0<%0t!0t$0l$0+$0/$0y*0y$0L%0#%0x*0X$0-(0*$0q'0,&0r%0l&0p+0o*0m*0p&0p-0t31m81l:1k>1f?1m>1l>1j?1f?1h?1h@1k@1k<1i?1l=1!?14:1>61=91?;1B>1@>1A=1>?1=;16?1#:1s91j@1k?1l@1p@1hD1j?1h?1i@1g>1m?1#=16=1?=1@=1A=1B@1?;1@=1=A1.<1s;1k>1eA1f?1g>1n=1'A19:1B@1E>1A=1A<1A<1D@1C<1>:1;=1*=1o61g11u.1q81m;1e@1f?1k<1&=1381>=1A<1B>1A>1C>1C=1C?1B@1@@1/>1r71p-1t01t21l71k:1dA1k?1iA1g@1i>1m;1p?1)A1.<17<1>?1A?1@?1BA1B@14@1|:1i<1j<1j=1j@1j?1l<1l>1p>1o?1i@1f=1",
            "h>1j>1j=1g?1i>1g>1k<1k;1f?1h<1k=1w?13=1A?1@;1>=1@@1C=1C=1D<1F21421a$0v$0r$0t$0r$00&06%0F%0:+0:(06%06!0I)0I*0M!0L$0M#0?%0*%0+&0)&0Y'0<(0;&0?'0<)0>+0;(0=&0A(0>*0<,0@-0<,0@(0?*0?&08*0A(0A'0;-09-0=.0A,09/0?91==1@91A=1E<1A91B91F<1D>1B?1C=1E=1B>1D=1@:1=<1.<1w91h11f*0t(05#0q*0o(0$*0;$0b!0`'0/$0,%0!'0x$0u%0y%0s(0l)0x&0o*0u.0q71i<1j91l=1h?1i?1i>1n>1p?1l>1g=1f=1j@1i<1d?1i=1g=1m@1t>1z@15=1:=1971r&09&08%0R!0d!0R$0>'0g%0-&0B%0?)07(0@*0=(08)0:,07/0=/0:70830951?71B:1D>1C?1E<1C;1C<1B=1D;1E=1B<1?;13=1/71{11{)0[%0]!0O$03%0F#0$%0s$0h'0r'0s+0o)0k+0m+0q.0n+0o)0t.0r41n61n91k=1h<1i<1l?1k@1i?1j@1k>1i@1v@1-:1L:1h,14#09'0`%0.#0!!0!$0M%0w!0N$0o%0,(0!%0v#0m'0t'0o)0m*0q)0m)0m&0p,0r.0q41m51p51l:1f>1f;1h<1i=1g<1g>1j;1g61i?1g=1i<1i71j<1j=1gA1l:1l>1m=1y@1->1;31>81@61Q*1U(0y$0w$0z#0z#0z%0/(0/#0;!0*$03$0n&0-%0z$06#0?#0?$0)$0)&0-%01%0>$0.%0?%09'0B%0<(0@&0?(0<+0@*0>,0;)0;*0>-0?*08/0961=;1@:1=;1A<1=919=1D@1;>1C?1C<1@=1C=1;>1",
            "B=1B?1B@1AC1?A1A?1B=1@;1@<1A?1DA1==1A?1H=1==1>A1B=1A<1E>1?=1@@1<<1A>1E@1>=1=>12?1%81q31;+0J#0L*0Q'0-#0.$0.$03&0!'0I)0I$0I$0I$02$0$&0v)0#'0u'0t'0k'0r'0%&0x&0?&0/!0#$0;%0;#0L%0F$05%0y$0*&0z%0v+0t'0r)0o+0n)0r'0s00p51m;1k91n<1l>1l?1m<1l>1j?1k>1p>1q?1s?1!?16<1;=1@81>81A=1=;1@=1>;1<:1?<1A?17:1w51*$0[$0[%05$0-%0O%0O#0O$07#0*&0!%0y%0t(0l)0q'0k'0q(0p-0r.0x-0?$0O!0O$0m$0|#0S!0S%0r$06&0m%0r(0n(0l)0q(0o)0p+0u,0{+0q)0u+0u*0o)0q,0q*0l)0o,0s,0q(0q+0q00s/0o31m61j91i:1o<1r<1p;1g;1u?1l>1l;1o>1yB1-:1*C1d'0c#0^!0U!0L#0h!0h#0h!0*&0V!0z%02&0L&08)02$04+08'0?(01'05&04(0=)09)0;*0?&06$0>%0'$0'#0$%0u$0@$0@$0$$0k%0o(0p%0n&0q)0s)0j)0p)0o'0n)0r.0p/0o41r11n/1l+0l(0n,0q00p+0j)0k)0q)0m*0n(0q*0n)0s+0s/0o00o)0t'0u)0r.0o41q51k>1m<1lA1n@1p>1p?1n?1m?1o=1q=1p>1qA1#A11?17919>1;>1>:1@=1><1=@1:C1=;1/=1#@1T(1W'0'&0r#01%04&0y$0'(0s&0)#0)#0)#0X#0<#0<#0<!0:&04%05%05&06(0<(0@%0<&0?'0W%0a%0D%0;$02&0'!0D%0D&02%0@%0o%0o#0{$0;#0k%0k!0/!0",
            "/#0/$0.$0b#01%08#02$0-%0B)0/$08(0I&0@&0B(05)0=(0;(05*0A&0<+08'0:'0:'0A&0C%0:'0:.06109104+0<&08)0:'0>(0<)0=*05'0='0=*0@)0?)0<+0<(09.0>-0<)0<*08*0B(0@(09(0:(0;*0=)08*0=*08-08-0<(0@,0E+0A)0>(0:%0;(07,09/0;)0@(04'0=(0D)0@-07-0<(0;+0:-0<+0A+0>-0<+05.07516:19=1=;1C<1@>1==1<81::19816:1=:1?31811,/1j!0.#0.!0.#0.#0.$0.!0.#0Q#0Q$0Q#0I$0?$09#0>&0E&0:&0k#0[$0u!0u!0u!0u!0i%0i&0i!0]$0x%0:#0:!0:#0:!0:!0F#0{!0{!0f%0U!02%0]%0:#0j#00#0((0",
        ] as Array<String>;
    }

    // Dispatch, so the test loops rather than repeating itself per fixture.
    (:debug) function nameAt(i as Number) as String {
        if (i == 0) { return name0(); }
        if (i == 1) { return name1(); }
        return "";
    }

    (:debug) function engineDegAt(i as Number) as Float {
        if (i == 0) { return engineDeg0(); }
        if (i == 1) { return engineDeg1(); }
        return 0.0;
    }

    (:debug) function chunksAt(i as Number) as Array<String> {
        if (i == 0) { return chunks0(); }
        if (i == 1) { return chunks1(); }
        return [] as Array<String>;
    }
}
