#!/usr/bin/env python3
"""Derive `fixtures/presentation/*.expected.json` from the analysis goldens.

The analysis goldens say what the engine found; these say what a UI is allowed to *draw*
from it. They are the second half of docs/presentation.md's enforcement: both the iOS app
(`PresentationTests.presentationGoldensMatch`) and the web verification
(`web/tools/verify_presentation.py`) assert exactly these numbers, so a marker that
appears on one platform and not on the other is a failing test rather than a bug report a
year later.

    python3 web/tools/make_presentation_goldens.py            # write
    python3 web/tools/make_presentation_goldens.py --check     # exit 1 if stale

Nothing here re-derives a metric: every fact is a *count of what survives an eligibility
rule*, and every rule is written down in docs/presentation.md:

  * turns with `counted == false` are course changes — never an outcome marker, never in a
    tally, never in a trend;
  * a flight end already owned by a turn would double-mark the same swim, and a truncated
    end is a recording that stopped, not an event;
  * pump episodes: only `success` and `failed` are attempts; `recovery`, `in_flight` and
    `unknown` are counted by the engine but never drawn;
  * splash evidence comes from the engine's `submerged` flags and is never re-derived;
  * turn filters are type × ENTRY side, ANDed, over counted turns only;
  * every flight is started by one takeoff and stopped by one end, so the takeoff halves
    and the flight-end buckets each sum to `flightCount`.

Stdlib only, and byte-stable: two runs produce identical files.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

WEB = Path(__file__).resolve().parents[1]
REPO = WEB.parent
GOLDENS = REPO / "fixtures" / "goldens"
OUT = REPO / "fixtures" / "presentation"
#: The periods fixture lives outside `OUT` on purpose: it is not derived from an analysis
#: golden, and the orphan sweep in `write()` removes anything under `OUT` that is not.
PERIODS_OUT = REPO / "fixtures" / "periods" / "periods.expected.json"

sys.path.insert(0, str(WEB / "lab_bundle"))
import library                                                          # noqa: E402

SUFFIX = ".expected.json"

# docs/presentation.md "Record windows": eight kinds, canonical order, best2s default.
RECORD_ORDER = ["best2s", "best10s", "best5x10s", "best100m", "best250m", "best500m",
                "bestNm", "alpha500"]
RECORD_DEFAULT = "best2s"

TYPE_FILTERS = ["both", "jibes", "tacks"]
SIDE_FILTERS = ["both", "port", "starboard"]

NOTE = ("Generated by web/tools/make_presentation_goldens.py from "
        "fixtures/goldens/ — do not edit. Asserted by ios PresentationTests and by "
        "web/tools/verify_presentation.py; a count that differs between the platforms "
        "is a failing test, not a bug report (docs/presentation.md).")


# ------------------------------------------------------------------- the rules


def outcome_layer(outcome: str) -> str:
    """The ladder: fell in, touchdown, everything else flew. `glide_out` is a flight that
    ended without drama, which is the green end of the ladder — the iOS app's
    `outcomeTone` reads it exactly this way."""
    if outcome == "fell_in":
        return "fellIn"
    if outcome == "touchdown":
        return "touchdown"
    return "flewThrough"


def drawn_flight_ends(doc: dict) -> list[dict]:
    """Straight-line flight ends: the ones no turn already explains, from a recording that
    did not simply stop."""
    return [e for e in doc.get("flightEnds", [])
            if e.get("ownedByTurn") is None and not e.get("truncated", False)]


def marker_counts(doc: dict) -> dict[str, int]:
    counts = {"flewThrough": 0, "touchdown": 0, "fellIn": 0, "courseChange": 0}
    for turn in doc.get("turns", []):
        layer = outcome_layer(turn["outcome"]) if turn.get("counted") else "courseChange"
        counts[layer] += 1
    for end in drawn_flight_ends(doc):
        counts[outcome_layer(end["outcome"])] += 1
    return counts


def clean_jibe_count(doc: dict) -> int:
    """The star layer: counted, named a jibe, and passed the engine's own `success` flag
    (docs/presentation.md, "Clean jibe").

    Deliberately **not** one of `marker_counts`: those partition the turns and the drawn
    flight ends one mark each, and a clean jibe is already counted there under whatever
    outcome it ended on. This is the second, stricter reading laid over the same set.
    """
    return sum(1 for t in doc.get("turns", [])
               if t.get("counted") and t["type"] == "jibe" and t["success"])


def takeoff_counts(doc: dict) -> dict[str, int]:
    """Both halves of the takeoff layer. Every entry in `takeoffs` flew (the engine only
    writes one for a flight that happened); the failures are the pumping episodes the
    classifier called `failed`, which is the only block that gives them a time."""
    takeoffs = doc.get("takeoffs", [])
    free = sum(1 for k in takeoffs if k.get("free"))
    failed = sum(1 for ep in doc.get("pumpEpisodes", []) if ep["outcome"] == "failed")
    pumped = len(takeoffs) - free
    return {"pumped": pumped, "free": free, "failed": failed,
            "total": pumped + free + failed}


def flight_end_counts(doc: dict) -> dict[str, int]:
    """Every flight end, in the three buckets the marker rules already distinguish.

    `drawn` is the hollow mark; `ownedByTurn` is the end a turn's outcome window already
    explains (marking both would draw one swim twice); `truncated` is a recording that
    stopped rather than a flight that ended. They partition the block, so `total` is also
    the flight count — the invariant `check_flight_invariants` asserts.
    """
    ends = doc.get("flightEnds", [])
    owned = sum(1 for e in ends if e.get("ownedByTurn") is not None
                and not e.get("truncated", False))
    truncated = sum(1 for e in ends if e.get("truncated", False))
    return {"drawn": len(drawn_flight_ends(doc)), "ownedByTurn": owned,
            "truncated": truncated, "total": len(ends)}


def splash_count(doc: dict) -> int:
    """The barometer's evidence on both channels, with the same ownership rule that keeps
    one swim from being marked twice."""
    turns = sum(1 for t in doc.get("turns", []) if t.get("submerged") and t.get("counted"))
    ends = sum(1 for e in drawn_flight_ends(doc) if e.get("submerged"))
    return turns + ends


def pumping_spans(doc: dict) -> int:
    """Pump-burst spans: the attempts, and only the attempts."""
    return sum(1 for ep in doc.get("pumpEpisodes", [])
               if ep["outcome"] in ("success", "failed"))


def record_windows(doc: dict) -> list[str]:
    """The records this session can actually highlight: a value *and* the window
    provenance the map draws. `bestHour` is deliberately not in the catalogue."""
    records = doc.get("records", {})
    windows = records.get("windows", {}) or {}
    out = []
    for key in RECORD_ORDER:
        value = records.get(f"{key}Kn")
        window = windows.get(key)
        if value is None or value <= 0 or not window:
            continue
        out.append(key)
    return out


def accepts_type(kind: str, turn_type: str) -> bool:
    if kind == "both":
        return True
    return turn_type == ("jibe" if kind == "jibes" else "tack")


def accepts_side(side: str, turn_side: str) -> bool:
    return True if side == "both" else turn_side == side


def filter_tallies(doc: dict) -> list[dict]:
    """Every type × entry-side combination, with the flew-through share's numerator. Side
    is the tack the turn was ENTERED on, never the rotation direction."""
    counted = [t for t in doc.get("turns", []) if t.get("counted")]
    out = []
    for kind in TYPE_FILTERS:
        for side in SIDE_FILTERS:
            kept = [t for t in counted
                    if accepts_type(kind, t["type"]) and accepts_side(side, t["side"])]
            flew = sum(1 for t in kept if outcome_layer(t["outcome"]) == "flewThrough")
            out.append({"type": kind, "side": side, "count": len(kept),
                        "flewThrough": flew})
    return out


def facts(stem: str, doc: dict) -> dict:
    """Everything a UI may draw from this analysis, as counts."""
    windows = record_windows(doc)
    return {
        "fixture": stem,
        "engineVersion": doc.get("engineVersion"),
        "source": f"fixtures/goldens/{stem}{SUFFIX}",
        "generator": "web/tools/make_presentation_goldens.py",
        "note": NOTE,
        # The engine's own count, and the two blocks that must add up to it: one takeoff
        # starts every flight, one end stops it (docs/presentation.md "Enforcement" 3).
        "flightCount": doc.get("summary", {}).get("flightCount"),
        "markers": marker_counts(doc),
        "cleanJibes": clean_jibe_count(doc),
        "flightEnds": flight_end_counts(doc),
        "takeoff": takeoff_counts(doc),
        "splash": splash_count(doc),
        "pumpingSpans": pumping_spans(doc),
        "recordWindows": windows,
        "defaultRecordWindow": RECORD_DEFAULT if RECORD_DEFAULT in windows else None,
        "filters": filter_tallies(doc),
    }


# -------------------------------------------------------------------- the files


def render(stem: str, doc: dict) -> str:
    return json.dumps(facts(stem, doc), indent=2, ensure_ascii=False) + "\n"


# ----------------------------------------------------------------- the periods fixture
#
# One synthetic library, and the periods `web/lab_bundle/library.py` makes of it. The whole
# reason it is a *file* rather than a pair of test cases is that iOS has to read it too:
# months, seasons, trips and the aggregate block are one contract with one reference
# implementation (Python), and two hand-written test suites agreeing today is not the same
# thing as two implementations that cannot drift.
#
# `sessions` is the input, echoed into the fixture verbatim, so the Swift side can build the
# same `SessionRow`s from it. Everything else is Python's answer.
#
# The library is small and every row in it is doing a job:
#
#   a1 a2 a3   one trip: gaps of 1 and 3 days, and 3 is still the same holiday
#   a4         5 days after a3 — a second visit, alone, and therefore not a trip
#   b1 b2      a second spot 12 km away: 3 km separates two beaches on one lake
#   a5         starts 22:30 UTC on 31 August at +02:00 — a SEPTEMBER session
#   c1 c2      two winter afternoons 46 days apart: one season, no trip
#   a6         no anchor fix, so it is placed by name; no swims, no streak, no 10 s
#              record and only three jibes — a period built of it alone has to drop
#              four entries rather than print four zeroes
#
# and the seasons it produces are the two spellings: 2026 reaches February 2027 and is
# therefore "2026/27", while 2027 has not crossed a year and is just "2027".
PERIOD_SESSIONS = [
    {"id": "a1", "spot": "Nago Torbole", "startUtc": "2026-07-31T10:00:00Z",
     "utcOffsetS": 7200, "lat": 45.8760, "lon": 10.8710,
     "rateDurationS": 3600.0, "durationS": 3700.0, "distanceKm": 12.0,
     "foilTimeS": 1800.0, "foilPct": 50.0, "flightCount": 9, "longestFlightS": 120.0,
     "jibes": 8, "jibesSuccessful": 5, "turnsCounted": 12, "longestDryStreak": 6,
     "wetExits": 4, "best2sKn": 14.00, "best10sKn": 12.00},
    {"id": "a2", "spot": "Nago Torbole", "startUtc": "2026-08-01T10:00:00Z",
     "utcOffsetS": 7200, "lat": 45.8762, "lon": 10.8712,
     "rateDurationS": 7200.0, "durationS": 7300.0, "distanceKm": 24.0,
     "foilTimeS": 4320.0, "foilPct": 60.0, "flightCount": 18, "longestFlightS": 240.0,
     "jibes": 20, "jibesSuccessful": 11, "turnsCounted": 26, "longestDryStreak": 9,
     "wetExits": 7, "best2sKn": 15.50, "best10sKn": 13.20},
    {"id": "a3", "spot": "Nago Torbole", "startUtc": "2026-08-04T10:00:00Z",
     "utcOffsetS": 7200, "lat": 45.8758, "lon": 10.8705,
     "rateDurationS": 1800.0, "durationS": 1850.0, "distanceKm": 6.0,
     "foilTimeS": 900.0, "foilPct": 50.0, "flightCount": 5, "longestFlightS": 90.0,
     "jibes": 6, "jibesSuccessful": 4, "turnsCounted": 8, "longestDryStreak": 3,
     "wetExits": 2, "best2sKn": 13.10, "best10sKn": 11.40},
    {"id": "a4", "spot": "Nago Torbole", "startUtc": "2026-08-09T10:00:00Z",
     "utcOffsetS": 7200, "lat": 45.8759, "lon": 10.8709,
     "rateDurationS": 3600.0, "durationS": 3650.0, "distanceKm": 10.0,
     "foilTimeS": 1440.0, "foilPct": 40.0, "flightCount": 7, "longestFlightS": 150.0,
     "jibes": 10, "jibesSuccessful": 3, "turnsCounted": 14, "longestDryStreak": 4,
     "wetExits": 6, "best2sKn": 12.80, "best10sKn": 10.90},
    {"id": "b1", "spot": "Malcesine", "startUtc": "2026-08-02T12:00:00Z",
     "utcOffsetS": 7200, "lat": 45.7650, "lon": 10.8100,
     "rateDurationS": 5400.0, "durationS": 5500.0, "distanceKm": 18.0,
     "foilTimeS": 2700.0, "foilPct": 50.0, "flightCount": 12, "longestFlightS": 200.0,
     "jibes": 14, "jibesSuccessful": 7, "turnsCounted": 18, "longestDryStreak": 5,
     "wetExits": 5, "best2sKn": 13.60, "best10sKn": 11.80},
    {"id": "b2", "spot": "Malcesine", "startUtc": "2026-08-03T12:00:00Z",
     "utcOffsetS": 7200, "lat": 45.7655, "lon": 10.8105,
     "rateDurationS": 3600.0, "durationS": 3700.0, "distanceKm": 11.0,
     "foilTimeS": 1980.0, "foilPct": 55.0, "flightCount": 8, "longestFlightS": 130.0,
     "jibes": 9, "jibesSuccessful": 6, "turnsCounted": 11, "longestDryStreak": 7,
     "wetExits": 3, "best2sKn": 14.40, "best10sKn": 12.60},
    {"id": "a5", "spot": "Nago Torbole", "startUtc": "2026-08-31T22:30:00Z",
     "utcOffsetS": 7200, "lat": 45.8761, "lon": 10.8711,
     "rateDurationS": 1800.0, "durationS": 1900.0, "distanceKm": 5.0,
     "foilTimeS": 720.0, "foilPct": 40.0, "flightCount": 4, "longestFlightS": 70.0,
     "jibes": 5, "jibesSuccessful": 2, "turnsCounted": 7, "longestDryStreak": 2,
     "wetExits": 3, "best2sKn": 11.90, "best10sKn": 10.20},
    {"id": "c1", "spot": "Rheinstetten", "startUtc": "2026-12-30T09:00:00Z",
     "utcOffsetS": 3600, "lat": 48.9700, "lon": 8.3200,
     "rateDurationS": 5400.0, "durationS": 5600.0, "distanceKm": 14.0,
     "foilTimeS": 2160.0, "foilPct": 40.0, "flightCount": 10, "longestFlightS": 110.0,
     "jibes": 12, "jibesSuccessful": 4, "turnsCounted": 15, "longestDryStreak": 5,
     "wetExits": 8, "best2sKn": 12.20, "best10sKn": 10.60},
    {"id": "c2", "spot": "Rheinstetten", "startUtc": "2027-02-14T09:00:00Z",
     "utcOffsetS": 3600, "lat": 48.9702, "lon": 8.3205,
     "rateDurationS": 3600.0, "durationS": 3700.0, "distanceKm": 9.0,
     "foilTimeS": 1440.0, "foilPct": 40.0, "flightCount": 6, "longestFlightS": 95.0,
     "jibes": 7, "jibesSuccessful": 3, "turnsCounted": 9, "longestDryStreak": 4,
     "wetExits": 5, "best2sKn": 11.50, "best10sKn": 9.80},
    {"id": "a6", "spot": "Nago Torbole", "startUtc": "2027-05-10T10:00:00Z",
     "utcOffsetS": 7200, "lat": None, "lon": None,
     "rateDurationS": 2400.0, "durationS": 2500.0, "distanceKm": 7.0,
     "foilTimeS": 1200.0, "foilPct": 50.0, "flightCount": 5, "longestFlightS": 100.0,
     "jibes": 3, "jibesSuccessful": 2, "turnsCounted": 5, "longestDryStreak": None,
     "wetExits": None, "best2sKn": 12.00, "best10sKn": None},
]

#: The custom ranges the fixture pins. Inclusive on both ends, in local calendar days.
PERIOD_RANGES = [
    {"start": "2026-08-01", "end": "2026-08-04"},
    {"start": None, "end": "2026-07-31"},
    {"start": "2027-01-01", "end": None},
]

PERIOD_NOTE = (
    "Generated by web/tools/make_presentation_goldens.py from PERIOD_SESSIONS — do not "
    "edit. `sessions` is the input, so both platforms build the same library from it; "
    "everything else is what web/lab_bundle/library.py makes of it, and is what the iOS "
    "PeriodTests and web/tools/verify_presentation.py 6 assert against. Python is the "
    "reference implementation (docs/presentation.md, \"Periods\").")


def period_digest(s: dict) -> dict:
    """One fixture session as the stored digest shape `library` reads.

    Only the fields periods touch, so the fixture stays readable: it is a contract about
    trips, months, seasons and one block, not a second copy of the digest schema.
    """
    epoch = library._epoch(s["startUtc"])
    geo = None if s.get("lat") is None else {"lat": s["lat"], "lon": s["lon"]}
    return {
        "schema": library.SCHEMA, "id": s["id"], "fileName": f"{s['id']}.fit",
        "spot": s["spot"], "startUtc": s["startUtc"], "startEpoch": epoch,
        "dateUtc": s["startUtc"][:10],
        "dateLocal": library._local_date(epoch, s["utcOffsetS"]),
        "utcOffsetS": s["utcOffsetS"], "geo": geo,
        "durationS": s["durationS"], "rateDurationS": s["rateDurationS"],
        "distanceKm": s["distanceKm"], "foilTimeS": s["foilTimeS"], "foilPct": s["foilPct"],
        "flightCount": s["flightCount"], "longestFlightS": s["longestFlightS"],
        "wetExits": s["wetExits"],
        "records": {"best2sKn": s["best2sKn"], "best10sKn": s["best10sKn"]},
        "turns": {"counted": s["turnsCounted"], "jibes": s["jibes"],
                  "jibesSuccessful": s["jibesSuccessful"],
                  "longestDryStreak": s["longestDryStreak"]},
    }


def period_facts() -> dict:
    digests = [period_digest(s) for s in PERIOD_SESSIONS]
    out = library.periods(digests)
    return {
        "note": PERIOD_NOTE,
        "rules": {"tripGapDays": library.TRIP_GAP_DAYS,
                  "tripMinSessions": library.TRIP_MIN_SESSIONS,
                  "tripRadiusM": library.TRIP_RADIUS_M,
                  "seasonStartMonth": library.SEASON_START_MONTH,
                  "minJibesForRate": library.MIN_JIBES_FOR_RATE,
                  "blockOrder": [key for key, _l, _f in library.PERIOD_BLOCK],
                  "leanKeys": list(library.PERIOD_LEAN_KEYS)},
        "sessions": PERIOD_SESSIONS,
        "trips": out["trips"],
        "months": out["months"],
        "seasons": out["seasons"],
        "custom": [{"start": r["start"], "end": r["end"],
                    **library.custom_period(digests, r["start"], r["end"])}
                   for r in PERIOD_RANGES],
    }


def goldens() -> list[Path]:
    return sorted(p for p in GOLDENS.glob(f"*{SUFFIX}"))


def artifacts() -> dict[Path, str]:
    out: dict[Path, str] = {}
    for path in goldens():
        stem = path.name[: -len(SUFFIX)]
        doc = json.loads(path.read_text(encoding="utf-8"))
        out[OUT / f"{stem}{SUFFIX}"] = render(stem, doc)
    out[PERIODS_OUT] = json.dumps(period_facts(), indent=2, ensure_ascii=False) + "\n"
    return out


def write() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    built = artifacts()
    for path, content in built.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    for orphan in sorted(OUT.glob(f"*{SUFFIX}")):
        if orphan not in built:
            orphan.unlink()
            print(f"  - {orphan.relative_to(REPO).as_posix()} (no analysis golden)")
    print(f"presentation goldens written: {len(built)}")
    for path in sorted(built):
        print(f"  {path.relative_to(REPO).as_posix()}")
    return 0


def check() -> int:
    stale = []
    built = artifacts()
    for path, content in built.items():
        have = path.read_text(encoding="utf-8") if path.exists() else None
        if have != content:
            stale.append(path.relative_to(REPO).as_posix())
    for extra in sorted(OUT.glob(f"*{SUFFIX}")):
        if extra not in built:
            stale.append(extra.relative_to(REPO).as_posix())
    if stale:
        print("presentation goldens are STALE — run: "
              "python3 web/tools/make_presentation_goldens.py", file=sys.stderr)
        for name in stale:
            print(f"  differs: {name}", file=sys.stderr)
        return 1
    print(f"presentation goldens are current ({len(built)} fixtures)")
    return 0


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="verify only; do not write")
    args = ap.parse_args(argv)
    return check() if args.check else write()


if __name__ == "__main__":
    raise SystemExit(main())
