#!/usr/bin/env python3
"""``web/js/copy.js`` — the handful of docs/copy strings the analyzer has to SAY.

    python3 web/tools/make_copy_js.py            # write web/js/copy.js
    python3 web/tools/make_copy_js.py --check    # exit 1 if it is stale

The rest of the copy contract is checked against pages (``verify_copy.py``). This is the
part the browser has to render at run time, from a verdict the engine computes milliseconds
earlier: a recording with no foil time that went nowhere is **not a session**
(docs/algorithms/not-a-session.md, "Not a session", engine 0.19.0). The phone tags such a row and says
why; the analyzer computed the same verdict from the same engine and said nothing about it.

There is no build step on this site and no JSON fetch on the session path — the analyzer
already waits for Pyodide, and a second round trip for four sentences would be four
sentences that can fail to arrive. So the strings are inlined here, generated, and
``verify_links.py`` fails while the file is stale. Stdlib only.

WHAT IS IN IT

  ``NOT_A_SESSION``  verdicts.json → ``notASession``: the tag and the two lines, with
                     ``{duration}`` and ``{distance}`` left in place. js/render.js fills
                     them the way ``NotASessionNote.swift`` does.
  ``PHRASES``        phrases.json → ``promise``, ``callToAction``, ``captionOffer``. The
                     three sentences the product says about itself, available to any
                     renderer on this side of the site.
  ``GLOSSARY``       glossary.json → every entry's ``id``, ``term`` and ``line``. The
                     analyzer's ``?`` beside the key-metrics block opens them (ux-audit
                     A3.2: the page printed ``On foil``, ``JPH``, ``CPH``, ``WPH`` and the
                     outcome ladder and had no definition anywhere in it). Only those three
                     keys are read and every other key on an entry is ignored on purpose —
                     the kit is adding fields to these entries (``short``, ``sentence``,
                     ``surfaces``) and a generator that copied whatever it found would put
                     the watch's cell budget into a browser bundle, while one that DEMANDED
                     the three keys would fail on the day a fourth arrived. ``/learn/``'s
                     definition list stays pinned by ``verify_copy.py`` against the same
                     file; this is the same eight lines, rendered rather than authored.

WHAT IS NOT, and why: ``js/cardstats.js``'s ``BRANDING`` stays where it is. It does not
hold ``callToAction`` — it holds the two PARTS the card draws separately (``cta`` on one
line, ``site`` under the QR) and composes the sentence from them. Reading the composed
string here and splitting it back apart would be a worse contract than the one
``verify_copy.py`` already enforces, which re-does the composition and compares.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

WEB = Path(__file__).resolve().parents[1]
REPO = WEB.parent
COPY = REPO / "docs" / "copy"
OUT = WEB / "js" / "copy.js"

HEADER = '''/* GENERATED by web/tools/make_copy_js.py from docs/copy/ — do not edit.
 *
 * The rider-facing sentences this site has to say at run time. docs/copy/README.md holds
 * the contract: the kit is the author, the JSON is the artefact, and both sides are pinned
 * — `CopyContractTests` on the Swift side, `web/tools/verify_copy.py` on the pages and
 * `make_copy_js.py --check` (run by verify_links.py) on this file.
 *
 * Regenerate after a deliberate wording change:
 *
 *     cd ios/WingFoilKit && COPY_WRITE=1 swift test --filter CopyContractTests
 *     python3 web/tools/make_copy_js.py
 */

'''


def render() -> str:
    verdicts = json.loads((COPY / "verdicts.json").read_text(encoding="utf-8"))
    phrases = json.loads((COPY / "phrases.json").read_text(encoding="utf-8"))
    glossary = json.loads((COPY / "glossary.json").read_text(encoding="utf-8"))

    def js(value, indent=2):
        return json.dumps(value, ensure_ascii=False, indent=indent)

    not_a_session = verdicts["notASession"]
    picked = {key: phrases[key] for key in ("promise", "callToAction", "captionOffer")}
    # Three keys, in the JSON's own order, and anything else on an entry is left behind.
    terms = [{key: entry[key] for key in ("id", "term", "line")}
             for entry in glossary["entries"]]

    return HEADER + (
        "/**\n"
        " * What the rider is told about a recording that is not a session — the kit's\n"
        " * `NotASessionNote` (docs/copy/verdicts.json).\n"
        " *\n"
        " * `lines[0]` is the no-recording case, which the analyzer cannot reach: it only\n"
        " * ever sees a file somebody dropped on it. `lines[1]` is the short /\n"
        " * went-nowhere case, and carries `{duration}` (m:ss under an hour, h:mm:ss over\n"
        " * it) and `{distance}` (metres under a kilometre, otherwise one decimal of km) —\n"
        " * the row's own displayed numbers, so the line reads against the key metrics\n"
        " * directly above it.\n"
        " */\n"
        "export const NOT_A_SESSION = %s;\n\n"
        "/** The three sentences the product says about itself (docs/copy/phrases.json). */\n"
        "export const PHRASES = %s;\n\n"
        "/**\n"
        " * The words the product is made of, one line each — the kit's `MetricGlossary`\n"
        " * (docs/copy/glossary.json), which /learn/'s definition list carries and the\n"
        " * analyzer's `?` beside the key-metrics block opens.\n"
        " *\n"
        " * `id` is a slug that outlives a rewording, so it is what a caller keys on.\n"
        " * Entries carry other fields in the JSON; only these three are copied here.\n"
        " */\n"
        "export const GLOSSARY = %s;\n" % (js(not_a_session), js(picked), js(terms)))


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true",
                        help="exit 1 if web/js/copy.js is stale")
    args = parser.parse_args(argv)

    text = render()
    if args.check:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != text:
            print("stale, run `python3 web/tools/make_copy_js.py`: %s"
                  % OUT.relative_to(REPO), file=sys.stderr)
            return 1
        print("js/copy.js: the not-a-session words and the three phrases, from docs/copy")
        return 0

    OUT.write_text(text, encoding="utf-8")
    print("wrote %s" % OUT.relative_to(REPO))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
