#!/usr/bin/env python3
"""Derive `fixtures/presentation/*.expected.json` from the analysis goldens.

The analysis goldens say what the engine found; these say what a UI is allowed to *draw*
from it. They are the second half of docs/presentation.md's enforcement: both the iOS app
(`PresentationTests.presentationGoldensMatch`) and the web verification
(`web/tools/verify_presentation.py`) assert exactly these numbers, so a marker that
appears on one platform and not on the other is a failing test rather than a bug report a
year later.

    python3 web/tools/make_presentation_goldens.py            # write
    python3 web/tools/make_presentation_goldens.py --check     # exit 1 if stale

Nothing here re-derives a metric: every fact is a *count of what survives an eligibility
rule*, and every rule is written down in docs/presentation.md:

  * turns with `counted == false` are course changes — never an outcome marker, never in a
    tally, never in a trend;
  * a flight end already owned by a turn would double-mark the same swim, and a truncated
    end is a recording that stopped, not an event;
  * pump episodes: only `success` and `failed` are attempts; `recovery`, `in_flight` and
    `unknown` are counted by the engine but never drawn;
  * splash evidence comes from the engine's `submerged` flags and is never re-derived;
  * turn filters are type × ENTRY side, ANDed, over counted turns only;
  * every flight is started by one takeoff and stopped by one end, so the takeoff halves
    and the flight-end buckets each sum to `flightCount`.

Stdlib only, and byte-stable: two runs produce identical files.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

WEB = Path(__file__).resolve().parents[1]
REPO = WEB.parent
GOLDENS = REPO / "fixtures" / "goldens"
OUT = REPO / "fixtures" / "presentation"

SUFFIX = ".expected.json"

# docs/presentation.md "Record windows": eight kinds, canonical order, best2s default.
RECORD_ORDER = ["best2s", "best10s", "best5x10s", "best100m", "best250m", "best500m",
                "bestNm", "alpha500"]
RECORD_DEFAULT = "best2s"

TYPE_FILTERS = ["both", "jibes", "tacks"]
SIDE_FILTERS = ["both", "port", "starboard"]

NOTE = ("Generated by web/tools/make_presentation_goldens.py from "
        "fixtures/goldens/ — do not edit. Asserted by ios PresentationTests and by "
        "web/tools/verify_presentation.py; a count that differs between the platforms "
        "is a failing test, not a bug report (docs/presentation.md).")


# ------------------------------------------------------------------- the rules


def outcome_layer(outcome: str) -> str:
    """The ladder: fell in, touchdown, everything else flew. `glide_out` is a flight that
    ended without drama, which is the green end of the ladder — the iOS app's
    `outcomeTone` reads it exactly this way."""
    if outcome == "fell_in":
        return "fellIn"
    if outcome == "touchdown":
        return "touchdown"
    return "flewThrough"


def drawn_flight_ends(doc: dict) -> list[dict]:
    """Straight-line flight ends: the ones no turn already explains, from a recording that
    did not simply stop."""
    return [e for e in doc.get("flightEnds", [])
            if e.get("ownedByTurn") is None and not e.get("truncated", False)]


def marker_counts(doc: dict) -> dict[str, int]:
    counts = {"flewThrough": 0, "touchdown": 0, "fellIn": 0, "courseChange": 0}
    for turn in doc.get("turns", []):
        layer = outcome_layer(turn["outcome"]) if turn.get("counted") else "courseChange"
        counts[layer] += 1
    for end in drawn_flight_ends(doc):
        counts[outcome_layer(end["outcome"])] += 1
    return counts


def clean_jibe_count(doc: dict) -> int:
    """The star layer: counted, named a jibe, and passed the engine's own `success` flag
    (docs/presentation.md, "Clean jibe").

    Deliberately **not** one of `marker_counts`: those partition the turns and the drawn
    flight ends one mark each, and a clean jibe is already counted there under whatever
    outcome it ended on. This is the second, stricter reading laid over the same set.
    """
    return sum(1 for t in doc.get("turns", [])
               if t.get("counted") and t["type"] == "jibe" and t["success"])


def takeoff_counts(doc: dict) -> dict[str, int]:
    """Both halves of the takeoff layer. Every entry in `takeoffs` flew (the engine only
    writes one for a flight that happened); the failures are the pumping episodes the
    classifier called `failed`, which is the only block that gives them a time."""
    takeoffs = doc.get("takeoffs", [])
    free = sum(1 for k in takeoffs if k.get("free"))
    failed = sum(1 for ep in doc.get("pumpEpisodes", []) if ep["outcome"] == "failed")
    pumped = len(takeoffs) - free
    return {"pumped": pumped, "free": free, "failed": failed,
            "total": pumped + free + failed}


def flight_end_counts(doc: dict) -> dict[str, int]:
    """Every flight end, in the three buckets the marker rules already distinguish.

    `drawn` is the hollow mark; `ownedByTurn` is the end a turn's outcome window already
    explains (marking both would draw one swim twice); `truncated` is a recording that
    stopped rather than a flight that ended. They partition the block, so `total` is also
    the flight count — the invariant `check_flight_invariants` asserts.
    """
    ends = doc.get("flightEnds", [])
    owned = sum(1 for e in ends if e.get("ownedByTurn") is not None
                and not e.get("truncated", False))
    truncated = sum(1 for e in ends if e.get("truncated", False))
    return {"drawn": len(drawn_flight_ends(doc)), "ownedByTurn": owned,
            "truncated": truncated, "total": len(ends)}


def splash_count(doc: dict) -> int:
    """The barometer's evidence on both channels, with the same ownership rule that keeps
    one swim from being marked twice."""
    turns = sum(1 for t in doc.get("turns", []) if t.get("submerged") and t.get("counted"))
    ends = sum(1 for e in drawn_flight_ends(doc) if e.get("submerged"))
    return turns + ends


def pumping_spans(doc: dict) -> int:
    """Pump-burst spans: the attempts, and only the attempts."""
    return sum(1 for ep in doc.get("pumpEpisodes", [])
               if ep["outcome"] in ("success", "failed"))


def record_windows(doc: dict) -> list[str]:
    """The records this session can actually highlight: a value *and* the window
    provenance the map draws. `bestHour` is deliberately not in the catalogue."""
    records = doc.get("records", {})
    windows = records.get("windows", {}) or {}
    out = []
    for key in RECORD_ORDER:
        value = records.get(f"{key}Kn")
        window = windows.get(key)
        if value is None or value <= 0 or not window:
            continue
        out.append(key)
    return out


def accepts_type(kind: str, turn_type: str) -> bool:
    if kind == "both":
        return True
    return turn_type == ("jibe" if kind == "jibes" else "tack")


def accepts_side(side: str, turn_side: str) -> bool:
    return True if side == "both" else turn_side == side


def filter_tallies(doc: dict) -> list[dict]:
    """Every type × entry-side combination, with the flew-through share's numerator. Side
    is the tack the turn was ENTERED on, never the rotation direction."""
    counted = [t for t in doc.get("turns", []) if t.get("counted")]
    out = []
    for kind in TYPE_FILTERS:
        for side in SIDE_FILTERS:
            kept = [t for t in counted
                    if accepts_type(kind, t["type"]) and accepts_side(side, t["side"])]
            flew = sum(1 for t in kept if outcome_layer(t["outcome"]) == "flewThrough")
            out.append({"type": kind, "side": side, "count": len(kept),
                        "flewThrough": flew})
    return out


def facts(stem: str, doc: dict) -> dict:
    """Everything a UI may draw from this analysis, as counts."""
    windows = record_windows(doc)
    return {
        "fixture": stem,
        "engineVersion": doc.get("engineVersion"),
        "source": f"fixtures/goldens/{stem}{SUFFIX}",
        "generator": "web/tools/make_presentation_goldens.py",
        "note": NOTE,
        # The engine's own count, and the two blocks that must add up to it: one takeoff
        # starts every flight, one end stops it (docs/presentation.md "Enforcement" 3).
        "flightCount": doc.get("summary", {}).get("flightCount"),
        "markers": marker_counts(doc),
        "cleanJibes": clean_jibe_count(doc),
        "flightEnds": flight_end_counts(doc),
        "takeoff": takeoff_counts(doc),
        "splash": splash_count(doc),
        "pumpingSpans": pumping_spans(doc),
        "recordWindows": windows,
        "defaultRecordWindow": RECORD_DEFAULT if RECORD_DEFAULT in windows else None,
        "filters": filter_tallies(doc),
    }


# -------------------------------------------------------------------- the files


def render(stem: str, doc: dict) -> str:
    return json.dumps(facts(stem, doc), indent=2, ensure_ascii=False) + "\n"


def goldens() -> list[Path]:
    return sorted(p for p in GOLDENS.glob(f"*{SUFFIX}"))


def artifacts() -> dict[Path, str]:
    out: dict[Path, str] = {}
    for path in goldens():
        stem = path.name[: -len(SUFFIX)]
        doc = json.loads(path.read_text(encoding="utf-8"))
        out[OUT / f"{stem}{SUFFIX}"] = render(stem, doc)
    return out


def write() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    built = artifacts()
    for path, content in built.items():
        path.write_text(content, encoding="utf-8")
    for orphan in sorted(OUT.glob(f"*{SUFFIX}")):
        if orphan not in built:
            orphan.unlink()
            print(f"  - {orphan.relative_to(REPO).as_posix()} (no analysis golden)")
    print(f"presentation goldens written: {len(built)}")
    for path in sorted(built):
        print(f"  {path.relative_to(REPO).as_posix()}")
    return 0


def check() -> int:
    stale = []
    built = artifacts()
    for path, content in built.items():
        have = path.read_text(encoding="utf-8") if path.exists() else None
        if have != content:
            stale.append(path.relative_to(REPO).as_posix())
    for extra in sorted(OUT.glob(f"*{SUFFIX}")):
        if extra not in built:
            stale.append(extra.relative_to(REPO).as_posix())
    if stale:
        print("presentation goldens are STALE — run: "
              "python3 web/tools/make_presentation_goldens.py", file=sys.stderr)
        for name in stale:
            print(f"  differs: {name}", file=sys.stderr)
        return 1
    print(f"presentation goldens are current ({len(built)} fixtures)")
    return 0


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="verify only; do not write")
    args = ap.parse_args(argv)
    return check() if args.check else write()


if __name__ == "__main__":
    raise SystemExit(main())
