#!/usr/bin/env python3
"""Analyse the bundled example once, here, so the browser can show it without Pyodide.

"Try the example" used to run `web/example/ExampleSession.fit` through the engine in the
tab, which on a first visit meant waiting out the whole ~14 MB runtime download before a
single number appeared (rider review X4, 9 Oct 2026). The recording never changes and the
engine is the one this repo pins, so the answer is the same every time: this script works
it out at build time, with the same `web_entry.analyze_bytes` call and the same
`library.digest` the worker makes, and writes it beside the recording as
`web/example/ExampleSession.analysis.json`. The page draws that file straight away and
lets the runtime load in the background for the rider's own file.

    lab/.venv/bin/python web/tools/make_example.py            # write
    lab/.venv/bin/python web/tools/make_example.py --check    # exit 1 if stale

`web/tools/bundle_lab.py` runs it after every bundle, so an engine change regenerates the
example with the bundle; `bundle_lab.py --check` and `verify_first_run.py` fail on a file
stamped with another engine or built from other sources (stdlib only, `stamp_problems`),
and `--check` here regenerates it in memory and compares the bytes.

The file carries one presentation document per Settings → Speed records choice, because the
presentation is the one part of the analysis that takes a rider input (ADR-033). The page
picks the one the rider has set, so the example reads the way his own file would.

Byte-stable: two runs over the same sources write identical files.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path

WEB = Path(__file__).resolve().parents[1]
REPO = WEB.parent
FIT = WEB / "example" / "ExampleSession.fit"
OUT = WEB / "example" / "ExampleSession.analysis.json"
LAB_SRC = REPO / "lab" / "src" / "wingfoil_lab"
#: The browser-only Python the document is also built by (bundle_lab.py's GLUE).
GLUE = [WEB / "lab_bundle" / "web_entry.py", WEB / "lab_bundle" / "library.py"]
#: The name the page hands the worker for the example, so the digest's file name and spot
#: are the ones a live analysis would store (js/app.js, `EXAMPLE_NAME`).
NAME = "example-nago-torbole-2026-08-30.fit"
NOTE = ("Generated by web/tools/make_example.py from web/example/ExampleSession.fit. Do not "
        "edit. Re-run web/tools/bundle_lab.py after any engine change.")


# ------------------------------------------------------------------ stdlib: the stamp


def engine_version() -> str:
    """`ENGINE_VERSION` out of the lab's `__init__.py`, without importing the engine."""
    text = (LAB_SRC / "__init__.py").read_text()
    m = re.search(r'^ENGINE_VERSION\s*=\s*"([^"]+)"', text, re.M)
    if not m:
        raise SystemExit("ENGINE_VERSION not found in lab/src/wingfoil_lab/__init__.py")
    return m.group(1)


def inputs_digest() -> str:
    """One hash over everything the document is a function of: every lab module, the two
    glue modules and the recording. A change to any of them that moves no version number
    still makes the shipped answer stale, and this is what notices."""
    h = hashlib.sha256()
    sources = sorted(p for p in LAB_SRC.rglob("*.py") if "__pycache__" not in p.parts)
    for p in sources + GLUE + [FIT]:
        rel = p.relative_to(REPO).as_posix()
        h.update(rel.encode() + b"\0" + hashlib.sha256(p.read_bytes()).digest())
    return h.hexdigest()[:16]


def stamp_problems() -> list[str]:
    """What is wrong with the shipped file's stamp, without running the engine. Empty when
    it is current."""
    if not OUT.exists():
        return [f"{OUT.relative_to(REPO)} is missing"]
    try:
        have = json.loads(OUT.read_text())
    except ValueError as err:
        return [f"{OUT.relative_to(REPO)} is not JSON: {err}"]
    problems = []
    want = engine_version()
    if have.get("engineVersion") != want:
        problems.append(f"stamped engine {have.get('engineVersion')}, the lab is {want}")
    if (have.get("document") or {}).get("engineVersion") != want:
        problems.append("the document inside carries another engine version")
    if have.get("inputs") != inputs_digest():
        problems.append("built from other engine sources or another recording")
    return problems


# ------------------------------------------------------------- the engine: generate


def build() -> str:
    """The file's bytes, from the engine as it stands."""
    sys.path.insert(0, str(WEB / "lab_bundle"))
    # The authoritative lab ahead of the bundle's copy, as make_presentation_goldens.py
    # does: bundle_lab.py --check proves the two are the same sources.
    sys.path.insert(0, str(REPO / "lab" / "src"))
    import library                                                      # noqa: E402
    import web_entry                                                    # noqa: E402
    from wingfoil_lab.presentation import (DEFAULT_SPEED_RECORD_POLICY,  # noqa: E402
                                           SPEED_RECORD_POLICIES)

    raw = FIT.read_bytes()
    # `example=True`: the one session the 20-minute rate floor exempts (Jan, 9 Oct 2026).
    doc = web_entry.analyze_bytes(raw, NAME, DEFAULT_SPEED_RECORD_POLICY, example=True)
    # Round-tripped through the worker's own serialization, so the page parses exactly
    # what `analyze_json` would have posted.
    doc = json.loads(json.dumps(doc, allow_nan=False))
    presentations = {p: web_entry.presentation(doc["golden"], doc["meta"], p, example=True)
                     for p in SPEED_RECORD_POLICIES}
    payload = {
        "note": NOTE,
        "engineVersion": doc["engineVersion"],
        "inputs": inputs_digest(),
        "fitBytes": len(raw),
        "fitSha256": hashlib.sha256(raw).hexdigest(),
        "name": NAME,
        "defaultPolicy": DEFAULT_SPEED_RECORD_POLICY,
        "document": doc,
        "presentations": presentations,
        "digest": json.loads(library.digest_json(json.dumps(doc, allow_nan=False), NAME)),
    }
    return json.dumps(payload, allow_nan=False, separators=(",", ":")) + "\n"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="regenerate in memory and compare (exit 1 if stale), write nothing")
    args = ap.parse_args(argv)
    text = build()
    rel = OUT.relative_to(REPO)
    if args.check:
        if not OUT.exists() or OUT.read_text() != text:
            print(f"{rel} is STALE. Run: lab/.venv/bin/python web/tools/make_example.py",
                  file=sys.stderr)
            return 1
        print(f"{rel} is current (engine {engine_version()}, {len(text) // 1024} KB)")
        return 0
    OUT.write_text(text)
    print(f"wrote {rel} (engine {engine_version()}, {len(text) // 1024} KB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
