#!/usr/bin/env python3
"""Generate the presentation-token artifacts from `design/tokens.json`.

`docs/presentation.md` defines what the marks *mean*; this generator is how their
*values* reach the two implementations without either one holding a private copy:

    design/tokens.json                                     <- the only file a human edits
      -> ios/WingFoilKit/Sources/WingFoilKit/Presentation/DesignTokens.swift
      -> web/css/tokens.css
      -> web/js/tokens.js
      -> garmin/source/DesignTokens.mc

    python3 design/generate_tokens.py            # write the four artifacts
    python3 design/check_tokens.py --check       # fail (exit 1) if any of them is stale

Every colour carries two forms — a hex for the web and a semantic SwiftUI colour for
iOS — because the platforms genuinely differ: `Color.green` follows the system's light
and dark palettes and the accessibility settings, and pinning it to #0ca30c would make
the iOS app *worse*, not more consistent. The token is the pair; each side consumes its
own half, and this file is what keeps the halves in one place.

The watch takes the hex half, like the web: `Dc.setColor` accepts a literal 0xRRGGBB on
every product in the manifest. It additionally gets a *second* literal per token, the
nearest colour in the 64-entry {00,55,AA,FF}^3 palette the 8 bpp MIP variants quantise
to — see `monkeyc()` for why that is written down rather than left to the firmware.

Stdlib only, and byte-stable: the output is a pure function of tokens.json, so two runs
produce identical bytes and CI can compare them.
"""

from __future__ import annotations

import json
from pathlib import Path

DESIGN = Path(__file__).resolve().parent
REPO = DESIGN.parent
TOKENS = DESIGN / "tokens.json"

SWIFT_OUT = (REPO / "ios" / "WingFoilKit" / "Sources" / "WingFoilKit" / "Presentation"
             / "DesignTokens.swift")
CSS_OUT = REPO / "web" / "css" / "tokens.css"
JS_OUT = REPO / "web" / "js" / "tokens.js"
MONKEYC_OUT = REPO / "garmin" / "source" / "DesignTokens.mc"

BANNER = ("Generated by design/generate_tokens.py from design/tokens.json — do not edit.\n"
          "Edit the tokens, re-run the generator, and commit all four files together;\n"
          "design/check_tokens.py --check fails the build on drift.")

# The Monkey C file joined the set last and carries its own line, so the three older
# artifacts stay byte-identical to what they were before the watch was wired in — a
# generator change must not show up as a diff in files whose CONTENT did not change.
MONKEYC_BANNER = ("Generated by design/generate_tokens.py from design/tokens.json — "
                  "do not edit.\n"
                  "Edit the tokens, re-run the generator, and commit every generated file\n"
                  "together; design/check_tokens.py --check fails the build on drift.")

# The colour groups, in the order every artifact emits them. `side` and then `clean` are
# last because they joined the set last (docs/app-ui-review.md §5.2/§5.3; the clean-jibe
# star, engine 0.10.0), and appending rather than inserting keeps every line above them
# byte-identical to what it was before.
GROUPS = ("outcome", "effort", "phase", "direction", "side", "clean")

# What the **watch** emits, which is a subset and always will be. The watch draws no
# clean-jibe mark — the star is a phone-and-web affordance on a map neither of which the
# watch has — and a fixed RGB written into `DesignTokens.mc` for a token nothing there can
# draw is a value with no meaning, which is exactly what that file exists to prevent.
# A group added here without a use on the watch would also rewrite a generated file under
# `garmin/` for no behavioural reason.
MONKEYC_GROUPS = ("outcome", "effort", "phase", "direction", "side")


def load() -> dict:
    return json.loads(TOKENS.read_text(encoding="utf-8"))


# ------------------------------------------------------------------ small helpers


def _kebab(name: str) -> str:
    """`failedTakeoff` -> `failed-takeoff` (CSS custom-property spelling)."""
    out = []
    for ch in name:
        if ch.isupper():
            out.append("-")
            out.append(ch.lower())
        else:
            out.append(ch)
    return "".join(out)


def _num(value: float) -> str:
    """A JSON number as the shortest exact literal (0.42, not 0.42000000000000004)."""
    text = repr(float(value))
    return text[:-2] if text.endswith(".0") else text


def _swift_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _swift_color(spec: dict) -> str:
    """`Color.brown`, or `Color.brown.opacity(0.55)` for a second lightness of one hue.

    The optional `swiftUIOpacity` exists for a token pair that is deliberately ONE hue at
    two intensities — the port/starboard pair, where two *different* hues would be a second
    vocabulary nobody asked for. Opacity rather than a lighter literal because iOS renders
    these over a background that may be light or dark, and "toward the background" is the
    only spelling of "the quieter half of the pair" that is true in both.
    """
    expression = f"Color.{spec['swiftUI']}"
    if "swiftUIOpacity" in spec:
        expression += f".opacity({_num(spec['swiftUIOpacity'])})"
    return expression


def _comment_block(lines: list[str], prefix: str) -> list[str]:
    return [f"{prefix} {line}".rstrip() for line in lines]


def _screaming(group: str, name: str) -> str:
    """`phase` + `offFoil` -> `PHASE_OFF_FOIL` (Monkey C constant spelling)."""
    return (group + "-" + _kebab(name)).replace("-", "_").upper()


def _rgb(hex_value: str) -> tuple[int, int, int]:
    raw = hex_value.lstrip("#")
    return int(raw[0:2], 16), int(raw[2:4], 16), int(raw[4:6], 16)


# The 8 bpp MIP products (fenix 8 Solar, the whole fenix 7 family) render a fixed
# 64-colour palette: every channel is one of these four levels.
MIP_LEVELS = (0x00, 0x55, 0xAA, 0xFF)


def _mip(hex_value: str) -> str:
    """The nearest colour in the MIP palette, as a 0xRRGGBB literal."""
    snapped = [min(MIP_LEVELS, key=lambda level: abs(level - c)) for c in _rgb(hex_value)]
    return "0x%02X%02X%02X" % tuple(snapped)


def _amoled(hex_value: str) -> str:
    return "0x" + hex_value.lstrip("#").upper()


# ------------------------------------------------------------------------- Swift


def swift(tokens: dict) -> str:
    colors = tokens["colors"]
    lines: list[str] = []
    lines += _comment_block(BANNER.splitlines(), "//")
    lines += [
        "//",
        "// Contract: docs/presentation.md — the meanings. This file carries only values.",
        "",
        "import SwiftUI",
        "",
        "/// The presentation palette, generated from `design/tokens.json`.",
        "///",
        "/// iOS consumes the *semantic* half of each token (`Color.green`, `Color.teal`, …)",
        "/// so the marks keep following the system's light/dark and accessibility palettes;",
        "/// the web consumes the hex half. `Hex` is carried here too, not for drawing, but",
        "/// so a test can hold the two halves of a token against each other.",
        "public enum DesignTokens {",
        "",
    ]

    groups = [
        ("Outcome", "outcome",
         "The verdict ladder. Nothing outside a maneuver outcome may borrow it."),
        ("Effort", "effort",
         "Effort and water: deliberately outside the ladder — nothing here is a verdict."),
        ("Phase", "phase", "Track tint by phase."),
        ("Direction", "direction",
         "Course-of-travel chevrons: ink plus opacity, never a hue of its own."),
        ("Side", "side",
         "Entry tack. A side is not a verdict, so it may borrow neither the ladder nor the\n"
         "    /// effort inks: one hue at two intensities, and the quieter half is dashed."),
        ("Clean", "clean",
         "The strict verdict's own ink. Clean is what a jibe *cost*; the ladder's green is\n"
         "    /// how it *ended*, and the two disagree on purpose — so the clean mark carries a\n"
         "    /// green of its own and never the ladder's."),
    ]
    for swift_name, key, doc in groups:
        lines.append(f"    /// {doc}")
        lines.append(f"    public enum {swift_name} {{")
        for token, spec in colors[key].items():
            lines.append(f"        /// {spec['means']}")
            lines.append(f"        public static let {token} = {_swift_color(spec)}")
        lines.append("    }")
        lines.append("")

    lines.append("    /// Opacities the chevrons are drawn at, per phase (web uses its own).")
    lines.append("    public enum Opacity {")
    for name, value in tokens["opacity"].items():
        lines.append(f"        public static let {name}: Double = {_num(value)}")
    lines.append("    }")
    lines.append("")

    lines.append("    /// SF Symbols. Shape is a channel of its own — see the contract.")
    lines.append("    public enum Glyph {")
    for name, spec in tokens["glyphs"].items():
        lines.append(f"        /// {spec['means']}")
        lines.append(f"        public static let {name} = {_swift_string(spec['sfSymbol'])}")
    lines.append("    }")
    lines.append("")

    lines.append("    /// The hex half of every colour token — what the web renders. Not used")
    lines.append("    /// for drawing on iOS; it exists so the two halves stay in one file.")
    lines.append("    public enum Hex {")
    for group_key in GROUPS:
        for token, spec in colors[group_key].items():
            name = group_key + token[0].upper() + token[1:]
            lines.append(f"        public static let {name} = {_swift_string(spec['hex'])}")
    lines.append("    }")
    lines.append("")

    records = tokens["recordWindows"]
    lines += [
        "    /// The record picker: canonical order, display labels, and the window every",
        "    /// session opens on.",
        "    public enum RecordWindows {",
        f"        public static let defaultID = {_swift_string(records['default'])}",
        "        public static let catalogue: [DesignTokenEntry] = [",
    ]
    for entry in records["order"]:
        lines.append(f"            DesignTokenEntry(id: {_swift_string(entry['id'])}, "
                     f"label: {_swift_string(entry['label'])}),")
    lines += [
        "        ]",
        "        public static let order: [String] = catalogue.map(\\.id)",
        "    }",
        "",
        "    /// The legend's layer catalogue: ids, chip text, and which layers a rider who",
        "    /// has never touched a chip sees.",
        "    public enum Layers {",
        "        public static let catalogue: [DesignTokenEntry] = [",
    ]
    for entry in tokens["layers"]:
        lines.append(f"            DesignTokenEntry(id: {_swift_string(entry['id'])}, "
                     f"label: {_swift_string(entry['label'])}),")
    lines += [
        "        ]",
        "        public static let order: [String] = catalogue.map(\\.id)",
        "        public static let visibleByDefault: [String] = [",
    ]
    for entry in tokens["layers"]:
        if entry["defaultVisible"]:
            lines.append(f"            {_swift_string(entry['id'])},")
    lines += [
        "        ]",
        "    }",
        "}",
        "",
        "/// One catalogue row: the id the code switches on, and the words the rider reads.",
        "public struct DesignTokenEntry: Sendable, Equatable, Identifiable {",
        "    public let id: String",
        "    public let label: String",
        "",
        "    public init(id: String, label: String) {",
        "        self.id = id",
        "        self.label = label",
        "    }",
        "}",
        "",
    ]
    return "\n".join(lines)


# --------------------------------------------------------------------------- CSS


def css(tokens: dict) -> str:
    lines: list[str] = ["/*"]
    lines += _comment_block(BANNER.splitlines(), " ")
    lines += [
        "",
        "  Contract: docs/presentation.md. Loaded before css/style.css, which reads these",
        "  through its own semantic names (--good, --track, …).",
        "*/",
        "",
        ":root {",
    ]
    for group in GROUPS:
        lines.append(f"  /* {group} */")
        for token, spec in tokens["colors"][group].items():
            lines.append(f"  --wf-{group}-{_kebab(token)}: {spec['hex']};")
    lines.append("  /* opacity */")
    for name, value in tokens["opacity"].items():
        lines.append(f"  --wf-opacity-{_kebab(name)}: {_num(value)};")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------- JS


def js(tokens: dict) -> str:
    payload = {
        **{group: {k: {"hex": v["hex"], "swiftUI": v["swiftUI"]}
                   for k, v in tokens["colors"][group].items()}
           for group in GROUPS},
        "opacity": dict(tokens["opacity"]),
        "glyphs": {k: {"sfSymbol": v["sfSymbol"], "webShape": v["webShape"]}
                   for k, v in tokens["glyphs"].items()},
        "recordWindows": {"default": tokens["recordWindows"]["default"],
                          "order": [dict(e) for e in tokens["recordWindows"]["order"]]},
        "layers": [dict(e) for e in tokens["layers"]],
    }
    body = json.dumps(payload, indent=2, ensure_ascii=False, sort_keys=False)
    lines = ["/*"]
    lines += _comment_block(BANNER.splitlines(), " ")
    lines += [
        "",
        "  Contract: docs/presentation.md. js/viz.js maps these onto its own names (C.good,",
        "  C.foil, …) so nothing downstream has to know a token from a literal.",
        "*/",
        "",
        f"export const TOKENS = {body};",
        "",
    ]
    return "\n".join(lines)


# ----------------------------------------------------------------------- Monkey C


def monkeyc(tokens: dict) -> str:
    colors = tokens["colors"]
    lines: list[str] = []
    lines += _comment_block(MONKEYC_BANNER.splitlines(), "//")
    lines += [
        "//",
        "// Contract: docs/presentation.md — the meanings. This file carries only values.",
        "//",
        "// The watch consumes the HEX half of every token, the way the web does:",
        "// `Dc.setColor` takes a literal 0xRRGGBB on every product in garmin/manifest.xml,",
        "// and `Graphics.createColor` is not needed (nor uniformly available) for that. What",
        "// the watch does NOT have is iOS's semantic layer, so a token used here is a fixed",
        "// RGB, and this file is the only place those RGBs may be written.",
        "//",
        "// THE _MIP TWINS. The AMOLED products (fenix 8 43/47 mm) are 16 bpp and render the",
        "// hex as authored. The 8 bpp products — both fenix 8 Solars and the whole fenix 7",
        "// family — quantise every colour to a fixed 64-entry palette, one of",
        "// {0x00, 0x55, 0xAA, 0xFF} per channel. The firmware does that snapping on its own,",
        "// so passing the AMOLED literal would still *render* correctly; the twin is written",
        "// down anyway so the fallback is a reviewable value rather than a surprise, and so a",
        "// token whose nearest palette entry collides with another token's is visible here",
        "// instead of on the water. Ink.mc picks the right half per device.",
        "//",
    ]

    seen: dict[str, list[str]] = {}
    for group in MONKEYC_GROUPS:
        for token, spec in colors[group].items():
            seen.setdefault(_mip(spec["hex"]), []).append(f"{group}.{token}")
    collisions = {k: v for k, v in seen.items() if len(v) > 1}
    if collisions:
        lines.append("// Palette collisions on 8 bpp — distinguishable on AMOLED, identical")
        lines.append("// on MIP. None of these pairs is drawn on the same watch screen:")
        for literal, names in collisions.items():
            lines.append(f"//   {literal}  {' = '.join(names)}")
        lines.append("//")

    lines += [
        "import Toybox.Lang;",
        "",
        "module DesignTokens {",
    ]

    docs = {
        "outcome": "The verdict ladder. Nothing outside a maneuver outcome may borrow it.",
        "effort": "Effort and water: outside the ladder — nothing here is a verdict.",
        "phase": "Track / ring / bar tint by phase. NOT the ladder's green.",
        "direction": "Course-of-travel ink: subordinate to every mark.",
        "side": "Entry tack. A side is not a verdict — never the ladder's inks.",
    }
    for group in MONKEYC_GROUPS:
        lines.append("")
        lines.append(f"    // ---- {group}: {docs[group]}")
        for token, spec in colors[group].items():
            name = _screaming(group, token)
            lines.append(f"    // {spec['means']}")
            lines.append(f"    const {name} = {_amoled(spec['hex'])};")
            lines.append(f"    const {name}_MIP = {_mip(spec['hex'])};")
    lines += [
        "}",
        "",
    ]
    return "\n".join(lines)


# -------------------------------------------------------------------------- main


def artifacts(tokens: dict | None = None) -> dict[Path, str]:
    """Path -> content for every generated file. The one place the mapping lives, so
    `check_tokens.py` compares exactly what `generate` writes."""
    tokens = tokens if tokens is not None else load()
    return {SWIFT_OUT: swift(tokens), CSS_OUT: css(tokens), JS_OUT: js(tokens),
            MONKEYC_OUT: monkeyc(tokens)}


def main() -> int:
    written = []
    for path, content in artifacts().items():
        path.parent.mkdir(parents=True, exist_ok=True)
        old = path.read_text(encoding="utf-8") if path.exists() else None
        path.write_text(content, encoding="utf-8")
        written.append(f"  {'=' if old == content else '+'} "
                       f"{path.relative_to(REPO).as_posix()}")
    print("design tokens generated from design/tokens.json")
    print("\n".join(written))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
