#!/usr/bin/env python3
"""Generate the presentation-token artifacts from `design/tokens.json`.

`docs/presentation.md` defines what the marks *mean*; this generator is how their
*values* reach the two implementations without either one holding a private copy:

    design/tokens.json                                     <- the only file a human edits
      -> ios/WingFoilKit/Sources/WingFoilKit/Presentation/DesignTokens.swift
      -> web/css/tokens.css
      -> web/js/tokens.js

    python3 design/generate_tokens.py            # write the three artifacts
    python3 design/check_tokens.py --check       # fail (exit 1) if any of them is stale

Every colour carries two forms — a hex for the web and a semantic SwiftUI colour for
iOS — because the platforms genuinely differ: `Color.green` follows the system's light
and dark palettes and the accessibility settings, and pinning it to #0ca30c would make
the iOS app *worse*, not more consistent. The token is the pair; each side consumes its
own half, and this file is what keeps the halves in one place.

Stdlib only, and byte-stable: the output is a pure function of tokens.json, so two runs
produce identical bytes and CI can compare them.
"""

from __future__ import annotations

import json
from pathlib import Path

DESIGN = Path(__file__).resolve().parent
REPO = DESIGN.parent
TOKENS = DESIGN / "tokens.json"

SWIFT_OUT = (REPO / "ios" / "WingFoilKit" / "Sources" / "WingFoilKit" / "Presentation"
             / "DesignTokens.swift")
CSS_OUT = REPO / "web" / "css" / "tokens.css"
JS_OUT = REPO / "web" / "js" / "tokens.js"

BANNER = ("Generated by design/generate_tokens.py from design/tokens.json — do not edit.\n"
          "Edit the tokens, re-run the generator, and commit all four files together;\n"
          "design/check_tokens.py --check fails the build on drift.")


def load() -> dict:
    return json.loads(TOKENS.read_text(encoding="utf-8"))


# ------------------------------------------------------------------ small helpers


def _kebab(name: str) -> str:
    """`failedTakeoff` -> `failed-takeoff` (CSS custom-property spelling)."""
    out = []
    for ch in name:
        if ch.isupper():
            out.append("-")
            out.append(ch.lower())
        else:
            out.append(ch)
    return "".join(out)


def _num(value: float) -> str:
    """A JSON number as the shortest exact literal (0.42, not 0.42000000000000004)."""
    text = repr(float(value))
    return text[:-2] if text.endswith(".0") else text


def _swift_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _comment_block(lines: list[str], prefix: str) -> list[str]:
    return [f"{prefix} {line}".rstrip() for line in lines]


# ------------------------------------------------------------------------- Swift


def swift(tokens: dict) -> str:
    colors = tokens["colors"]
    lines: list[str] = []
    lines += _comment_block(BANNER.splitlines(), "//")
    lines += [
        "//",
        "// Contract: docs/presentation.md — the meanings. This file carries only values.",
        "",
        "import SwiftUI",
        "",
        "/// The presentation palette, generated from `design/tokens.json`.",
        "///",
        "/// iOS consumes the *semantic* half of each token (`Color.green`, `Color.teal`, …)",
        "/// so the marks keep following the system's light/dark and accessibility palettes;",
        "/// the web consumes the hex half. `Hex` is carried here too, not for drawing, but",
        "/// so a test can hold the two halves of a token against each other.",
        "public enum DesignTokens {",
        "",
    ]

    groups = [
        ("Outcome", "outcome",
         "The verdict ladder. Nothing outside a maneuver outcome may borrow it."),
        ("Effort", "effort",
         "Effort and water: deliberately outside the ladder — nothing here is a verdict."),
        ("Phase", "phase", "Track tint by phase."),
        ("Direction", "direction",
         "Course-of-travel chevrons: ink plus opacity, never a hue of its own."),
    ]
    for swift_name, key, doc in groups:
        lines.append(f"    /// {doc}")
        lines.append(f"    public enum {swift_name} {{")
        for token, spec in colors[key].items():
            lines.append(f"        /// {spec['means']}")
            lines.append(f"        public static let {token} = Color.{spec['swiftUI']}")
        lines.append("    }")
        lines.append("")

    lines.append("    /// Opacities the chevrons are drawn at, per phase (web uses its own).")
    lines.append("    public enum Opacity {")
    for name, value in tokens["opacity"].items():
        lines.append(f"        public static let {name}: Double = {_num(value)}")
    lines.append("    }")
    lines.append("")

    lines.append("    /// SF Symbols. Shape is a channel of its own — see the contract.")
    lines.append("    public enum Glyph {")
    for name, spec in tokens["glyphs"].items():
        lines.append(f"        /// {spec['means']}")
        lines.append(f"        public static let {name} = {_swift_string(spec['sfSymbol'])}")
    lines.append("    }")
    lines.append("")

    lines.append("    /// The hex half of every colour token — what the web renders. Not used")
    lines.append("    /// for drawing on iOS; it exists so the two halves stay in one file.")
    lines.append("    public enum Hex {")
    for group_key in ("outcome", "effort", "phase", "direction"):
        for token, spec in colors[group_key].items():
            name = group_key + token[0].upper() + token[1:]
            lines.append(f"        public static let {name} = {_swift_string(spec['hex'])}")
    lines.append("    }")
    lines.append("")

    records = tokens["recordWindows"]
    lines += [
        "    /// The record picker: canonical order, display labels, and the window every",
        "    /// session opens on.",
        "    public enum RecordWindows {",
        f"        public static let defaultID = {_swift_string(records['default'])}",
        "        public static let catalogue: [DesignTokenEntry] = [",
    ]
    for entry in records["order"]:
        lines.append(f"            DesignTokenEntry(id: {_swift_string(entry['id'])}, "
                     f"label: {_swift_string(entry['label'])}),")
    lines += [
        "        ]",
        "        public static let order: [String] = catalogue.map(\\.id)",
        "    }",
        "",
        "    /// The legend's layer catalogue: ids, chip text, and which layers a rider who",
        "    /// has never touched a chip sees.",
        "    public enum Layers {",
        "        public static let catalogue: [DesignTokenEntry] = [",
    ]
    for entry in tokens["layers"]:
        lines.append(f"            DesignTokenEntry(id: {_swift_string(entry['id'])}, "
                     f"label: {_swift_string(entry['label'])}),")
    lines += [
        "        ]",
        "        public static let order: [String] = catalogue.map(\\.id)",
        "        public static let visibleByDefault: [String] = [",
    ]
    for entry in tokens["layers"]:
        if entry["defaultVisible"]:
            lines.append(f"            {_swift_string(entry['id'])},")
    lines += [
        "        ]",
        "    }",
        "}",
        "",
        "/// One catalogue row: the id the code switches on, and the words the rider reads.",
        "public struct DesignTokenEntry: Sendable, Equatable, Identifiable {",
        "    public let id: String",
        "    public let label: String",
        "",
        "    public init(id: String, label: String) {",
        "        self.id = id",
        "        self.label = label",
        "    }",
        "}",
        "",
    ]
    return "\n".join(lines)


# --------------------------------------------------------------------------- CSS


def css(tokens: dict) -> str:
    lines: list[str] = ["/*"]
    lines += _comment_block(BANNER.splitlines(), " ")
    lines += [
        "",
        "  Contract: docs/presentation.md. Loaded before css/style.css, which reads these",
        "  through its own semantic names (--good, --track, …).",
        "*/",
        "",
        ":root {",
    ]
    for group in ("outcome", "effort", "phase", "direction"):
        lines.append(f"  /* {group} */")
        for token, spec in tokens["colors"][group].items():
            lines.append(f"  --wf-{group}-{_kebab(token)}: {spec['hex']};")
    lines.append("  /* opacity */")
    for name, value in tokens["opacity"].items():
        lines.append(f"  --wf-opacity-{_kebab(name)}: {_num(value)};")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------- JS


def js(tokens: dict) -> str:
    payload = {
        "outcome": {k: {"hex": v["hex"], "swiftUI": v["swiftUI"]}
                    for k, v in tokens["colors"]["outcome"].items()},
        "effort": {k: {"hex": v["hex"], "swiftUI": v["swiftUI"]}
                   for k, v in tokens["colors"]["effort"].items()},
        "phase": {k: {"hex": v["hex"], "swiftUI": v["swiftUI"]}
                  for k, v in tokens["colors"]["phase"].items()},
        "direction": {k: {"hex": v["hex"], "swiftUI": v["swiftUI"]}
                      for k, v in tokens["colors"]["direction"].items()},
        "opacity": dict(tokens["opacity"]),
        "glyphs": {k: {"sfSymbol": v["sfSymbol"], "webShape": v["webShape"]}
                   for k, v in tokens["glyphs"].items()},
        "recordWindows": {"default": tokens["recordWindows"]["default"],
                          "order": [dict(e) for e in tokens["recordWindows"]["order"]]},
        "layers": [dict(e) for e in tokens["layers"]],
    }
    body = json.dumps(payload, indent=2, ensure_ascii=False, sort_keys=False)
    lines = ["/*"]
    lines += _comment_block(BANNER.splitlines(), " ")
    lines += [
        "",
        "  Contract: docs/presentation.md. js/viz.js maps these onto its own names (C.good,",
        "  C.foil, …) so nothing downstream has to know a token from a literal.",
        "*/",
        "",
        f"export const TOKENS = {body};",
        "",
    ]
    return "\n".join(lines)


# -------------------------------------------------------------------------- main


def artifacts(tokens: dict | None = None) -> dict[Path, str]:
    """Path -> content for every generated file. The one place the mapping lives, so
    `check_tokens.py` compares exactly what `generate` writes."""
    tokens = tokens if tokens is not None else load()
    return {SWIFT_OUT: swift(tokens), CSS_OUT: css(tokens), JS_OUT: js(tokens)}


def main() -> int:
    written = []
    for path, content in artifacts().items():
        path.parent.mkdir(parents=True, exist_ok=True)
        old = path.read_text(encoding="utf-8") if path.exists() else None
        path.write_text(content, encoding="utf-8")
        written.append(f"  {'=' if old == content else '+'} "
                       f"{path.relative_to(REPO).as_posix()}")
    print("design tokens generated from design/tokens.json")
    print("\n".join(written))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
