// GENERATED by web/tools/make_start.py from docs/guide/getting-started.json.
// Do not edit by hand: regenerate, and `make_start.py --check` fails while this file and
// the source disagree.

import Foundation

/// One numbered step of one route, shown on cleanjibe.org/start.
///
/// The app does not render these — it shows a route's title and summary and sends the
/// reader to the web for the rest — but they live here anyway, because the point of the
/// generator is that one file is the guide and both surfaces are cut from it.
public struct GettingStartedStep: Sendable, Equatable, Identifiable {
    public let number: Int
    public let title: String
    public let detail: String

    public var id: Int { number }

    public init(number: Int, title: String, detail: String) {
        self.number = number
        self.title = title
        self.detail = detail
    }
}

/// One way in — a watch, a file, a cloud account — or one of the two notes that close the
/// guide (the dry run, and where to send what you found).
public struct GettingStartedRoute: Sendable, Equatable, Identifiable {
    public let id: String
    public let title: String
    /// **The lowest channel that has this door** (docs/channels.md), exactly as
    /// `HelpTopic.channel` means it: the two Apple routes are `.beta`, so an App Store
    /// build never names them and reaches them through the topic's `related` instead.
    public let channel: HelpChannel
    /// **The recording class this route yields**, as a `RecordingClass` id: `a`, `bPlus`,
    /// `b` or `c` (docs/copy/recording-classes.json). Empty on the two closing notes,
    /// which are not routes.
    ///
    /// The routes lost their letters on 16 September 2026: a route is named by what the
    /// rider holds, and what he gets back is this, which is a different ladder and has its
    /// own names. cleanjibe.org/start prints it as a pill on the card, linking to the class
    /// table; the app does not render it yet.
    public let classID: String
    /// The one or two sentences the app shows under the route's title.
    public let summary: String
    /// The numbered steps the web page shows under that summary.
    public let steps: [GettingStartedStep]

    public init(id: String, title: String, channel: HelpChannel, classID: String = "",
                summary: String, steps: [GettingStartedStep]) {
        self.id = id
        self.title = title
        self.channel = channel
        self.classID = classID
        self.summary = summary
        self.steps = steps
    }
}

/// **The getting-started guide, from the one source both platforms read.**
///
/// The app used to say "the same guide, on the web" about a page that had been written
/// separately and said different things (Jan, 15 September 2026). It is the same guide
/// now: `docs/guide/getting-started.json` holds the framing, the routes, the steps and the
/// two Settings sentences, and `web/tools/make_start.py` writes this file and the block of
/// `web/start/index.html` from it. `--check` fails while either is stale, and
/// `GettingStartedGuideTests` fails if the help topic stops matching this data.
public enum GettingStartedGuide {

    /// The one sentence that opens both the topic and the page: what the
    /// test actually is. First on purpose, on both surfaces.
    public static let framing =
        "Ride one session as you always do. Open it in CleanJibe. Check each turn: flew "
            + "through, touchdown, fell in. Only you know which it really was."

    /// The topic's own index line.
    public static let topicSummary =
        "Your first session on the water, and where to send what you find."

    /// The ways in, in the order the app and the page list them.
    public static let routes: [GettingStartedRoute] = [
        GettingStartedRoute(
            id: "garmin",
            title: "Garmin with the CleanJibe watch app",
            channel: .release,
            classID: "a",
            summary: "Install it from Connect IQ, ride, save. Sessions sync through "
                + "intervals.icu: Settings → intervals.icu, 4 steps, once.",
            steps: [
                .init(number: 1,
                      title: "Install the watch app",
                      detail: "**CleanJibe Wingfoil Tracker (Beta)** is on the Connect IQ "
                          + "store. Take it from the web, or from Connect IQ inside the "
                          + "Garmin Connect app. No key, no account."),
                .init(number: 2,
                      title: "Record and save",
                      detail: "Charge the watch and the phone. Press START, pick "
                          + "**CleanJibe**, wait for GPS good, press START again. Ride. "
                          + "Glance at the tally once. Then STOP and **Save**."),
                .init(number: 3,
                      title: "Let Garmin Connect sync",
                      detail: "The watch uploads to Garmin Connect by itself next to the "
                          + "phone. Open Garmin Connect once if it is taking its time."),
                .init(number: 4,
                      title: "Bridge it with intervals.icu",
                      detail: "Free account at intervals.icu, connect Garmin there, copy your "
                          + "personal API key, paste it into Settings → **intervals.icu**. 4 "
                          + "steps, about 5 minutes, once."),
                .init(number: 5,
                      title: "Pull down on Sessions",
                      detail: "That is the refresh: CleanJibe checks intervals.icu, imports "
                          + "what is new and analyses it as it lands. Your session appears at "
                          + "the top."),
                .init(number: 6,
                      title: "No intervals.icu? The long way",
                      detail: "connect.garmin.com → the activity → the gear icon → **Export "
                          + "File**. AirDrop it to the iPhone, then Import → **FIT or ZIP…**."),
                .init(number: 7,
                      title: "Garmin calls it Windsurf",
                      detail: "Garmin has no wingfoil profile, so Garmin and Strava call the "
                          + "session Windsurf. The jibes and the numbers are in CleanJibe, "
                          + "not in Garmin Connect or Strava."),
            ]),
        GettingStartedRoute(
            id: "appleWatchApp",
            title: "The CleanJibe Apple Watch app",
            channel: .beta,
            classID: "bPlus",
            summary: "Record on your Apple Watch. The session comes to the phone by itself, "
                + "with pump strokes and takeoff attempts included.",
            steps: [
                .init(number: 1,
                      title: "Put it on the watch",
                      detail: "It comes with the CleanJibe beta. On the iPhone open Apple's "
                          + "**Watch** app, scroll to *Available apps*, and install "
                          + "**CleanJibe** if it is missing."),
                .init(number: 2,
                      title: "Record",
                      detail: "Open CleanJibe on the watch, allow Health and Location if it "
                          + "asks, wait until NO GPS clears, press START. Then Stop, and "
                          + "Done."),
                .init(number: 3,
                      title: "Let it arrive",
                      detail: "Open CleanJibe on the iPhone. The session comes across on its "
                          + "own while phone and watch are together. Give it a minute."),
                .init(number: 4,
                      title: "What you get",
                      detail: "Speed comes off the watch's own receiver, so the records "
                          + "certify. The 50 Hz wrist gives pump strokes and takeoff "
                          + "attempts."),
            ]),
        GettingStartedRoute(
            id: "appleWorkoutApp",
            title: "Apple's own Workout app",
            channel: .beta,
            classID: "b",
            summary: "No extra app on the watch: record a Surfing workout and import it from "
                + "Apple Health.",
            steps: [
                .init(number: 1,
                      title: "Start a Surfing workout",
                      detail: "On the watch open **Workout** and pick **Surfing**. *Water "
                          + "Sports* works too. Apple Health has no wingfoil activity, so "
                          + "pick the closest one."),
                .init(number: 2,
                      title: "Ride, then end the workout",
                      detail: "End it on the watch and let it save. The route is written to "
                          + "Health when the workout finishes, which can take a minute."),
                .init(number: 3,
                      title: "Import it on the iPhone",
                      detail: "Import → **Apple Health**. Allow CleanJibe to read workouts and "
                          + "routes. Switch every one on, or there is nothing to read. Then "
                          + "pick yours."),
                .init(number: 4,
                      title: "Keep it automatic",
                      detail: "Switch on *Import new Health workouts automatically* and the "
                          + "next session is waiting when you open the app."),
                .init(number: 5,
                      title: "What you get",
                      detail: "Speed comes off the watch's own receiver, so the records "
                          + "certify. Nothing records your wrist, so there are no pump "
                          + "strokes or takeoff attempts."),
            ]),
        GettingStartedRoute(
            id: "fit",
            title: "Any watch that writes a .fit",
            channel: .release,
            classID: "b",
            summary: "Sync it through intervals.icu, or share the file into CleanJibe from "
                + "Files, Mail, AirDrop or any share sheet.",
            steps: [
                .init(number: 1,
                      title: "Record on your own watch",
                      detail: "Any outdoor activity with GPS, recorded the way you always do. "
                          + "There is nothing of ours to install on these watches."),
                .init(number: 2,
                      title: "Export the workout as a file",
                      detail: "Suunto: Calendar → the workout → ⋯ → FIT. COROS: Activities → "
                          + "the activity → ⋯ → Export → FIT. Polar exports from "
                          + "flow.polar.com only."),
                .init(number: 3,
                      title: "Take the FIT where you are offered one",
                      detail: "A FIT carries the speed your watch measured. A .gpx does not. A "
                          + ".tcx carries it only when the app wrote it in."),
                .init(number: 4,
                      title: "Hand it to CleanJibe",
                      detail: "**Open in CleanJibe** from the iOS share sheet, or Import → "
                          + "**FIT or ZIP…**. Foil time, flights, turns and the map are "
                          + "identical either way."),
                .init(number: 5,
                      title: "Or let intervals.icu do it",
                      detail: "Most of these watches sync to intervals.icu too. CleanJibe "
                          + "picks them up from there, through the same 4 steps as the Garmin "
                          + "route."),
            ]),
        GettingStartedRoute(
            id: "strava",
            title: "Strava",
            channel: .release,
            classID: "c",
            summary: "Settings → Strava → Connect with Strava, then Import → Import from "
                + "Strava…. Positions only, records uncertified. Without the watch's own "
                + "speed, a fall can read as a touchdown.",
            steps: [
                .init(number: 1,
                      title: "Connect once",
                      detail: "Settings → **Strava** → Connect with Strava. Strava's own "
                          + "consent page opens. Leave the private-activities box ticked, or "
                          + "your \"Only you\" sessions stay hidden."),
                .init(number: 2,
                      title: "Pick your sessions",
                      detail: "Import → **Import from Strava…** lists your matching activities "
                          + "of the last two years. Tap the ones you want, or **Import all "
                          + "new**."),
                .init(number: 3,
                      title: "Keep it automatic",
                      detail: "Once one session has come in this way a toggle appears, and "
                          + "CleanJibe checks Strava whenever you open the app."),
                .init(number: 4,
                      title: "What it costs",
                      detail: "Strava hands over positions rather than the speed your watch "
                          + "measured. These speed records are marked **uncertified**. There "
                          + "are no pump strokes."),
                .init(number: 5,
                      title: "If connecting is refused",
                      detail: "Strava lets a new app connect a limited number of riders. That "
                          + "is nothing to do with your account. Menu → Support & ideas says "
                          + "so."),
            ]),
    ]

    /// The two notes that close the guide: the dry run, and the report.
    public static let notes: [GettingStartedRoute] = [
        GettingStartedRoute(
            id: "dryRun",
            title: "If you cannot wait for wind",
            channel: .release,
            summary: "Record a 3 to 5 minute walk on the watch. It proves the route from the "
                + "watch to the phone, nothing else.",
            steps: [
                .init(number: 1,
                      title: "3 to 5 minutes of movement",
                      detail: "A bike ride draws the nicest track. Anything above about 12 "
                          + "km/h counts as flying. Walking works too. Go outside: indoors "
                          + "there are no positions."),
                .init(number: 2,
                      title: "Bring it in by your own route",
                      detail: "Whichever route above matches your watch. It answers one "
                          + "question: does a recording made on your watch reach CleanJibe on "
                          + "your phone?"),
                .init(number: 3,
                      title: "What you should see",
                      detail: "A map shows your track, with duration and speeds at the top. A "
                          + "speed chart moves when you drag along it."),
                .init(number: 4,
                      title: "Turns and jibes reading zero",
                      detail: "Expected on a bike or on foot: there is nothing to jibe. This "
                          + "checks the route from the watch, never the analysis."),
            ]),
        GettingStartedRoute(
            id: "sayHowItRead",
            title: "Then say how it read",
            channel: .release,
            summary: "Menu → Support & ideas opens a mail with the facts filled in. "
                + "TestFlight's own feedback works too if you are on the beta.",
            steps: [
                .init(number: 1,
                      title: "Read the verdicts against your memory",
                      detail: "Open the session and go to **Turns**. Every turn says *flew "
                          + "through*, *touched down* or *fell in*. The clean jibes are "
                          + "marked among them."),
                .init(number: 2,
                      title: "Say where it disagrees with you",
                      detail: "A jibe you know you flew through, marked as a touchdown. A swim "
                          + "it never noticed, or a wind direction you did not sail in."),
                .init(number: 3,
                      title: "Send it from the app",
                      detail: "Menu → **Support & ideas** fills in your build, phone, iOS "
                          + "version, watch and library size. You add what happened and press "
                          + "Send."),
                .init(number: 4,
                      title: "Attach the file if a session read wrong",
                      detail: "With the .fit the detection can be re-run and fixed. Without it "
                          + "there is only guesswork. Ideas and wishes are as welcome as "
                          + "faults."),
                .init(number: 5,
                      title: "Send a card, and say how it reads",
                      detail: "The share button on the session page draws a **share card** "
                          + "with your track and your numbers. Send it to a friend. Say if "
                          + "anything on it reads wrong."),
            ]),
    ]

    /// The last item of the topic, and the only one the web page does not
    /// render — a page does not send you to itself.
    public static let onTheWeb = HelpTopic.Item(
        term: "The same guide, with every step, on the web",
        detail: "\(Branding.site)/start")

    /// **Settings → intervals.icu**, the caption above the key field: why the
    /// detour exists at all, in one breath. The longer version, for the setup
    /// card and the help topic, is `IcuSetupGuide.rationale`.
    public static let settingsIcu =
        "Garmin has no open API, so intervals.icu is the bridge. Connect Garmin there once. "
            + "Every session then arrives here by itself. Free."

    /// **Settings → Strava**, the caption above the connect button: what this
    /// account is for, and what it costs. The footer under the button says the
    /// rest — what is read, what is never written, and the connection cap.
    public static let settingsStrava =
        "Any watch that syncs to Strava, no file needed. Positions only, so speed records are "
            + "uncertified. Without the watch's own speed, a fall can read as a touchdown."

    /// The routes and notes a build on `channel` may name, as the help topic's items —
    /// title as the term, summary as the detail — with the web page named last.
    ///
    /// **The channel comes from the app** (`HelpCatalog.topic(_:channel:)`, dev 65). The
    /// catalogue declares the topic with `.release`, because a static array cannot ask
    /// which build is reading it, and the lookup rebuilds the items for the channel the
    /// app hands in. So the two Apple routes are named by no release build, and are items
    /// on the two channels that have them; either way they are also topics on `related`,
    /// which `relatedTopics(of:channel:)` filters the same way.
    public static func items(for channel: HelpChannel) -> [HelpTopic.Item] {
        let ways = (routes + notes)
            .filter { channel.has($0.channel) }
            .map { HelpTopic.Item(term: $0.title, detail: $0.summary) }
        return ways + [onTheWeb]
    }
}
