#!/usr/bin/env python3
"""Cut the beta and dev channel marks from the release artwork, for every place they go.

The release mark is brand/icon-square.svg, rendered once to icon-square-1024.png (full
bleed, what iOS masks itself) and icon-tile-1024.png (the rounded tile with its own corners,
what the in-app splash, the welcome screen, the watch start page and the Garmin launcher
show). Those two PNGs are the inputs here; nothing is re-rendered from the SVG, so the
channel marks are pixel-identical to the release mark everywhere the treatment does not
touch.

The treatments are brand/tools/channelmark.py's: a red BETA label upper right for the beta,
a left-right mirror for dev (docs/channels.md, "Telling the channels apart").

What is written, per channel (beta, dev):

  brand/icon-square-<ch>-1024.png, icon-tile-<ch>-1024.png     the reference renders
  brand/icon-square-<ch>.svg                                    the same treatment on the
                                                                master, for the record
  ios/WingFoil/Resources/Assets.xcassets/
      AppIcon-<Ch>.appiconset/AppIcon.png                       1024, full bleed
      SplashMark-<Ch>.imageset/SplashMark[@2x|@3x].png           140 / 280 / 420, tile
      LaunchMark-<Ch>.imageset/LaunchMark.png                    512, tile
  ios/WingFoilWatch/Resources/Assets.xcassets/
      AppIcon-<Ch>.appiconset/AppIcon.png                       1024, full bleed, label
                                                                placed inside the circle
      BrandMark-<Ch>.imageset/BrandMark@2x.png                   96, tile
  garmin/resources-<ch>/icon{65,60,54,40}/drawables/
      launcher_icon.png                                         the tile at each native
                                                                launcher size
      drawables.xml                                             the four bitmap ids

The Garmin ink-only cuts (brand_mark, brand_badge, brand_hero) in those same directories
come from garmin/tools/make_brand_mark.py, which applies the same two treatments to its own
render. Run both after touching the artwork:

    python3 brand/tools/make_channel_marks.py
    python3 garmin/tools/make_brand_mark.py
"""

import json
import os
import re
import shutil
import sys

from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, HERE)
from channelmark import (LABEL_RGB, LABEL_TEXT, label_for_circle, label_for_square,  # noqa: E402
                         label_size, mirror)

BRAND = os.path.join(ROOT, "brand")
IOS_APP = os.path.join(ROOT, "ios", "WingFoil", "Resources", "Assets.xcassets")
IOS_WATCH = os.path.join(ROOT, "ios", "WingFoilWatch", "Resources", "Assets.xcassets")
GARMIN = os.path.join(ROOT, "garmin")

CHANNELS = ("beta", "dev")

GARMIN_LAUNCHER_SIZES = (65, 60, 54, 40)

GARMIN_DRAWABLES_XML = """<drawables>
    <!-- GENERATED by brand/tools/make_channel_marks.py and garmin/tools/make_brand_mark.py:
         the {channel} channel's cut of the four brand bitmaps, appended to this size class's
         resourcePath in monkey-{jungle}.jungle so these ids override the release ones.
         Same sizes as the release cuts next door; only the treatment differs
         (docs/channels.md, "Telling the channels apart"). -->
    <bitmap id="LauncherIcon" filename="launcher_icon.png"/>
    <bitmap id="BrandMark" filename="brand_mark.png" dithering="none"/>
    <bitmap id="BrandBadge" filename="brand_badge.png" dithering="none"/>
    <bitmap id="BrandHero" filename="brand_hero.png" dithering="none"/>
</drawables>
"""

# Which jungle carries which channel — the Garmin naming predates the channels and is the
# other way round from what the file names suggest (garmin/store/listing.md, "Naming trap").
GARMIN_JUNGLE = {"beta": "invite", "dev": "beta"}


def treat(img, channel, shape="square"):
    """Apply a channel's treatment to a copy of `img`."""
    out = img.copy()
    if channel == "dev":
        return mirror(out)
    if channel == "beta":
        return label_for_circle(out) if shape == "circle" else label_for_square(out)
    return out


def save(img, path, mode=None):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    if mode and img.mode != mode:
        img = img.convert(mode)
    img.save(path, optimize=True)
    print(f"{os.path.relpath(path, ROOT)}  {img.width}x{img.height}")


def resized(img, side):
    return img.resize((side, side), Image.LANCZOS)


def copy_contents(src_set, dst_set):
    """An asset set's Contents.json, verbatim: the file names inside the set stay the same,
    only the set's own name carries the channel."""
    os.makedirs(dst_set, exist_ok=True)
    shutil.copyfile(os.path.join(src_set, "Contents.json"), os.path.join(dst_set, "Contents.json"))


def svg_variant(channel):
    """The master SVG with the same treatment, so the vector record matches the pixels."""
    src = os.path.join(BRAND, "icon-square.svg")
    with open(src, encoding="utf-8") as f:
        svg = f.read()
    note = (f"<!-- GENERATED by brand/tools/make_channel_marks.py from icon-square.svg: the "
            f"{channel} channel's mark. Edit the master, then rerun; do not edit this file. -->\n")
    if channel == "dev":
        # Everything after the ground rect is drawn mirrored about the vertical centre line.
        m = re.search(r'<rect width="100" height="100"[^>]*/>\n', svg)
        i = m.end()
        svg = svg[:i] + '<g transform="translate(100 0) scale(-1 1)">\n' + svg[i:]
        svg = svg.replace("</svg>", "</g>\n</svg>")
    elif channel == "beta":
        w1024, h1024 = label_size(1024 * 0.146)
        w, h = w1024 / 10.24, h1024 / 10.24
        x1, y0 = 100 - 8.6, 8.6
        fill = "#%02X%02X%02X" % LABEL_RGB
        label = (f'<g><rect x="{x1 - w:.2f}" y="{y0:.2f}" width="{w:.2f}" height="{h:.2f}" '
                 f'rx="{h * 0.28:.2f}" fill="{fill}"/>\n'
                 f'<text x="{x1 - w / 2:.2f}" y="{y0 + h * 0.5:.2f}" font-family="Helvetica, Arial, sans-serif" '
                 f'font-weight="bold" font-size="{h * 0.62:.2f}" fill="#FFFFFF" text-anchor="middle" '
                 f'dominant-baseline="central">{LABEL_TEXT}</text></g>\n')
        svg = svg.replace("</svg>", label + "</svg>")
    svg = svg.replace("<svg ", note + "<svg ", 1)
    out = os.path.join(BRAND, f"icon-square-{channel}.svg")
    with open(out, "w", encoding="utf-8") as f:
        f.write(svg)
    print(os.path.relpath(out, ROOT))


def main():
    square = Image.open(os.path.join(BRAND, "icon-square-1024.png")).convert("RGB")
    tile = Image.open(os.path.join(BRAND, "icon-tile-1024.png")).convert("RGBA")

    for ch in CHANNELS:
        Ch = ch.capitalize()
        sq = treat(square, ch)
        tl = treat(tile, ch)

        # The record.
        save(sq, os.path.join(BRAND, f"icon-square-{ch}-1024.png"), "RGB")
        save(tl, os.path.join(BRAND, f"icon-tile-{ch}-1024.png"), "RGBA")
        svg_variant(ch)

        # The phone.
        dst = os.path.join(IOS_APP, f"AppIcon-{Ch}.appiconset")
        copy_contents(os.path.join(IOS_APP, "AppIcon.appiconset"), dst)
        save(sq, os.path.join(dst, "AppIcon.png"), "RGB")

        dst = os.path.join(IOS_APP, f"SplashMark-{Ch}.imageset")
        copy_contents(os.path.join(IOS_APP, "SplashMark.imageset"), dst)
        for name, side in (("SplashMark.png", 140), ("SplashMark@2x.png", 280), ("SplashMark@3x.png", 420)):
            save(resized(tl, side), os.path.join(dst, name), "RGBA")

        dst = os.path.join(IOS_APP, f"LaunchMark-{Ch}.imageset")
        copy_contents(os.path.join(IOS_APP, "LaunchMark.imageset"), dst)
        save(resized(tl, 512), os.path.join(dst, "LaunchMark.png"), "RGBA")

        # The Apple Watch: its icon is cut to a circle, so the label moves in.
        dst = os.path.join(IOS_WATCH, f"AppIcon-{Ch}.appiconset")
        copy_contents(os.path.join(IOS_WATCH, "AppIcon.appiconset"), dst)
        save(treat(square, ch, "circle"), os.path.join(dst, "AppIcon.png"), "RGB")

        dst = os.path.join(IOS_WATCH, f"BrandMark-{Ch}.imageset")
        copy_contents(os.path.join(IOS_WATCH, "BrandMark.imageset"), dst)
        save(resized(tl, 96), os.path.join(dst, "BrandMark@2x.png"), "RGBA")

        # The Garmin launcher, at each size class the jungles map products to.
        for side in GARMIN_LAUNCHER_SIZES:
            d = os.path.join(GARMIN, f"resources-{ch}", f"icon{side}", "drawables")
            save(resized(tl, side), os.path.join(d, "launcher_icon.png"), "RGBA")
            with open(os.path.join(d, "drawables.xml"), "w", encoding="utf-8") as f:
                f.write(GARMIN_DRAWABLES_XML.format(channel=ch, jungle=GARMIN_JUNGLE[ch]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
