import Foundation

/// The channel's cut of the brand mark, by asset name (docs/channels.md, "Telling the
/// channels apart").
///
/// Three builds of this app can sit on one phone — the App Store one, the beta and the dev
/// app — and they are told apart by their icon before anything else: the release mark as
/// drawn, a red BETA label upper right for the beta, the mark mirrored (wing upper RIGHT)
/// for dev. The app icon itself is picked per configuration in project.yml
/// (`ASSETCATALOG_COMPILER_APPICON_NAME`), and the launch screen's image through
/// `CJ_SPLASH_MARK`; this is the same choice for the two places code names the mark — the
/// splash that takes over from the launch screen and the welcome page.
///
/// NOT the share card, its QR centre or anything that leaves the phone: those carry the
/// release mark in every channel, because a card promotes CleanJibe, not the build that
/// rendered it. The cuts are generated by brand/tools/make_channel_marks.py.
enum ChannelArt {
    #if DEV
    static let splashMark = "SplashMark-Dev"
    static let launchMark = "LaunchMark-Dev"
    #elseif BETA
    static let splashMark = "SplashMark-Beta"
    static let launchMark = "LaunchMark-Beta"
    #else
    static let splashMark = "SplashMark"
    static let launchMark = "LaunchMark"
    #endif
}
